### ISSUE TITLE
Update OKD-based CRC build (2022-02)

### ISSUE THREAD

**Issue by justkrys** [okd-project/okd#1123]
**Describe the bug**

Same issue as #636.  OKD CRC certificates are expired.

Also, an observation in the hope it helps:
This is my OKD/OpenShift "What the heck is it" first experience.  The minimal commitment for me is CRC.  Oops, it's out of date and broken. :(  
I wonder if either longer cert expiry or an automated monthly build of OKD CRC would make for a better first time experience.
As it stands now, I either have to signup for a Redhat 30-day Trial or commit to a full OKD install (say on AWS or whatever) just to be able to do some hands on exploring.  Either path is less palatable than a working OKD CRC.
Not to mention that I only find this out after several Gib of downloads.
Anyway, hope you take this in the kind spirit it is offered. :)

**Version**

4.9.15, I guess.

**How reproducible**

100%. Certs expire every 30 days.  The CRC is dated Nov 2021.

**Log bundle**

```
INFO Kubelet client certificate has expired, renewing it... [will take up to 8 minutes] 
INFO Kubelet serving certificate has expired, waiting for automatic renewal... [will take up to 8 minutes] 
Failed to renew TLS certificates: please check if a newer CodeReady Containers release is available: Temporary error: certificate /var/lib/kubelet/pki/kubelet-server-current.pem still expired (x60)
```

```
WARN A new version (1.39.0) has been published on https://developers.redhat.com/content-gateway/file/pub/openshift-v4/clients/crc/1.39.0/crc-linux-amd64.tar.xz 
```

**Comment by vrutkovs** [comment]
cc  @cgruver

**Comment by cgruver** [comment]
@justkrys   Fully understand your frustration.  The OKD build of CRC hasn't been getting much attention since it's all volunteer, and for a while I've been the sole volunteer...  :-)

If it helps, you can get the official CRC free of charge, and it does not require a 30 day trial.

It does require that you sign up for a Red Hat developer account to get a pull secret, but that's also free and gets you access to some nice free books and other resources.  The CRC install does not limit you to a 30 day trial.

https://cloud.redhat.com/openshift/create/local

**Comment by cgruver** [comment]
OKD CRC isn't dead, it just doesn't have a community invested in it yet.

OKD has a vibrant community around it, so it's not going anywhere.  But, that really is the difference.  There's enough interest in OKD, and users of OKD that there are folks both in and out of Red Hat who spend time contributing to it.

CRC just hasn't found that level of interest.  I built and maintained the first few releases of CRC for OKD as a favor.  But I have never been a user of it.  

Thus, if I have to choose where to invest my FOSS community contributions, it's going to be on projects that I am actively using.  This is just the nature of FOSS.

I really would encourage @everflux and @justkrys, if you have some time, we'd love for you to join the OKD community.

There are a few other folks who have expressed interest in getting a CRC group formed to maintain it.  They'd love for you to join them.  https://github.com/openshift/community#okd-working-group-meetings

I've published some info on how to build CRC for OKD.  My forks of crc and snc are likely out of date now, but it might get you started.

https://upstreamwithoutapaddle.com/home-lab/okd-crc/

Cheers

**Comment by justkrys** [comment]
> 

Thanks very much for the information and alternative path.  I will check that out as a starting point.

Also thank you for your invitation to join the community.  :)  Unfortunately, I leaned long ago that I do not have the right personality type for any sustained engagement with any community.  But I will check things out.  Who knows, things change.

Anyway, thanks again for the help. :D

**Comment by justkrys** [comment]
One thought, though, if OKD CRC is not getting the love it needs, maybe a word about that in the install docs might be in order.  Perhaps an open invitation for help.  Just so people are not surprised and confused.

Thanks again!

**Comment by cgruver** [comment]
@justkrys It takes all types of personalities to make a community.  Come on over.

:-)

**Comment by gbraad** [comment]
> This is my OKD/OpenShift "What the heck is it" first experience. The minimal commitment for me is CRC. Oops, it's out of date and broken. :(

This issue comes from the upstream OpenShift release that prevents certificates to exist longer than 30 days. We from @code-ready/crc-team have tried to resolve this for a long time, but has been denied

**Comment by gbraad** [comment]
My proposal is as follows:

![image](https://user-images.githubusercontent.com/1894/158747206-bd653a31-042c-48d2-aefb-ccd4db314d52.png)

**Comment by cgruver** [comment]
@gbraad   Let me get some time set aside for this, and I'll work with @praveenkumar.

**Comment by kai-uwe-rommel** [comment]
If the OKD based CRC is no longer useable, it should be taken offline to not confuse and frustrate potential users.

**Comment by martinbel** [comment]
I'm getting this on the latest version: 
```
INFO Kubelet client certificate has expired, renewing it... [will take up to 8 minutes] 
Failed to renew TLS certificates: please check if a newer CodeReady Containers release is available: Temporary error: certificate /var/lib/kubelet/pki/kubelet-client-current.pem still expired (x60)

```

**Comment by JaimeMagiera** [comment]
I’ve been asking for a volunteer to do a fresh build. So far no takers. At the WG Docs Subcommittee meeting Tuesday, I’ll add this topic to the agenda.

**Comment by gbraad** [comment]
The certificate renewal process should work. Please delete and retry start. If this remains this needs to be looked into soon. Ideally we want to make automated images for okd-crc, but need access to the location to store these.
________________________________

**Comment by gbraad** [comment]
@JaimeMagiera can the volunteer reach out to us? getting the preset working and let us do part of the upstream releases will solve the problem long-term

**Comment by cgruver** [comment]
Hey guys, apologies that I'm MIA here.  #DayJob has consumed everything.

@JaimeMagiera Did you get a volunteer?

**Comment by cgruver** [comment]
@JaimeMagiera I may be able to set aside some time over in the next couple of weeks.  I'll keep you posted.

**Comment by gbraad** [comment]
It is not a thing you do in just a few mins. We are still in the process to automate some stuff. We might pick this up also soon. Any assistance is welcomed. Currently we are looking into enabling upstream bundles in our regular builds... This could become a replacement for the okd-crc fork.

**Comment by titou10titou10** [comment]
It seems OpenShift CodeReady is now [OpenShift Local](https://developers.redhat.com/products/openshift-local/overview)...    
Don't know if there is an OKD "flavor" of OpenShift Local...

**Comment by gbraad** [comment]
OpenShift Local is a rebrand of CodeReady Containers, but the command and project are still named `crc`.
We are moving CRC to be the upstream effort for also OKD, so yes... it will hopefully support this soon as a preset.
But I do not think there will be a flavour of this as OpenShift Local is a productization of CRC...

You will see `crc` releases to be made on our github page and hopefully this issue tracker can be seen as preset-/bundle specific.

Does this answer your question?

**Comment by myjoshtheflame** [comment]
> If the OKD based CRC is no longer useable, it should be taken offline to not confuse and frustrate potential users.

Spot on ..l just started exploring Openshift and I am extremly confused if I should use OKD or CRC but hanging here and there to be honest

**Comment by JaimeMagiera** [comment]
Yes. That is the overall issue. The certificate expires and the installer needs to be recreated. We (the OKD Working Group) are looking for a volunteer to build a fresh installer. We just don't have the cycles.

**Comment by VGerris** [comment]
I made it work with the workaround, but happy to build it. Any instructions
to follow, access needed? Can pm me

Den tors 23 juni 2022 11:41Jaime Magiera ***@***.***> skrev:

**Comment by praveenkumar** [comment]
As part of crc-2.x we have decoupled the bundle from the crc binary and as part of setup we download it. It will allow us to generate the bundle adhoc fashion and upload it publicly and renew the bundle when cert expire. Bundle generation happen from https://github.com/code-ready/snc/ and have instruction about how to create an OKD bundle. Our (crc team) near term goal is to put more document/how-to for bundle creation and also update the bundle to latest okd release sooner. We are working on having those bundles as part of container image which will allow us to upload those quickly to quay.io than waiting for any internal/fedora infra.

**Comment by VGerris** [comment]
thanks, docs are appreciated. the latest crc binary with oc 4.10 "just works" on my ubuntu 22.04 now, when I tried to follow instructions for snc I got into all kind of redhat related things to get libvirt and other stuff installed.
When working around it in the script, eventually it complaiend about tcp for libvirt - not sure why because it seems everything works as it should now. Anyway, happy to give it another shot if there are more docs, perhaps I can add Ubuntu support if wished for. Thank you

**Comment by gbraad** [comment]
https://github.com/code-ready/blog/pull/6
Functionality has been added to the 2.7.1 of CRC: https://github.com/code-ready/crc/releases/tag/v2.7.1

**Comment by gbraad** [comment]
One of the next steps is to describe the automated generation flow. Perhaps a terraform or pulumi definition of the setup might help.

**Comment by LorbusChris** [comment]
> [code-ready/blog#6](https://github.com/code-ready/blog/pull/6) Functionality has been added to the 2.7.1 of CRC: https://github.com/code-ready/crc/releases/tag/v2.7.1

https://crc.dev/blog/posts/2022-08-22-okd-on-crc/

**Comment by kaovilai** [comment]
Awesome!

Too bad I can't Circle/TravisCI this for https://app.circleci.com/pipelines/github/kaovilai/reliable-ci/15/workflows/e65e2e00-0e06-44da-9598-a0d1a0e593a3/jobs/22

**Comment by gbraad** [comment]
We need to update the info on https://www.okd.io/crc/
The current version published there is nearly unusable due to cert rotation

any idea where we can propose these changes?

/cc @vrutkovs @JaimeMagiera @cgruver

**Comment by gbraad** [comment]
@praveenkumar is a longer term cert extension possible for the OKD bundle too or is this already published?

**Comment by cgruver** [comment]
The site content is here: [https://github.com/okd-project/okd.io](https://github.com/okd-project/okd.io)

Those images are almost a year old too.  It's the last CRC for OKD that I built manually.

I'll bring it up in the next OKD working group meeting.  For now, that content should probably just be removed until we have an automated process to build OKD bundles.

**Comment by kai-uwe-rommel** [comment]
Are you sure it is worth investing scarce manpower into CRC for OKD? The CRC from Red Hat based on OCP is basically free to use, too (you just need a free Red Hat developer account).

**Comment by VGerris** [comment]
I think it is, people run OKD for a reason. The idea of the image decoupled
is better too. I would made an attempt if there was documentation that made
the workings and packaging clearer. I see no reason why CRC cannot be
improved to just point to an image for OKD or Openshift, have certificate
rotation or have them valid for 20 years.
Up to day I have still not run OKD locally to test it because of this.
Thank you

**Comment by vrutkovs** [comment]
Good news, this has been resolved in CRC itself. Now it has `presets` and OKD is included. See https://crc.dev/blog/posts/2022-08-22-okd-on-crc/

**Comment by praveenkumar** [comment]
> @praveenkumar is a longer term cert extension possible for the OKD bundle too or is this already published?

No, I still have to figure out this for OKD bundles. I will discuss that internally with @vrutkovs next week and try to create next bundle with cert validity of 1 year.

**Comment by VGerris** [comment]
Great. Why not make it 30 years? Or have a refresh mechanism.

**Comment by praveenkumar** [comment]
> Or have a refresh mechanism.

@VGerris cert refresh mechanism already present and rotation happen successfully, it just take more time (extra for cert rotation) than usual.

**Comment by praveenkumar** [comment]
> > 
> 
> hi, ok, how does one do that?

@VGerris End user doesn't have to do anything, it just happen automatic when cert expire.
