### ISSUE TITLE
Installed in vmware/vcenter a new OKD 4.10.0-0.okd-2022-04-23-131357 cluster, but the install didn't finish within the 30 min timeframe

### ISSUE THREAD

**Issue by johnlongo** [okd-project/okd#1208]
Installed in vmware/vcenter  (openshift-install create cluster --dir /opt/install --log-level=info ) a new OKD 4.10.0-0.okd-2022-04-23-131357 cluster, but the install didn't finish within the 30 min time frame.

The cluster did eventually finish deploying but never deleted the bootstrap node, now when I bring the cluster up (I don't start the bootstrap node) it is giving me a unhealthy warning about etcd bootstrap see below. What do I need to do to get rid of the bootstrap dependency in a functioning cluster?

[root@config okd-scripts]# oc get -o yaml clusteroperator etcd
apiVersion: config.openshift.io/v1
kind: ClusterOperator
metadata:
  annotations:
    exclude.release.openshift.io/internal-openshift-hosted: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
  creationTimestamp: "2022-05-03T17:24:28Z"
  generation: 1
  name: etcd
  ownerReferences:
  - apiVersion: config.openshift.io/v1
    kind: ClusterVersion
    name: version
    uid: 56981808-c81e-46e3-a6cc-5477061429c1
  resourceVersion: "72694"
  uid: eed2cb9e-2775-4421-b827-ea5fa5a808ee
spec: {}
status:
  conditions:
  - lastTransitionTime: "2022-05-03T17:39:39Z"
    reason: ControllerStarted
    status: Unknown
    type: RecentBackup
  - lastTransitionTime: "2022-05-03T20:40:12Z"
    message: |-
      ClusterMemberControllerDegraded: unhealthy members found during reconciling members
      DefragControllerDegraded: cluster is unhealthy: 3 of 4 members are available, etcd-bootstrap is unhealthy
      EtcdMembersDegraded: 3 of 4 members are available, etcd-bootstrap is unhealthy
    reason: ClusterMemberController_Error::DefragController_Error::EtcdMembers_UnhealthyMembers
    status: "True"
    type: Degraded
  - lastTransitionTime: "2022-05-03T18:01:31Z"
    message: |-
      NodeInstallerProgressing: 3 nodes are at revision 7
      EtcdMembersProgressing: No unstarted etcd members found
    reason: AsExpected
    status: "False"
    type: Progressing
  - lastTransitionTime: "2022-05-03T17:42:10Z"
    message: |-
      StaticPodsAvailable: 3 nodes are active; 3 nodes are at revision 7
      EtcdMembersAvailable: 3 of 4 members are available, etcd-bootstrap is unhealthy
    reason: AsExpected
    status: "True"
    type: Available
  - lastTransitionTime: "2022-05-03T17:39:39Z"
    message: All is well
    reason: AsExpected
    status: "True"
    type: Upgradeable
  extension: null
  relatedObjects:
  - group: operator.openshift.io
    name: cluster
    resource: etcds
  - group: ""
    name: openshift-config
    resource: namespaces
  - group: ""
    name: openshift-config-managed
    resource: namespaces
  - group: ""
    name: openshift-etcd-operator
    resource: namespaces
  - group: ""
    name: openshift-etcd
    resource: namespaces
  versions:
  - name: raw-internal
    version: 4.10.0-0.okd-2022-04-23-131357
  - name: etcd
    version: 4.10.0-0.okd-2022-04-23-131357
  - name: operator
    version: 4.10.0-0.okd-2022-04-23-131357

**Comment by fortinj66** [comment]
Log into the bootstrap node and look at the journal. It may give an indication why it didn’t omplete

**Comment by johnlongo** [comment]
found the issue looks like I'm missing a dns entry see below
The instructions on the web page did not say I needed a dns entry for api-int see below

![image](https://user-images.githubusercontent.com/23619505/166587330-8addd8ff-b649-4a4d-9da7-efb033842205.png)

![image](https://user-images.githubusercontent.com/23619505/166587454-c42e29e1-3954-4673-b7af-88fa2e165a39.png)

**Comment by fortinj66** [comment]
You've hit a known issue in the installer.  It should be fixed in the next release:

https://github.com/openshift/okd/issues/1182

**Comment by fortinj66** [comment]
> found the issue looks like I'm missing a dns entry see below
> The instructions on the web page did not say I needed a dns entry for api-int see below

bootstrap node should be resolving api-int.<domain> so you shouldn't need an external DNS entry

**Comment by johnlongo** [comment]
In the meantime adding the dns entry worked for me 
![image](https://user-images.githubusercontent.com/23619505/166608147-b6de2d5e-8944-48e0-9d76-c67c7ba67a83.png)

**Comment by wouterbouvy** [comment]
I can confirm I have this issue on my vSphere IPI install asiel with 4.11.0-0.okd-2022-08-20-022919
Manually adding the api-int DNS record to my DNSmasq config works around this issue

**Comment by JaimeMagiera** [comment]
Closed per https://github.com/openshift/installer/pull/5788
