### ISSUE TITLE
Error from server (InternalError): Internal error occurred: error resolving resource when execuiting oc

### ISSUE THREAD

**Issue by bdlink** [okd-project/okd#1222]
**Describe the bug**
in some circumstances oc get returns an error due to internal server error (with no more information about the problem.

1. apply the attached yaml file (creates a CRD for new kind "runner")
2. oc get runners.apps.gitlab.com
3. results in internal system error.

The yaml file is accepted, even though it has an erroneous field (probably the yaml file should be rejected).

At this point you will 
1 not be able to delete projects (they will hang in terminating),
2. not be able to delete pods from the console,
3. not be able to delete the Runner CRD from the console (it will hang in terminating)
As well, successful or failed cronJobs will not get deleted, and collect-profiles, ip-reconciler, and image-pruner  pods will multiply indefinitely.

To undo this, edit the Runner CRD to remove the caBundle: field and save it.  Then delete the Runner CRD.

**Version**
 OKD version release: 4.10.0-0.okd-2022-05-07-021833
UPI install method on vSphere

**How reproducible**
100%

**Log bundle**
Not included.
[gitlab-runner.yaml.txt](https://github.com/openshift/okd/files/8674369/gitlab-runner.yaml.txt)

**Comment by vrutkovs** [comment]
I don't think its OKD specific, this probably should be filed as a bugzilla?

**Comment by JaimeMagiera** [comment]
@bdlink Given the response on https://bugzilla.redhat.com/show_bug.cgi?id=2084960, how do you want to proceed with this issue? My sense is that it's framed as "works as expected". On the other hand, improved feedback to the user would be good.
