### ISSUE TITLE
SamplesImagestreamImportFailing alert keeps triggering after upgrading cluster

### ISSUE THREAD

**Issue by kai-uwe-rommel** [okd-project/okd#1251]
**Describe the bug**
A cluster was initially installed with OKD 4.6 and over the time upgraded to 4.7/4.8/4.9 and now 4.10, it is currently on the 2022-05-28 version.
Since upgrading to 4.10, the SamplesImagestreamImportFailing alert keeps triggering.

`Samples operator is detecting problems with imagestream image imports. You can look at the "openshift-samples" ClusterOperator object for details. Most likely there are issues with the external image registry hosting the images that needs to be investigated. Or you can consider marking samples operator Removed if you do not care about having sample imagestreams available. The list of ImageStreams for which samples operator is retrying imports: dotnet dotnet-runtime httpd mariadb mysql openliberty perl php postgresql python redis ruby wildfly wildfly-runtime `

**Version**
OKD 4.10 2022-05-28

**How reproducible**
100%, seen on two clusters.

**Log bundle**
Will provide if wanted/considered useful.
See samples operator log snipped below.

**Comment by kai-uwe-rommel** [comment]
This is a sample from the cluster-samples-operator's log:
```
time="2022-06-04T09:02:54Z" level=info msg="initiated an imagestreamimport retry for imagestream/tag wildfly-runtime/22.0"
time="2022-06-04T09:02:54Z" level=warning msg="Image import for imagestream wildfly-runtime tag 23.0 generation 2 failed with detailed message Internal error occurred: registry.redhat.io/wildfly/wildfly-runtime-centos7:23.0: unknown: Not Found"
time="2022-06-04T09:02:54Z" level=info msg="initiated an imagestreamimport retry for imagestream/tag wildfly-runtime/23.0"
time="2022-06-04T09:02:54Z" level=warning msg="Image import for imagestream wildfly-runtime tag 24.0 generation 2 failed with detailed message Internal error occurred: registry.redhat.io/wildfly/wildfly-runtime-centos7:24.0: unknown: Not Found"
time="2022-06-04T09:02:55Z" level=info msg="initiated an imagestreamimport retry for imagestream/tag wildfly-runtime/24.0"
time="2022-06-04T09:02:55Z" level=warning msg="Image import for imagestream wildfly-runtime tag 25.0 generation 2 failed with detailed message Internal error occurred: registry.redhat.io/wildfly/wildfly-runtime-centos7:25.0: unknown: Not Found"
time="2022-06-04T09:02:55Z" level=info msg="initiated an imagestreamimport retry for imagestream/tag wildfly-runtime/25.0"
time="2022-06-04T09:02:55Z" level=warning msg="Image import for imagestream wildfly-runtime tag 26.0 generation 2 failed with detailed message Internal error occurred: registry.redhat.io/wildfly/wildfly-runtime-centos7:26.0: unknown: Not Found"
time="2022-06-04T09:02:55Z" level=info msg="initiated an imagestreamimport retry for imagestream/tag wildfly-runtime/26.0"
time="2022-06-04T09:02:55Z" level=warning msg="Image import for imagestream wildfly-runtime tag latest generation 2 failed with detailed message Internal error occurred: registry.redhat.io/wildfly/wildfly-runtime-centos7:latest: unknown: Not Found"
time="2022-06-04T09:02:56Z" level=info msg="initiated an imagestreamimport retry for imagestream/tag wildfly-runtime/latest"
time="2022-06-04T09:02:56Z" level=info msg="clearImageStreamTagError: stream jenkins-agent-base already deleted so no worries on clearing tags"
time="2022-06-04T09:02:56Z" level=info msg="There are no more errors or image imports in flight for imagestream jenkins-agent-base"
time="2022-06-04T09:02:56Z" level=warning msg="Image import for imagestream dotnet tag 3.1 generation 2 failed with detailed message Internal error occurred: registry.redhat.io/dotnet/dotnet-31-centos7:latest: unknown: Not Found"
time="2022-06-04T09:02:56Z" level=info msg="initiated an imagestreamimport retry for imagestream/tag dotnet/3.1"
time="2022-06-04T09:02:56Z" level=warning msg="Image import for imagestream dotnet tag 3.1-el7 generation 2 failed with detailed message Internal error occurred: registry.redhat.io/dotnet/dotnet-31-centos7:latest: unknown: Not Found"
time="2022-06-04T09:02:56Z" level=info msg="initiated an imagestreamimport retry for imagestream/tag dotnet/3.1-el7"
time="2022-06-04T09:02:56Z" level=info msg="clearImageStreamTagError: stream ubi8-openjdk-8-runtime already deleted so no worries on clearing tags"
time="2022-06-04T09:02:56Z" level=info msg="There are no more errors or image imports in flight for imagestream ubi8-openjdk-8-runtime"
time="2022-06-04T09:02:56Z" level=info msg="clearImageStreamTagError: stream java already deleted so no worries on clearing tags"
time="2022-06-04T09:02:56Z" level=info msg="There are no more errors or image imports in flight for imagestream java"
time="2022-06-04T09:02:56Z" level=warning msg="Image import for imagestream mysql tag 8.0 generation 2 failed with detailed message Internal error occurred: registry.redhat.io/centos7/mysql-80-centos7:latest: unknown: Not Found"
time="2022-06-04T09:02:57Z" level=info msg="initiated an imagestreamimport retry for imagestream/tag mysql/8.0"
time="2022-06-04T09:02:57Z" level=warning msg="Image import for imagestream mysql tag 8.0-el7 generation 2 failed with detailed message Internal error occurred: registry.redhat.io/centos7/mysql-80-centos7:latest: unknown: Not Found"
time="2022-06-04T09:02:57Z" level=info msg="initiated an imagestreamimport retry for imagestream/tag mysql/8.0-el7"
time="2022-06-04T09:02:57Z" level=warning msg="Image import for imagestream mysql tag 8.0-el8 generation 2 failed with detailed message Internal error occurred: registry.redhat.io/centos/mysql-80-centos8:latest: unknown: Not Found"

```

**Comment by kai-uwe-rommel** [comment]
I have already deleted the imagestream objects mentioned in the alert message.
They were recreated automatically.
Their associated image objects were also automatically deleted and recreated.
But the alert persists.

**Comment by LorbusChris** [comment]
Does https://docs.okd.io/4.10/openshift_images/configuring-samples-operator.html#samples-operator-retries help with this issue?

**Comment by kai-uwe-rommel** [comment]
@LorbusChris what exactly on this page do you mean? I don't see anything there that could help.

**Comment by kai-uwe-rommel** [comment]
But both does not seem to be a solution, just a method to get it out of my way?
And setting it to Removed simply disables the functionality ...
Why does the Samples operator fail? Why on my two clusters and not on others?
How to diagnose and fix?

**Comment by kai-uwe-rommel** [comment]
I'll try setting to Removed and then to Managed again and wait for a day and see what happens.

**Comment by kai-uwe-rommel** [comment]
After doing that, the alert cleared. But after a couple of hours, it is now back.
I guess, this will need some debugging and fixing. But how?

**Comment by LorbusChris** [comment]
All of the images seem to be CentOS7 based, I think they might've been deprecated, which would be: https://docs.okd.io/4.10/openshift_images/configuring-samples-operator.html#images-samples-operator-deprecated-image-stream_configuring-samples-operator
```
oc tag -d <image_stream_name:tag>
```

However, you said you did that but they were re-created?
If this persists, we should open a BZ. There should be a `samples-operator` component there.

**Comment by kai-uwe-rommel** [comment]
No I did not do it this way. Instead I "Removed" the operator, waited a while and then set it "Managed" again. When "Removed" it deleted all of its ImageStream and Image objects. When "Managed" again, it recreated all - but then the alert came back.

**Comment by kai-uwe-rommel** [comment]
A fresh installed cluster (with 4.10 2022-05-07) does not have this problem.

**Comment by ceagan** [comment]
Here is my understanding of the situation and the solution I used.

The samples operator does not remove tags for sample images because they may be in use by resources in the cluster. However, if the image pulls are failing and it has been determined that this is because the images are no longer available upstream, then the image tags that are failing may be deleted to address the problem. Use the following command to delete them all at once.

```bash
oc -n openshift get imagetag | grep "ImportFailed" | awk -e '{ print $1 }' | xargs oc -n openshift tag -d
```

**Comment by kai-uwe-rommel** [comment]
Thanks a lot!

**Comment by JaimeMagiera** [comment]
@kai-uwe-rommel Can we close this now?

**Comment by kai-uwe-rommel** [comment]
Yes, I think so.
