### ISSUE TITLE
Update OKD from 4.9.0-0.okd-2022-02-12-140851 to 4.10.0-0.okd-2022-05-28-062148 fails on MCP processing

### ISSUE THREAD

**Issue by dbutti** [okd-project/okd#1256]
Good morning; this is a 3-master + 3-worker cluster which has worked pretty well for over one year. First installation was with 4.7 on Fedora CoreOS 34, then it was upgraded to different 4.8 versions and then to 4.9. The 6 VMs are running under oVirt.

Now I'm trying to upgrade to 4.10.0-0.okd-2022-05-28-062148, and all the cluster operators have been upgraded succesfully.

Then after reboot of the first master and the first worker node, the machine-operator says **"Cluster not available for [{operator 4.9.0-0.okd-2022-02-12-140851}]"**. The rebooted nodes never get through the update; the logs from the machine-config-daemon on the failing **master** node ends with the following message, repeated every 2-3 minutes:

```E0608 19:51:44.910905    3351 writer.go:135] Marking Degraded due to: failed to update OS to quay.io/openshift/okd-content@sha256:7561f13827c24d5b5433f4ba8793a58b3cd7ea4684ba627a8f30d96396f81a3b : error running rpm-ostree
rebase --experimental /run/mco-machine-os-content/os-content-204306217/srv/repo:f7bc51778b14034645048550bf9aaff0aa22f06411d9307f4cf71b143a7e35b8 --custom-origin-url pivot://quay.io/openshift/okd-content@sha256:7561f13827c24d5b5433f4ba8793a58b3cd7ea4684ba627a8f30d96396f81a3b --custom-origin-description Managed by machine-config-operator: error: Could not depsolve transaction; 1 problem detected:
 Problem: package python3-3.10.0-1.fc35.i686 requires libc.so.6(GLIBC_2.34), but none of the providers can be installed
  - package python3-pyyaml-5.4.1-4.fc35.x86_64 requires python(abi) = 3.10, but none of the providers can be installed
  - package python3-3.10.0-1.fc35.x86_64 requires python3-libs(x86-64) = 3.10.0-1.fc35, but none of the providers can be installed
  - glibc-2.34-7.fc35.i686 has inferior architecture
  - package python3-ceph-common-2:16.2.6-2.fc35.x86_64 requires python3.10dist(pyyaml), but none of the providers can be installed
  - package python3-ceph-common-2:16.2.6-2.fc35.x86_64 requires python3-pyyaml, but none of the providers can be installed
  - cannot install both python3-libs-3.10.0-1.fc35.x86_64 and python3-libs-3.10.4-1.fc35.x86_64
  - cannot install both glibc-2.34-7.fc35.x86_64 and glibc-2.34-34.fc35.x86_64
  - package ceph-common-2:16.2.6-2.fc35.x86_64 requires python3-ceph-common = 2:16.2.6-2.fc35, but none of the providers can be installed
  - conflicting requests 
```

The rebooted worker node, on the other hand, boots successfully but never gets Ready again.

So I paused the update and also both MCP to be sure, and then on the two nodes I ran **rpm-ostree rollback**

In this way I could make both nodes Schedulable again, and now I'm left with this situation:

```[root@okd4-services ~]# oc get no
NAME                                 STATUS                     ROLES    AGE    VERSION
okd4-compute-1.lab.okd.local         Ready                      worker   280d   v1.22.3+fdba464
okd4-compute-2.lab.okd.local         Ready                      worker   281d   v1.22.3+fdba464
okd4-compute-3.lab.okd.local         Ready                      worker   251d   v1.22.3+fdba464
okd4-control-plane-1.lab.okd.local   Ready                      master   341d   v1.21.2+9e8f924-1555
okd4-control-plane-2.lab.okd.local   Ready                      master   341d   v1.22.3+fdba464
okd4-control-plane-3.lab.okd.local   Ready                      master   341d   v1.22.3+fdba464
```

So the cluster operators are at 4.10, the nodes are still on v1.22.3, and the one master node where I rolled back rpm is on v1.21.2

Could anyone shed some light please, how I can solve the issue and complete the upgrade to 4.10?

Thanks in advance to everybody,

**Comment by vrutkovs** [comment]
Please attach (or upload to the public file sharing service) [must-gather](https://docs.okd.io/latest/support/gathering-cluster-data.html#support_gathering_data_gathering-cluster-data) archive

**Comment by dbutti** [comment]
Thank-you, you can download the must-gather archive from this link: [Must-Gather.tgz](https://nc.neaweb.ch/s/fBgaPMReEKJXpen)

At some point in the past, while still on 4.7, I had installed the package ceph-common on the master nodes. I have now removed it by running the `rpm-ostree reset -l` command, but that doesn't seem to fix the issue. I was able anyway to bring the "broken" master node to a slightly better condition, by manually invoking the pivot operation on the machine-operator; `oc get nodes` now shows:

```
NAME                                 STATUS   ROLES    AGE    VERSION
okd4-compute-1.lab.okd.local         Ready    worker   280d   v1.22.3+fdba464
okd4-compute-2.lab.okd.local         Ready    worker   281d   v1.22.3+fdba464
okd4-compute-3.lab.okd.local         Ready    worker   251d   v1.22.3+fdba464
okd4-control-plane-1.lab.okd.local   Ready    master   341d   v1.22.3+fdba464
okd4-control-plane-2.lab.okd.local   Ready    master   341d   v1.22.3+fdba464
okd4-control-plane-3.lab.okd.local   Ready    master   341d   v1.22.3+fdba464
```

In the web console, the "Cluster settings" window shows:

```
This cluster should not be updated to the next minor version.
Multiple cluster operators should not be upgraded between minor versions:

Cluster operator kube-apiserver should not be upgraded between minor versions: KubeletMinorVersion_KubeletMinorVersionUnsupportedNextUpgrade: KubeletMinorVersionUpgradeable: Kubelet minor versions on 6 nodes will not be supported in the next OpenShift minor version upgrade.
Cluster operator machine-config should not be upgraded between minor versions: DegradedPool: One or more machine config pools are degraded, please see oc get mcp for further details and resolve before upgrading
```

Thank-you,

**Comment by vrutkovs** [comment]
>The presence of some "layered" packages I had added through rpm-ostree to some nodes caused the MCO update operation to fail, and left the nodes in NotReady state

Yes, you can add layered packages via MachineConfig's `spec.extensions` (provided you have enabled necessary repos for that).

Can't think of a reason to have `ceph-common` on the nodes - neither Ceph CSI nor Rook requires it.

>So I'm now looking into adding a small MachineConfig fragment which will shut down the service definitively.

We do expect `systemd-resolved` to run, but with DNS stub disabled

**Comment by fortinj66** [comment]
The issues with systemd-resolved are fixed in 4.10.  
I would suggest rather than disable systemd-resolved you could change ` /etc/nsswitch.conf ` so that both dns and resolved get called...
change
`hosts:      files myhostname resolve [!UNAVAIL=return] dns`
to
`hosts:      files myhostname resolve dns`

After update you can change it back

**Comment by fortinj66** [comment]
> I wouldn't say that all issues with resolved are fixed in 4.10, though, because now I'm running at 4.10.0-0.okd-2022-05-28-062148 on all nodes, and the issue is well present on every reboot. Am I missing anything?

I'd be curious to see what issues you have after upgrading to the latest 4.10 release.  We've spend a good amount of time fixing DNS issues

**Comment by vrutkovs** [comment]
I think its best to use `rpm-ostree rollback` to revert manual changes instead of `reset`. Also, don't forget to disable Fedora repos before upgrade - OKD doesn't need those and new updates may bring issues like this over time

**Comment by dbutti** [comment]
Thank-you @vrutkovs for your comments about disabling the Fedora repos, will take care of that.

On the other hand, I'm not sure I fully understand the remark by @fortinj66: it seems clear to me that something in 4.10 is not working "out of the box", otherwise I wouldn't need the manual change to the /etc/nsswitch.conf file. And without that, the software update would never succeed. Or am I mistaken? Doesn't this mean that the resolved daemon _under default settings_ causes unforeseen issues?

**Comment by JaimeMagiera** [comment]
@dbutti After making the changes to allow upgrade to >= 4.10.0-0.okd-2022-06-10-131327 the issue should have been resolved permanently. Do you need to keep this issue open?
