### ISSUE TITLE
Update from 4.10.0-0.okd-2022-06-10-131327 to 4.10.0-0.okd-2022-06-24-212905 fails at reboot

### ISSUE THREAD

**Issue by devinmatte** [okd-project/okd#1270]
**Describe the bug**

When running an update from `4.10.0-0.okd-2022-06-10-131327` to `4.10.0-0.okd-2022-06-24-212905`, the cluster fails in the last stage (reboot and mcp).

```
ClusterVersion: Updating to "4.10.0-0.okd-2022-06-24-212905" from "4.10.0-0.okd-2022-06-10-131327" for 2 hours: Working towards 4.10.0-0.okd-2022-06-24-212905: 656 of 778 done (84% complete)
ClusterOperators:
	clusteroperator/machine-config is degraded because Unable to apply 4.10.0-0.okd-2022-06-24-212905: timed out waiting for the condition during syncRequiredMachineConfigPools: error pool master is not ready, retrying. Status: (pool degraded: true total: 3, ready 0, updated: 0, unavailable: 0)
```

The masters and workers went to reboot with the newer version of coreos, and they simply hang and never boot. Restarting and booting to the `ostree: 1` image from before the update still works fine.

The cluster is now in a state where it's always updating and never finishing.

<img width="819" alt="Screen Shot 2022-07-01 at 3 22 55 PM" src="https://user-images.githubusercontent.com/9310513/176957402-4389b5b2-add1-478e-8bfc-ee66cfb9726b.png">

Ideally I'd like to boot into the newer version successfully, cancel the update and revert or roll forward to a newer version that will succeed. We have etcd backups if we need, but that is really something we'd like to avoid at all costs.

```
[root@okd4-services ~]# oc adm upgrade --clear
info: No update in progress
[root@okd4-services ~]# oc adm upgrade
info: An upgrade is in progress. Working towards 4.10.0-0.okd-2022-06-24-212905: 656 of 778 done (84% complete)

Upgradeable=False

  Reason: DegradedPool
  Message: Cluster operator machine-config should not be upgraded between minor versions: One or more machine config pools are degraded, please see `oc get mcp` for further details and resolve before upgrading

Upstream: https://origin-release.ci.openshift.org/graph
Channel: stable-4
No updates available. You may force an upgrade to a specific release image, but doing so may not be supported and may result in downtime or data loss.
```

**Version**

`4.10.0-0.okd-2022-06-10-131327` to `4.10.0-0.okd-2022-06-24-212905`

We're running on bare metal.

**How reproducible**

Hard to reproduce without trying to upgrade a second cluster, but nodes refuse to boot with the new coreos image from the upgrade.

**Log bundle**

[Must Gather Zip](https://csh.rit.edu/~matted/must-gather.zip)

**Comment by vrutkovs** [comment]
>The masters and workers went to reboot with the newer version of coreos, and they simply hang and never boot

I see ctrl02 has new version as a staged deployment:
```
2022-07-01T19:08:09.446839463Z I0701 19:08:09.446804    3984 update.go:1956] Starting to manage node: okd4-ctl02-nrh
2022-07-01T19:08:09.449798909Z I0701 19:08:09.449761    3984 rpm-ostree.go:325] Running captured: rpm-ostree status
2022-07-01T19:08:09.815310812Z I0701 19:08:09.815265    3984 daemon.go:957] State: idle
2022-07-01T19:08:09.815310812Z Deployments:
2022-07-01T19:08:09.815310812Z   pivot://quay.io/openshift/okd-content@sha256:d10fe7ed3ac8aa66ccd0bb7deee549dba5edd05a1dae57e52830d2e69ea3a7c5
2022-07-01T19:08:09.815310812Z               CustomOrigin: Managed by machine-config-operator
2022-07-01T19:08:09.815310812Z                    Version: 410.35.202206241934-0 (2022-06-24T19:38:53Z)
2022-07-01T19:08:09.815310812Z                       Diff: 47 upgraded, 1 removed, 1 added
2022-07-01T19:08:09.815310812Z 
2022-07-01T19:08:09.815310812Z * pivot://quay.io/openshift/okd-content@sha256:cd4fe63cf7c5c787dfe4f0080630459c20a7b87ce8754415a2277d934563ec66
2022-07-01T19:08:09.815310812Z               CustomOrigin: Managed by machine-config-operator
2022-07-01T19:08:09.815310812Z                    Version: 410.35.202206101257-0 (2022-06-10T13:01:20Z)
```
Does it mean it attempted to boot into it, but failed and reverted back to a previous deployment?

**Comment by devinmatte** [comment]
Yep. It attempted to boot to the newer deployment, and after 15-20 minutes of no progress booting I intervened, rebooted the box a few times, before finally booting it back to it's previous deployment in the boot menu.

When it tries to boot to the newer deployment it hangs and simply shows a cursor with no progress being made and no logs being shown.

**Comment by SriRamanujam** [comment]
If it's failing during early boot (possible from what you've described, though I can't find anything in the must-gather to say for sure) you may be able to see the kernel logs by attaching a virtual serial console and seeing if that gets log output. There may also be logs from your hypervisor that could point at something.

**Comment by devinmatte** [comment]
The nodes that failed to boot are bare metal (not VMs). I have access to a ILO interface or I can have someone go in person come Tuesday. Is there a way to boot into a verbose logging form?

**Comment by devinmatte** [comment]
Okay so weirdly the solution seems to have been shutting the servers down, and booting cold. I don't know why that worked, but I was able to replicate the same issue with reboots even after. So we'll have to remain super careful with our boxes to ensure they are shut down and then booted cold if they need a reboot for this version.

**Comment by dnlwgnd** [comment]
my cluster behaved similar on both 2022-06-10 and 2022-06-24 updates. 
Some workers seemed to not boot up correctly. I foud that they do boot, but take a long time doing so until I was able to ssh into them. In their vconsole I get a lot audit messages relating kubelet, and sure enough kubelet was not able to start for permission-denied reason on its executable. 
I worked around it by temporarily setting SELinux to permissive, this allowed kubelet to start automatically and also the update process proceeded on its own with the next node until eventually the update succeeded. 
Only some of the worker nodes were affected.

**Comment by msteenhu** [comment]
Thx @dnlwgnd ! That sounds exactly like my problem: kubelet starts with a 'file not found' like error which indeed not make sense unless SELinux is in play. Clearly some bug in latest versions then.

**Comment by vrutkovs** [comment]
We didn't notice any SELinux errors in CI neither on new installs or upgrades.

PLease check the journal and provide any details on these SELinux errors?

**Comment by msteenhu** [comment]
Confirmed, run this and my upgrade continues:
`setenforce 0 &&
systemctl restart kubelet`

**Comment by msteenhu** [comment]
@vrutkovs This is all journalctl logging around the first (failing) start of kubelet after upgrade. Should I supply a zip with all the journal logging or something else to help? I can even help by doing an upgrade again (after reinstalling a host with an older 4.10 version or something like that).

> We didn't notice any SELinux errors in CI neither on new installs or upgrades.
> 
> Please check the journal and provide any details on these SELinux errors

```
Jul 06 18:08:53 mec-okd4-worker-03 systemd[1]: Starting Kubernetes Kubelet...
Jul 06 18:08:53 mec-okd4-worker-03 kernel: SELinux:  Context system_u:object_r:kubelet_exec_t:s0 is not valid (left unmapped).
Jul 06 18:08:53 mec-okd4-worker-03 audit[4040]: AVC avc:  denied  { execute } for  pid=4040 comm="(yperkube)" name="hyperkube" dev="sda4" ino=342043427 scontext=system_u:system_r:init_t:s0 tcontext=syste>
Jul 06 18:08:53 mec-okd4-worker-03 systemd[4040]: kubelet.service: Failed to locate executable /usr/bin/hyperkube: Permission denied
Jul 06 18:08:53 mec-okd4-worker-03 systemd[4040]: kubelet.service: Failed at step EXEC spawning /usr/bin/hyperkube: Permission denied
Jul 06 18:08:53 mec-okd4-worker-03 systemd[1]: kubelet.service: Main process exited, code=exited, status=203/EXEC
```

**Comment by msteenhu** [comment]
So an SELinux module was not loaded when kubelet tries to start?

Now I find these openshift related modules on the host:
```
sudo semodule -l | grep openshift
openshift
openshift-origin
```

**Comment by msteenhu** [comment]
Or bug in these changes?

```
selinux-policy 35.17-1.fc35 -> 35.18-1.fc35
selinux-policy-targeted 35.17-1.fc35 -> 35.18-1.fc35
```

**Comment by vrutkovs** [comment]
>Jul 06 18:08:53 mec-okd4-worker-03 kernel: SELinux:  Context system_u:object_r:kubelet_exec_t:s0 is not valid (left unmapped).
Looks like SELinux DB is messed up, try https://bugzilla.redhat.com/show_bug.cgi?id=1843873#c1?
