### ISSUE TITLE
Random connection timeouts with OKD 4.10 and Nginx Ingress Controller ?

### ISSUE THREAD

**Issue by aelbarkani** [okd-project/okd#1279]
**Describe the bug**

Since we upgraded to OKD 4.10 from 4.8 we are seeing random timeouts on Nginx Ingress Controller requests. It doesn't seem related to CNI, we are using both OpenShiftSDN and OVNKubernetes on two differents cloud providers.
Openshift Ingress Controller seems to be working better (~5 timeouts per day only vs ~30% of the requests on Nginx Ingress Controller), although we still see some timeout from time to time.
Is anyone facing the same issue ?

**Version**

4.10.0-0.okd-2022-06-10-131327 IPI AWS 
4.10.0-0.okd-2022-04-23-131357 IPI Azure
**How reproducible**

Reproducible on all OKD 4.10 clusters, it happens for 20-40% of the requests. 
**Log bundle**

I'll upload it soon.

**Comment by vrutkovs** [comment]
/lifecycle stale

Is this reproducible in 4.12?
