### ISSUE TITLE
OKD support for Azure provider

### ISSUE THREAD

**Issue by DanyC97** [okd-project/okd#13]
We would like to keep this master issue to link new issues which are related to Azure deployment so we can keep track as well as letting community know if a specific provider deployment is supported or has known issues etc

**Comment by LorbusChris** [comment]
Azure images are now being built by the FCOS pipeline. They're not uploaded to Azure automatically, yet, though and users would still have to do that manually at the moment.

refs https://github.com/coreos/fedora-coreos-tracker/issues/148#issuecomment-564622757

**Comment by jomeier** [comment]
Currently I'm uploading the decompressed VHD file to my Storage Account in Azure with the tool "Microsoft Azure Storage Explorer".

**Comment by jomeier** [comment]
It seems as if the bootstrap VM requires a reboot before it gets the DNS servers provided in the Azure VNET and is able to pull the initial okd image from quay.io.

**Comment by jomeier** [comment]
If Azure support comes back to the openshift-installer (maybe in preview 2 ?) I'm eager to test Azure disk and Azure file support.

**Comment by vrutkovs** [comment]
Official FCOS on Azure is still not progressing. We have a workaround for that, so we won't be blocking GA on this

**Comment by edisonpaul4bp** [comment]
Any news regarding this? Many problems trying to install this on Azure, at least with the last Nightly build I was able to install everything BUT only the Bootstrap node is online, master nodes are always offline.

Always getting ERROR Attempted to gather ClusterOperator status after installation failure: listing ClusterOperator objects timeout

**Comment by jryberg** [comment]
> If Azure support comes back to the openshift-installer (maybe in preview 2 ?) I'm eager to test Azure disk and Azure file support.

It's supported in OpenShift openshift-installer, running it right now and my infrastructure is built using OpenShift instead of OKD

**Comment by 1Kasla** [comment]
Hello, I have encountered this issue while trying to install OKD on version v4.12 and above... on Azure IPI. Could you tell me if this error has already been fixed?

FATAL failed to fetch Metadata: failed to fetch dependency of "Metadata": failed to fetch dependency                                                                                                           of "Bootstrap Ignition Config": failed to fetch dependency of "Worker Machines": failed to generate                                                                                                           asset "Release": stable/x86_64: No azure build found

**Comment by bishoy-payco** [comment]
I'm facing the same error with OKD 4.15 installation.

I uploaded fcos image to my storage account as per the documentation (https://docs.fedoraproject.org/en-US/fedora-coreos/provisioning-azure/). But I can't find a way to tell the installer to use this image, and the only options I found to tell the installer to use a specific image is relying on providing the publisher, offer, sku, and version information, in which these information is only available to the marketplace images.

And generating the ignition files fails as well, giving the same error:
`FATAL failed to fetch Bootstrap Ignition Config: failed to fetch dependency of "Bootstrap Ignition Config": failed to fetch dependency of "CVO Ignore": failed to fetch dependency of "Openshift Manifests": failed to generate asset "Image": stable/x86_64: No azure build found `

**Comment by JaimeMagiera** [comment]
Hi,

We are not working on FCOS builds of OKD any more. Please see these documents...

https://okd.io/blog/2024/06/01/okd-future-statement
https://okd.io/blog/2024/07/30/okd-pre-release-testing

Please test with the OKD SCOS nightlies and file a new issue as needed.

Many thanks,

Jaime
