### ISSUE TITLE
Link to GPG signing keys not working

### ISSUE THREAD

**Issue by mkesper** [okd-project/okd#1319]
**Describe the bug**
[the Github okd site](https://github.com/okd-project/okd) contains a link to [a list of public keys](https://okd.io/keys.html) used for signing.
This link resolves to a search page / 404 - Not found.

**Comment by vrutkovs** [comment]
Brian, could you take a look? https://github.com/openshift-cs/okd.io/commit/328b93615002d4f55e920d53c4652bcb0d086eb6 is the commit we added these

**Comment by binnes** [comment]
This is covered in the documentation : https://www.okd.io/installation/#getting-started.  Probably need to remove this from the README.md in the old repo.  Point the users to the okd.io site
