### ISSUE TITLE
[OKD 4.10.0 on KVM UPI] bootstrap never complete

### ISSUE THREAD

**Issue by yurix1975** [okd-project/okd#1329]
### Discussed in https://github.com/okd-project/okd/discussions/1328

<div type='discussions-op-text'>

<sup>Originally posted by **yurix1975** September  1, 2022</sup>
good evening,
i spent a lot of time in last days to setup an okd cluster on UPI powered by qemu/proxmox, i've followed all the indications i found
but without success.
at the end of all my tries, the okd is unable to start ingress-router pod cause it doesn' t know about route.openshift.io resource kind.
i convinced my sefl the problem is on the bootstrap node, but which?
in the journal of the bootstrap i found a lot of failure during creation of object in the boostrap kube.
for example: 
Sep 01 11:33:46 okd4-bootstrap bootkube.sh[4399]: Created "0000_00_cluster-version-operator_00_namespace.yaml" namespaces.v1./openshift-cluster-version -n
Sep 01 11:33:46 okd4-bootstrap cluster-bootstrap[4481]: Failed to create "0000_00_cluster-version-operator_01_adminack_configmap.yaml" configmaps.v1./admin-acks -n openshift-config: namespaces "openshift-config" not found

my setup use fedora-coreos-35.20220327.3.0-qemu.x86_64.qcow2 for all the vm beloging to the cluster, a debian 11 vm as haproxy,dns,dhcp and router.

this is my install-config.yml:

apiVersion: v1
baseDomain: okd.local
metadata:
  name: lab

compute:
- hyperthreading: Enabled
  name: worker
  replicas: 0

controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3

networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14 
    hostPrefix: 23 
  networkType: OVNKubernetes
  serviceNetwork: 
  - 172.30.0.0/16

platform:
  none: {}

fips: false

pullSecret: '{"auths":{"fake":{"auth":"aWQ6cGFzcwo="}}}' 
sshKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDXMXpke3A

in attach the bootstrap node journal
[journalctl.out.gz](https://github.com/okd-project/okd/files/9469858/journalctl.out.gz)

any help ?

kind regards</div>

**Comment by vrutkovs** [comment]
Please attach [log bundle](https://docs.okd.io/latest/installing/installing-troubleshooting.html#installation-bootstrap-gather_installing-troubleshooting)

**Comment by yurix1975** [comment]
here you are, thanks
[log-bundle-20220902063656.tar.gz](https://github.com/okd-project/okd/files/9475515/log-bundle-20220902063656.tar.gz)

**Comment by vrutkovs** [comment]
Master ignition was requested 3 times:
```
I0902 06:17:39.129879       1 api.go:110] Pool master requested by address:"192.168.13.254:52474" User-Agent:"Ignition/2.13.0" Accept-Header: "application/vnd.coreos.ignition+json;version=3.3.0, */*;q=0.1"
I0902 06:17:39.130255       1 bootstrap_server.go:66] reading file "/etc/mcs/bootstrap/machine-pools/master.yaml"
I0902 06:17:39.131628       1 bootstrap_server.go:86] reading file "/etc/mcs/bootstrap/machine-configs/rendered-master-17ad77a459d6328d71539de923e301f1.yaml"
I0902 06:17:45.751791       1 api.go:110] Pool master requested by address:"192.168.13.254:54636" User-Agent:"Ignition/2.13.0" Accept-Header: "application/vnd.coreos.ignition+json;version=3.3.0, */*;q=0.1"
I0902 06:17:45.751833       1 bootstrap_server.go:66] reading file "/etc/mcs/bootstrap/machine-pools/master.yaml"
I0902 06:17:45.752479       1 bootstrap_server.go:86] reading file "/etc/mcs/bootstrap/machine-configs/rendered-master-17ad77a459d6328d71539de923e301f1.yaml"
I0902 06:17:49.464659       1 api.go:110] Pool master requested by address:"192.168.13.254:54658" User-Agent:"Ignition/2.13.0" Accept-Header: "application/vnd.coreos.ignition+json;version=3.3.0, */*;q=0.1"
I0902 06:17:49.464695       1 bootstrap_server.go:66] reading file "/etc/mcs/bootstrap/machine-pools/master.yaml"
I0902 06:17:49.465224       1 bootstrap_server.go:86] reading file "/etc/mcs/bootstrap/machine-configs/rendered-master-17ad77a459d6328d71539de923e301f1.yaml"
```
but no information fetched for `192.168.13.64`. is this machine running? If yes, can you ssh on it? If yes, is `kubelet.service` running there?

**Comment by yurix1975** [comment]
for sure:

***@***.*** deploy]$ systemctl status kubelet
● kubelet.service - Kubernetes Kubelet
     Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor
preset: disabled)
    Drop-In: /etc/systemd/system/kubelet.service.d
             └─10-mco-default-env.conf, 10-mco-default-madv.conf,
20-logging.conf, 20-nodenet.conf
     Active: active (running) since Fri 2022-09-02 06:21:55 UTC; 59min ago
    Process: 1884 ExecStartPre=/bin/mkdir --parents
/etc/kubernetes/manifests (code=exited, status=0/SUCCESS)
    Process: 1885 ExecStartPre=/bin/rm -f
/var/lib/kubelet/cpu_manager_state (code=exited, status=0/SUCCESS)
    Process: 1886 ExecStartPre=/bin/rm -f
/var/lib/kubelet/memory_manager_state (code=exited, status=0/SUCCESS)
   Main PID: 1887 (kubelet)
      Tasks: 18 (limit: 9418)
     Memory: 85.0M
        CPU: 1min 49.853s
     CGroup: /system.slice/kubelet.service
             └─ 1887 kubelet --config=/etc/kubernetes/kubelet.conf
--bootstrap-kubeconfig=/etc/kubernetes/kubeconfig
--kubeconfig=/var/lib/kubelet/kubeconfig --container-runtime=remote
--contain>

Sep 02 07:21:13 okd4-control-plane-1 hyperkube[1887]: set -o allexport
Sep 02 07:21:13 okd4-control-plane-1 hyperkube[1887]: if [[ -f
/etc/kubernetes/apiserver-url.env ]]; then
Sep 02 07:21:13 okd4-control-plane-1 hyperkube[1887]:   source
/etc/kubernetes/apiserver-url.env
Sep 02 07:21:13 okd4-control-plane-1 hyperkube[1887]: else
Sep 02 07:21:13 okd4-control-plane-1 hyperkube[1887]:
URL_ONLY_KUBECONFIG=/etc/kubernetes/kubeconfig
Sep 02 07:21:13 okd4-control-plane-1 hyperkube[1887]: fi
Sep 02 07:21:13 okd4-control-plane-1 hyperkube[1887]: exec
/usr/bin/cluster-network-operator start --listen=0.0.0.0:9104
Sep 02 07:21:13 okd4-control-plane-1 hyperkube[1887]:
],Args:[],WorkingDir:,Ports:[]ContainerPort{ContainerPort{Name:cno,HostPort:9104,ContainerPort:9104,Protocol:TCP,HostIP:,},},Env:[]EnvVar{En>
Sep 02 07:21:13 okd4-control-plane-1 hyperkube[1887]: E0902 07:21:13.408738
   1887 pod_workers.go:951] "Error syncing pod, skipping" err="failed to
\"StartContainer\" for \"network-operator\" w>
Sep 02 07:21:13 okd4-control-plane-1 hyperkube[1887]: E0902 07:21:13.460001
   1887 token_manager.go:121] "Couldn't update token" err="Post \"
https://api-int.lab.okd.local:6443/api/v1/namespaces>
***@***.*** deploy]$



Il giorno ven 2 set 2022 alle ore 09:03 Vadim Rutkovsky <
***@***.***> ha scritto:

**Comment by yurix1975** [comment]
the master nodes are going out of disk space, let me try with more disk
space.


Il giorno ven 2 set 2022 alle ore 09:03 Vadim Rutkovsky <
***@***.***> ha scritto:

**Comment by yurix1975** [comment]
my fault!
at the end, i completed installation successfully
