### ISSUE TITLE
Documentation - missing steps for cluster creation following AWS STS creation

### ISSUE THREAD

**Issue by sl-commits** [okd-project/okd#1339]
This is the document that I was following originally to install STS & OKD:

[Using manual mode with AWS Secure Token Service - Managing cloud provider credentials | Authentication and authorization | OKD 4](https://docs.okd.io/latest/authentication/managing_cloud_provider_credentials/cco-mode-sts.html)

After the section “Creating AWS resources with the Cloud Credential Operator utility”, the document moves to the “Running the Installer” section.

I had to perform the following two steps which are not present in the “Running the Installer” section at the moment.  Without either of these 2 steps I was unable to build a cluster successfully.

1.	Copy the credentialsrequests yamls created earlier into the installation ‘manifests’ folder so that they get created during installation.  I run this after step 4 which is ‘cp /<path_to_ccoctl_output_dir>/manifests/* ./manifests/’.

cp <path_to_directory_with_list_of_credentials_requests>/credrequests /* ./manifests/

2.	Create the Authentication YAML to associate the cluster with the OIDC provider previously created. This step was found in the document for OCP 4.7 [Using manual mode with STS - Managing cloud provider credentials | Authentication and authorization | OpenShift Container Platform 4.7](https://docs.openshift.com/container-platform/4.7/authentication/managing_cloud_provider_credentials/cco-mode-sts.html) – Creating AWS resources manually – step 11e. If this step is missed then the cluster goes to https://kubernetes.default.svc/ looking for OIDC provider.

OPENID_BUCKET_URL = https://okd-pofconcept-oidc.s3.eu-west-2.amazonaws.com/             # as an example

cat << EOF > manifests/cluster-authentication-02-config.yaml
apiVersion: config.openshift.io/v1
kind: Authentication
metadata:
  name: cluster
spec:
  serviceAccountIssuer: $OPENID_BUCKET_URL
EOF

**Comment by vrutkovs** [comment]
Please re-file this for https://github.com/openshift/openshift-docs/
