### ISSUE TITLE
[vsphere] nodes names are not derived from guestinfo.hostname

### ISSUE THREAD

**Issue by rvanderp3** [okd-project/okd#1343]
**Describe the bug**
When installing a recent 4.12 OKD nightly via IPI, installation fails due to compute nodes not joining the cluster.  From a local install, I was able to see the following as it relates to the vsphere-hostname unit:

~~~
$ journalctl -u vsphere-hostname.service
Sep 16 15:12:42 ocp-ci-seg-10-node53 systemd[1]: Started vsphere-hostname.service - vSphere hostname.
Sep 16 15:12:42 ocp-ci-seg-10-node53 vsphere-hostname.sh[1488]: /usr/local/bin/vsphere-hostname.sh: line 7: /bin/vmtoolsd: No such file or directory
Sep 16 15:12:42 ocp-ci-seg-10-node53 systemd[1]: vsphere-hostname.service: Deactivated successfully.
-- Boot fa0bbabcd4dc4df5ad24447b3aad027e --
Sep 16 15:14:51 localhost systemd[1]: vsphere-hostname.service - vSphere hostname was skipped because of a failed condition check (ConditionPathExists=!/etc/hostname).
~~~

When looking at the serial console for another node, it appears that the node name is set by network manager which would prevent the vsphere-hostname service(as it is presently designed) to apply the hostname from guestinfo.hostname.

![image](https://user-images.githubusercontent.com/49568690/190680307-f221235f-deb5-4720-8c44-0d7d2cee8331.png)

**Version**
IPI, vSphere, 4.12.0-0.okd-2022-09-16-023731

**How reproducible**
Consistently

**Log bundle**
Failing CI job(also reproduced on local install) -- > https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/periodic-ci-openshift-release-master-okd-4.12-e2e-vsphere/1570767685900308480/artifacts/e2e-vsphere/

**Comment by vrutkovs** [comment]
That's odd,  `open-vm-tools` was supposed to provide it

**Comment by rvanderp3** [comment]
If I'm understanding things correctly, it's not there until sometime after ignition and the hostname is being set prior to vmtoolsd being present and the unit running.  If there is already a hostname set, the unit won't overwrite it.

**Comment by vrutkovs** [comment]
Oh, so `vsphere-hostname` is expected to firstboot, set hostname so that NM would not attempt to do so.

Instead, we get `vsphere-hostname.service` and NM resolvies the hostname via PTR record, while we fetch machine-os-content and reboot. After reboot, `/bin/vmtoolsd` is there, but `vsphere-hostname` won't run as it assumes that hostname is already set.

Can we reconfigure the service to run it every time? Is it protecting against VM renames I guess?

**Comment by rvanderp3** [comment]
The idea here, if I recall, was to allow a user to explicitly override the hostname of a node if they needed to.  There appears to have been some behavior change where the hostname is set by NM prior to when the unit runs and vmtoolsd is available.  It appears this problem emerged around September 2nd:
Failed job(note node names, Sept 2): https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/periodic-ci-openshift-release-master-okd-4.12-e2e-vsphere/1565540360141148160/artifacts/e2e-vsphere/gather-extra/artifacts/nodes/
OK job(Aug 31): https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/periodic-ci-openshift-release-master-okd-4.12-e2e-vsphere/1564816579198193664/artifacts/e2e-vsphere/gather-extra/artifacts/nodes/

We aren't seeing this behavior in ocp in 4.12 nightlies.

**Comment by vrutkovs** [comment]
Right, seeing this in CI: node starts with valid hostname but no `/bin/vmtoolsd`, then NM resets it to `localhost` and on second boot `vsphere-hostname` is skipped as `/etc/hostname` already exists

**Comment by vrutkovs** [comment]
I see `e2e-vsphere` test passing in https://github.com/openshift/okd-machine-os/pull/438, so it must be indeed a bug fixed in 1.38.4

**Comment by rvanderp3** [comment]
ah, cool, thanks for checking that out @vrutkovs !

**Comment by vrutkovs** [comment]
vsphere test succeeded in https://amd64.origin.releases.ci.openshift.org/releasestream/4.12.0-0.okd/release/4.12.0-0.okd-2022-09-20-121638?from=4.12.0-0.okd-2022-09-20-045324, closing
