### ISSUE TITLE
Loadbalancer IP is (automatically) assigned on Node. This results in an IP conflict.

### ISSUE THREAD

**Issue by dbgrz** [okd-project/okd#1356]
**Describe the bug**

On OKD Clusters, the Loadbalancer IP is assigned on the Node, that the loadbalancer picks.
Example Configuration:
the loadbalancer listens on 10.96.224.16 for api and api-int
and on 10.96.224.17 for *.apps

the configuration is as follows:
10.96.224.16 -> 10.96.243.131,10.96.243.132,10.96.243.133

In vSphere I can see that one Master Node has the 10.96.224.16 assigned.
If I reboot this Master Node, the IP is assigned to a different Master Node instead
This generelly leads to an IP conflict, because the IP is now configured on the Loadbalancer and on an OKD Node.

Our Openshift Clusters do not have this issue. 

**Version**

Install Method: Both UPI
1st Cluster (lab): Release: 4.10.0-0.okd-2022-06-10-131327 (install time) - updated to 4.11.0-0.okd-2022-07-29-154152 (current) ; Fedora Core OS OKD - 35.20220327.3.0
2nd Cluster (dev): Release 4.8 4.8.0-0.okd-2021-11-14-052418 ; Fedora Core OS OKD - 34.20210626.3.1

**How reproducible**

I setup 2 Clusters and both have this issue. If I restart a Node that has a LB IP on it, the IP moves to a different Node.

**Log bundle**

The complete Log-Bundle has 145MB and can not be attached. If you want specific Logs from must-gather please tell me which ones are most important for you. I will attach a subset.
[must-gather.zip](https://github.com/okd-project/okd/files/9772353/must-gather.zip)

**Comment by vrutkovs** [comment]
>If I reboot this Master Node, the IP is assigned to a different Master Node instead

that's expected, isn't it?

> This generelly leads to an IP conflict, because the IP is now configured on the Loadbalancer and on an OKD Node.

Which "load balancer" do you mean here? 
In IPI external LB (i.e. haproxy) for api. endpoint should point to the API VIP, which would move to a valid node. Internal LB - keepalived - will use the same IP to handle api-int endpoint. Your UPI setup should replicate it to work

**Comment by dbgrz** [comment]
The loadbalancer is external. The loadbalancer detects if a Node is not reachable and does not send any requests to it, until the interface is up again.
We use a ssl_bridge configuration on the LB if that matters, that sends the requests to specific IP addresses (for api and api-int - these IPs are the Master Nodes. For *.apps for example. it are 2 specific nodes that run the router pods)

**Comment by bshephar** [comment]
So, just to clarify. You have configured an external Load Balancer, and you gave it the same IP address that Keepalived is using within OKD?

What are the IP's configured in your environment here:
```
❯ oc debug node/<your-master-node> -- grep -A1 address /host/etc/keepalived/keepalived.conf
Starting pod/okd-hm27m-master-2-debug ...
To use host binaries, run `chroot /host`
    virtual_ipaddress {
        10.0.0.5/32
--
    virtual_ipaddress {
        10.0.0.7/32
```

I'm using OpenStack and not VMware, but should be similar I assume.

**Comment by dbgrz** [comment]
root@jump ~]# oc debug node/master6101 -- grep -A1 address /host/etc/keepalived/keepalived.conf
Starting pod/bmcmaster6101rbgooeat-debug ...
To use host binaries, run `chroot /host`
    virtual_ipaddress {
        10.96.224.16/32
--
    virtual_ipaddress {
        10.96.224.17/32

Removing debug pod ...
[root@bmcdeploy6101 ~]#

**Comment by darren-oxford** [comment]
This sounds a bit confusing, you say that your cluster is installed as UPI, but have VIPs?

When installing via UPI (Infrastructure provider = none), you have an external load balancer, so the VIPs are not necessary. If you install using IPI then you have the VIPs as instead of an external load balancer, you have keepalived that maintains the VIPs.

You can add an external load balancer to your IPI cluster, as a post install exercise, but it still needs to point to the VIPs, you cannot reuse the VIP IP addresses for your external load balancer, that will need a unique IP address of its own.

Are you sure that the cluster is UPI, what does the Infrastructure Provider say in the console, None or bare metal?

**Comment by dbgrz** [comment]
Ironically, I can't find the info anymore on https://docs.okd.io/4.8/installing/installing_vsphere/installing-restricted-networks-vsphere.html#installation-vsphere-config-yaml_installing-restricted-networks-vsphere
but I thought it said to configure it that way.
The installation is a UPI in vSphere. Does it automatically assume the DNS names without providing the addresses for it? E.g. it searches for api.<clustername>.<domain-name> and apps.<clustername>.<domain-name> ?

**Comment by JaimeMagiera** [comment]
Yes. A vSphere UPI 4.8 installation formulates the api and apps URLs  using the base domain you provide in the config file. It assumes you have configured a DNS server upstream to provide those respective records, which should point to your upstream load balancers.  The nodes should have that DNS server in their network config either through DHCP or manual networking configuration using k args.

**Comment by bshephar** [comment]
It doesn't assume, those should be configured in your external DNS server prior to the install:
https://docs.okd.io/4.10/installing/installing_vsphere/installing-vsphere.html#installation-dns-user-infra_installing-vsphere

I guess the documentation you're referring to be this?
https://docs.okd.io/4.10/installing/installing_vsphere/installing-vsphere.html#installation-load-balancing-user-infra_installing-vsphere

There's a sample install-config.yaml here:
https://docs.okd.io/4.10/installing/installing_vsphere/installing-vsphere.html#installation-vsphere-config-yaml_installing-vsphere

**Comment by dbgrz** [comment]
Makes sense. Can I edit these settings after installation or should I reinstall my cluster?

**Comment by JaimeMagiera** [comment]
Re-install.
