### ISSUE TITLE
openshift-install create cluster Error ... bootstrap host 4.10.0-0.okd-2022-07-09-073606

### ISSUE THREAD

**Issue by apmlima** [okd-project/okd#1381]
$ openshift-install create cluster --dir t8
level=info msg=Credentials loaded from default AWS environment variables
level=info msg=Consuming Install Config from target directory
level=warning msg=Missing permissions to fetch Quotas and therefore will skip checking them: failed to load limits for servicequotas: failed to list serviceqquotas for ec2: AccessDeniedException: User: arn:aws:iam::101663181665:user/OpenShift-Deploy-User is not authorized to perform: servicequotas:ListServiceQuotas because no identity-based policy allows the servicequotas:ListServiceQuotas action, make sure you have `servicequotas:ListAWSDefaultServiceQuotas` permission available to the user.
level=info msg=Creating infrastructure resources...
level=info msg=Waiting up to 20m0s (until 1:23PM) for the Kubernetes API at https://api.t8.mdevlab.com:6443/...
level=error msg=Attempted to gather ClusterOperator status after installation failure: listing ClusterOperator objects: Get "https://api.t8.mdevlab.com:6443/apis/config.openshift.io/v1/clusteroperators": dial tcp 10.35.197.194:6443: connect: connection refused
level=info msg=Pulling debug logs from the bootstrap machine
level=info msg=Bootstrap gather logs captured here "/builds/infrastructure/cloud-automation/okd-4/t8/log-bundle-20221031132333.tar.gz"
level=error msg=Bootstrap failed to complete: Get "https://api.t8.mdevlab.com:6443/version": dial tcp 10.35.202.78:6443: connect: connection refused
level=error msg=Failed waiting for Kubernetes API. This error usually happens when there is a problem on the bootstrap host that prevents creating a temporary control plane.
level=fatal msg=Bootstrap failed to complete

Thanks for your help guys!

Pedro

Linux 4.10.0-0.okd-2022-07-09-073606 AWS

30%

https://drive.google.com/file/d/1MSyqllQe9k6xMwu3PQUSzX3o1UK9YHMx/view?usp=sharing
https://drive.google.com/file/d/10sOroQxPEMvq0LqzbX5j9ONUU3Sqp-1h/view?usp=sharing

**Comment by vrutkovs** [comment]
Is it reproducible on latest OKD 4.11 stable?

**Comment by apmlima** [comment]
@vrutkovs , this occurs from 4.8-4.10. Haven't tried with 4.11 yet but should occur too.
I've several okd clusters in this AWS account, could be a limits/quota issue?
I sent you all the logs, can you help me have a clue here?

**Comment by vrutkovs** [comment]
It looks similar to #1260, so it may have been resolved in recent installer

**Comment by apmlima** [comment]
@vrutkovs , Thanks for your brilliant help and I am going to try latest 4.11 stable still today.
