### ISSUE TITLE
[Doc] Broken links or missing sections in the CI/CD section (Pipelines, GitOps, Jenkins)

### ISSUE THREAD

**Issue by titou10titou10** [okd-project/okd#1388]
There are broken links in the CI/CD section of the latest OKD documentation: https://docs.okd.io/latest/cicd/index.html

Namely:

- Understanding OpenShift Pipelines: https://docs.okd.io/latest/cicd/pipelines/understanding-openshift-pipelines.html#understanding-openshift-pipelines
- Understanding OpenShift GitOps: https://docs.okd.io/latest/cicd/gitops/understanding-openshift-gitops.html#understanding-openshift-gitops

Either the section are missing or the page should be rewritten without those links

Compared to the OCP doc, those 3 sections are missing:
- CI/CD > Pipelines
- CI/CD > GitOps
- CI/CD > Jenkins

**Comment by JaimeMagiera** [comment]
Thank for providing this. The OpenShift Pipelines operator is not available within OKD. The upstream Tekton is. We'll have to massage the text to reflect that. I'll bring this up at the next OKD Community Development Meeting.

**Comment by titou10titou10** [comment]
> The OpenShift Pipelines operator is not available within OKD

oh? I'm currently actively using OpenShift Pipelines... 

    Operators > OperatorHub > Red Hat OpenShift Pipelines (v1.8.0, channel="pipeline-1.8"..)

It works like a charm...

    oc version
    Client Version: 4.11.0-0.okd-2022-10-28-153352
    Kustomize Version: v4.5.4
    Server Version: 4.11.0-0.okd-2022-10-28-153352
    Kubernetes Version: v1.24.0-2566+5157800f2a3bc3-dirty

**Comment by vrutkovs** [comment]
>  oh? I'm currently actively using OpenShift Pipelines in OKD...

Its not available in default "fake pullsecret" configuration.
/assign @mburke5678

**Comment by titou10titou10** [comment]
@vrutkovs, @JaimeMagiera  this is the same as described in the [KNOWN_ISSUES.md file](https://github.com/okd-project/okd/blob/master/KNOWN_ISSUES.md#some-optional-operators-from-ocp-are-not-available-in-okd) for logging (as an example)
...and the doc for logging IS present in the OKD doc even if you need a RH account

IMHO, its about consistency, either the doc for features/operators only available with a RH account are present in the OKD doc (With a statement saying you need a RH account..) or they are not, and in that case IMHO there should be as a minimum  a link to the related OCP doc and a statement saying you can get it with a RH account

**Comment by vrutkovs** [comment]
Agree, we'd need to remove references to the hidden section - until OKD operators is a thing

**Comment by JaimeMagiera** [comment]
Hi,

We are not working on FCOS builds of OKD any more. Please see these documents...

https://okd.io/blog/2024/06/01/okd-future-statement
https://okd.io/blog/2024/07/30/okd-pre-release-testing

The new operators project is alive and well. You can read more here... https://okd.io/docs/operators/

Many thanks,

Jaime
