### ISSUE TITLE
UPI Bare metal 4.11.0 bootstrap failed to install 

### ISSUE THREAD

**Issue by ttsvetanov92** [okd-project/okd#1404]
**Describe the bug**
I am trying to setup UPI Bare metal 4.11.0, but i result with some errors about manifests:

```
Nov 14 12:00:16 okd4-bootstrap.lab.okd.local cluster-bootstrap[2964]: [#21] failed to create some manifests:
Nov 14 12:00:16 okd4-bootstrap.lab.okd.local cluster-bootstrap[2964]: "etcd-signer-secret.yaml": failed to create secrets.v1./etcd-signer -n openshift-config: etcdserver: request timed out
Nov 14 12:00:17 okd4-bootstrap.lab.okd.local cluster-bootstrap[2964]: Skipped "etcd-signer-secret.yaml" secrets.v1./etcd-signer -n openshift-config as it already exists
Nov 14 12:00:17 okd4-bootstrap.lab.okd.local bootkube.sh[2880]: Skipped "etcd-signer-secret.yaml" secrets.v1./etcd-signer -n openshift-config as it already exists
Nov 14 12:09:28 okd4-bootstrap.lab.okd.local cluster-bootstrap[2964]: Error: error while checking pod status: timed out waiting for the condition
Nov 14 12:09:28 okd4-bootstrap.lab.okd.local cluster-bootstrap[2964]: Tearing down temporary bootstrap control plane...
Nov 14 12:09:28 okd4-bootstrap.lab.okd.local bootkube.sh[2880]: Error: error while checking pod status: timed out waiting for the condition
Nov 14 12:09:28 okd4-bootstrap.lab.okd.local bootkube.sh[2880]: Tearing down temporary bootstrap control plane...
Nov 14 12:09:28 okd4-bootstrap.lab.okd.local cluster-bootstrap[2964]: Error: error while checking pod status: timed out waiting for the condition
```

**Version**
OKD version release: 4.11.0-0.okd-2022-11-05-030711
Image version: fedora-coreos-36.20220716.3.1-metal.x86_64.raw.xz
UPI install method with esxi 6.0.0 (vSphere).

install-config.yaml contents (ignore symbol $ and line numbers, it's copied via vim):

```
  1 apiVersion: v1$
  2 baseDomain: okd.local$
  3 metadata:$
  4   name: lab$
  5 $
  6 compute:$
  7 - hyperthreading: Enabled$
  8   name: worker$
  9   replicas: 0$
 10 $
 11 controlPlane:$
 12   hyperthreading: Enabled$
 13   name: master$
 14   replicas: 3$
 15 $
 16 networking:$
 17   clusterNetwork:$
 18   - cidr: 10.128.0.0/14 $
 19     hostPrefix: 23 $
 20   networkType: OpenShiftSDN$
 21   serviceNetwork: $
 22   - 172.30.0.0/16$
 23 $
 24 platform:$
 25   none: {}$
 26 $
 27 fips: false$
 28 $
 29 pullSecret: 'auth from redhat' $
 30 sshKey: ''id_rsa.pub content
```

**How reproducible**
100%

**Log bundle**
https://drive.google.com/file/d/1Y1LPcsh6XCeyJvIk48cZLWUcsYhPMohQ/view?usp=share_link

**Comment by vrutkovs** [comment]
Please attach [log bundle](https://docs.okd.io/latest/installing/installing-troubleshooting.html#installation-bootstrap-gather_installing-troubleshooting). bootkube log is good and it shows
>etcdserver: request timed out
which is probably due to slow disk/network, but etcd pod logs would show more

**Comment by darren-oxford** [comment]
I notice you don't have a machineNetwork entry in your install-config.yaml could that be the problem?

**Comment by ttsvetanov92** [comment]
> Please attach [log bundle](https://docs.okd.io/latest/installing/installing-troubleshooting.html#installation-bootstrap-gather_installing-troubleshooting). bootkube log is good and it shows
> 
> > etcdserver: request timed out
> > which is probably due to slow disk/network, but etcd pod logs would show more

Link updated with bundled logs.

**Comment by ttsvetanov92** [comment]
> 
If I'm not mistaken, machineNetwork is for configuring the cluster-wide proxy during the installation. (Production environments can deny direct access to the Internet and instead have an HTTP or HTTPS proxy available). Since all the machines have access to internet, i don't see the point of adding it in the install-config.yaml
