### ISSUE TITLE
Update to 4.11.0-0.okd-2022-12-03-100655 offered

### ISSUE THREAD

**Issue by darren-oxford** [okd-project/okd#1433]
After updating to 4.11.0-0.okd-2022-12-02-145640 I am now being offered an upgrade to 4.11.0-0.okd-2022-12-03-100655. However 4.11.0-0.okd-2022-12-03-100655 is not listed as a valid release, either here on GitHub or on the CI page https://amd64.origin.releases.ci.openshift.org

The cluster is set to the usual stable-4 channel with the source as https://amd64.origin.releases.ci.openshift.org/graph. I have checked there and there is also no 4.11.0-0.okd-2022-12-03-100655 release. Is this perhaps a release that was accidentally made available and then pulled, but the cluster is still showing as an update option maybe?

**Comment by vrutkovs** [comment]
Ah, this is a long-standing release-controller bug/weird behaviour. When a new stable is released we mirror a nightly to quay and make a github release. The process is not instantenous and a new nightly may be scheduled at that time, starting a nightly-to-nightly upgrade test. As a result, we may end up with a stable-to-nightly upgrade edge.

I'll remove 4.11.0-0.okd-2022-12-03-100655 and see if that rebuilds the graph, but we'll need smth like https://github.com/openshift/release-controller/pull/295 to prevent this

**Comment by darren-oxford** [comment]
Thanks Vadim, that has updated the graph and I am no longer being offered the nightly.
