### ISSUE TITLE
OKD 4.11.9 & Proxmox : Installation failed after Bootstrap

### ISSUE THREAD

**Issue by KvnOnWeb** [okd-project/okd#1437]
**Describe the bug**
Hi ! I have a problem when boostrap complete : Console and authentication not Ready. I have 503 call : 
"APIServicesAvailable: "oauth.openshift.io.v1" is not ready: an attempt failed with statusCode = 503, err = the server is currently unable to handle the request..."

I have six server proxmox with one "okd-services" contains : DNS server, haproxy, pxe server. And 3 master / 3 worker. Domains calls between nodes / master works (ping test). When i try to access to console : I access on cluster but with the not available screen (same as route not exist in cluster).

Note : I have a home lab proxmox with one server (with 6 VM : 3 master / 3 worker) and it works.

* I try OpenShiftSDN and OVNKubernetes network type. Nothing change.
* I try to launch only 3 master scheduled. Nothing change.

The bug seems to be like this issue : 
- https://github.com/okd-project/okd/issues/430
- https://github.com/okd-project/okd/issues/395

** Print clusteroperators **
> [root@okd-services ~]# oc get clusteroperators
NAME                                       VERSION   AVAILABLE   PROGRESSING   DEGRADED   SINCE   MESSAGE
authentication                             4.11.9    False       False         True       33h     OAuthServerRouteEndpointAccessibleControllerAvailable: Get "https://oauth-openshift.apps.cloud.soyouweb.fr/healthz": EOF
baremetal                                  4.11.9    True        False         False      33h
cloud-controller-manager                   4.11.9    True        False         False      33h
cloud-credential                           4.11.9    True        False         False      33h
cluster-autoscaler                         4.11.9    True        False         False      33h
config-operator                            4.11.9    True        False         False      33h
console                                    4.11.9    False       False         False      32h     DeploymentAvailable: 0 replicas available for console deployment...
csi-snapshot-controller                    4.11.9    True        False         False      33h
dns                                        4.11.9    True        False         False      33h
etcd                                       4.11.9    True        False         False      33h
image-registry                             4.11.9    False       True          True       33h     Available: The deployment does not have available replicas...
ingress                                    4.11.9    True        False         True       7m49s   The "default" ingress controller reports Degraded=True: DegradedConditions: One or more other status conditions indicate a degraded state: CanaryChecksSucceeding=False (CanaryChecksRepetitiveFailures: Canary route checks for the default ingress controller are failing)
insights                                   4.11.9    True        False         False      33h
kube-apiserver                             4.11.9    True        False         False      33h
kube-controller-manager                    4.11.9    True        False         True       33h     GarbageCollectorDegraded: error fetching rules: Get "https://thanos-querier.openshift-monitoring.svc:9091/api/v1/rules": net/http: TLS handshake timeout
kube-scheduler                             4.11.9    True        False         False      33h
kube-storage-version-migrator              4.11.9    True        False         False      33h
machine-api                                4.11.9    True        False         False      33h
machine-approver                           4.11.9    True        False         False      33h
machine-config                             4.11.9    True        False         False      33h
marketplace                                4.11.9    True        False         False      33h
monitoring                                           False       False         True       33h     Rollout of the monitoring stack failed and is degraded. Please investigate the degraded status error.
network                                    4.11.9    True        False         False      33h
node-tuning                                4.11.9    True        False         False      33h
openshift-apiserver                        4.11.9    False       False         False      166m    APIServicesAvailable: "build.openshift.io.v1" is not ready: an attempt failed with statusCode = 503, err = the server is currently unable to handle the request...
openshift-controller-manager               4.11.9    True        False         False      9h
openshift-samples                                    False       False         False      10s     error creating samples: the server is currently unable to handle the request (put imagestreams.image.openshift.io dotnet-runtime)
operator-lifecycle-manager                 4.11.9    True        False         False      33h
operator-lifecycle-manager-catalog         4.11.9    True        False         False      33h
operator-lifecycle-manager-packageserver   4.11.9    False       False         False      8h      ClusterServiceVersion openshift-operator-lifecycle-manager/packageserver observed in phase Failed with reason: InstallCheckFailed, message: install timeout
service-ca                                 4.11.9    True        False         False      33h
storage                                    4.11.9    True        False         False      33h

**Version**
4.11.9 (and 4.9.45 as the same probleme)
UPI / platform : none 

**How reproducible**
100%

[must-gather.log](https://github.com/okd-project/okd/files/10206948/must-gather.log)

**Comment by KvnOnWeb** [comment]
Ho my bad, i think i was on OKD. There is a repo like this for OKD ? https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/4.11/4.11.9/

**Comment by vrutkovs** [comment]
See https://github.com/okd-project/okd#getting-started
