### ISSUE TITLE
OKD Installer workspace. Blank repo

### ISSUE THREAD

**Issue by valumar** [okd-project/okd#1448]
There is an invalid link on the [OKD Installer Workspace](https://github.com/okd-project/okd/blob/master/Guides/UPI/baremetal/installer-workspace.md) page which leads to an empty [repository](https://github.com/GingerGeek/okd-installer-workspace). Please correct it.

@GingerGeek @vrutkovs

**Comment by JaimeMagiera** [comment]
@GingerGeek are you maintaining the workspace project anymore? If not, we'll remove the referencing page from the OKD documentation repo. 

@valumar Please don't tag volunteers specifically on documentation issues. We need to share the responsibilities and make sure no particular person burns out. Thank you.
