### ISSUE TITLE
4.11.0-0.okd-2022-12-02-145640  IPI on vSphere problem with resolved-systemd DNS

### ISSUE THREAD

**Issue by clementcohen** [okd-project/okd#1457]
Hello, 
i've successfully installed  multiple OKD versions on disconnected environment,  but this time i've an issue with  dns .. 
bootstrap node refuse  to resolve the  registry's DNS for some obscure reason..

**Describe the bug**

Bootstrap node is unable to resolve  dns of private registry 
the DNS is a .local (  cnam-dmz.local )  as far as I know we do not perfoms mDNS  query 

Jan 05 08:37:44 localhost.localdomain release-image-download.sh[1925]: Error: initializing source docker://quay.io/openshift/okd@sha256:924958ed5ba93ea9d72e4b5a319d0d4df220edbb891816c106215cbf318a0a40: (Mirrors also failed: [harbor.cnam-dmz.local/quay/openshift/okd@sha256:924958ed5ba93ea9d72e4b5a319d0d4df220edbb891816c106215cbf318a0a40: pinging container registry harbor.cnam-dmz.local: Get "https://harbor.cnam-dmz.local/v2/": dial tcp: lookup harbor.cnam-dmz.local: Temporary failure in name resolution]): quay.io/openshift/okd@sha256:924958ed5ba93ea9d72e4b5a319d0d4df220edbb891816c106215cbf318a0a40: pinging container registry quay.io: Get "https://quay.io/v2/": dial tcp 54.163.152.191:443: i/o timeout

resolvectl status show our dns, a dig on another server is working fine ( but not through resolved-systemd mecanism )

i've seen other issue and a /etc/nsswitch.conf fix, but as this is IPI i'd like to avoid any manual changes

**Version**

4.11.0-0.okd-2022-12-02-145640  IPI on vSphere

**How reproducible**
100%

**Log bundle**

[log-bundle-20230105094859.tar.gz](https://github.com/okd-project/okd/files/10350714/log-bundle-20230105094859.tar.gz)

Thanks,

**Comment by vrutkovs** [comment]
Seems your DHCP server didn't set nameserver in options? As a result, we can't fetch machine-os-content to read network params from vsphere args?
