### ISSUE TITLE
Bootstrap problem with (4.11.0-0.okd-2022-12-02-145640) /usr/bin/hyperkube  appears to late

### ISSUE THREAD

**Issue by fruboes** [okd-project/okd#1458]
**Describe the bug**
UPI install fails on bootstrap machine due to '/usr/bin/hyperkube' file missing. File appears on the bootstrap machine  later at some moment (e.g. after reset),  but it seems to appear to late. 

I'm trying to simulated a bare-metal install in ovirt environment. Installation done as described in https://docs.okd.io/4.11/installing/installing_bare_metal/installing-bare-metal.html#installing-bare-metal (i.e. dns and haproxy taken from examples with ip addresses adjusted). Machines boot method - PXE, with ign files passed on boot (ie APPEND=(....) coreos.inst.ignition_url=http://10.60.0.201:8000/master.ign in pxelinux.cfg/default). Links to coreos installation files taken from the installer (fedora-coreos-36.20220716.3.1). In order to verify this is not some ovirt vm configuration issue I have repeated whole process in different vm software (virtualbox) on a different machine - same result.

**Version**
4.11.0-0.okd-2022-12-02-145640

**How reproducible**
100%

**Log bundle**
https://mega.nz/file/WFB23QCC#ySj1OG9rWfV5KthdgpIigL_rGOD-B9Yg40XOoDxT008

Any ideas ? Help or suggestions  here  would be greatly appreciated.

**Comment by vrutkovs** [comment]
etcd won't start:
```
{"level":"warn","ts":"2023-01-09T20:15:16.707Z","caller":"wal/wal.go:805","msg":"slow fdatasync","took":"4.975445654s","expected-duration":"1s"}
```
possibly slow disks
