### ISSUE TITLE
[OKD 4.12 installer][vSphere IPI]  IP expected to be in one of the machine networks: 10.0.0.0/16

### ISSUE THREAD

**Issue by fortinj66** [okd-project/okd#1489]
**Describe the bug**
new install of OKD 4.12 vSphere IPI fails with invalid API IP address

? Network VLAN_65
X Sorry, your reply was invalid: IP expected to be in one of the machine networks: 10.0.0.0/16
? Virtual IP Address for API [? for help]

API VIP is 10.102.5.11

The following bug which seems to be related is in the release notes for this version:

https://issues.redhat.com/browse/OCPBUGS-6015 fail to create install-config.yaml as apiVIP and ingress VIP are not in machine networks [#6783](https://github.com/openshift/installer/pull/6783)

**Version**

OKD 4.12 Stable

[root@os-utils-d03 <poc410> poc410]$ ./openshift-install version
./openshift-install 4.12.0-0.okd-2023-01-21-055900
built from commit e33d9bda73e58d6584f922d68260931c02992a41
release image quay.io/openshift/okd@sha256:8c5e4d3a76aba995c005fa7f732d68658cc67d6f11da853360871012160b2ebf
release architecture amd64

**How reproducible**
100%

**Log bundle**

**Comment by fortinj66** [comment]
This is also broken in the latest nightly:

DEBUG       Loading Platform...
ERROR failed to fetch Metadata: failed to load asset "Install Config": failed to create install config: invalid "install-config.yaml" file: [platform.vsphere.apiVIPs: Invalid value: "10.102.5.11": IP expected to be in one of the machine networks: 10.0.0.0/16, platform.vsphere.ingressVIPs: Invalid value: "10.102.5.12": IP expected to be in one of the machine networks: 10.0.0.0/16]

**Comment by jcpowermac** [comment]
Workaround
Create a install-config.yaml manually and set 
```
networking:
  machineNetwork:
  - cidr: "10.102.0.0/16" 
```

**Comment by JaimeMagiera** [comment]
Hi,

We are not working on FCOS builds of OKD any more. Please see these documents...

https://okd.io/blog/2024/06/01/okd-future-statement
https://okd.io/blog/2024/07/30/okd-pre-release-testing

Please test with the OKD SCOS nightlies and file a new issue as needed.

Many thanks,

Jaime
