### ISSUE TITLE
[OKD 4.12] Installation failed on User Provisioned Baremetal

### ISSUE THREAD

**Issue by Rouf111** [okd-project/okd#1496]
Bootstrap machine failed to get created on baremetal node. Upon reviewing the logs of the Kube controller manager, it was trying to load configuration data but couldn't!

**Describe the bug**

1. Based on the Kube controller manager logs, it appears that the configmap object couldn't be loaded.
2. The configmap object had already been created when I reviewed it. 
3.The Kube controller manager couldn't load it, so an error was thrown
`dial tcp "[::1]:6443: connect: connection refused` 
4. Additionally, I reviewed the Kube schedule and found the same logs.

`I0205 18:02:00.327437       1 serving.go:342] Generated self-signed cert (/var/run/kubernetes/kube-controller-manager.crt, /var/run/kubernetes/kube-controller-manager.key)
I0205 18:02:00.328664       1 dynamic_serving_content.go:113] "Loaded a new cert/key pair" name="serving-cert::/var/run/kubernetes/kube-controller-manager.crt::/var/run/kubernetes/kube-controller-manager.key"
E0205 18:02:00.652164       1 run.go:74] "command failed" err="unable to load configmap based request-header-client-ca-file: Get \"https://localhost:6443/api/v1/namespaces/kube-system/configmaps/extension-apiserver-authentication\": dial tcp [::1]:6443: connect: connection refused"`
ConfigMap is already available:
![image](https://user-images.githubusercontent.com/99723857/217051324-a21b58b2-40e7-4107-aa3a-f5ce4dcf0aa8.png)

Logs from Kube Scheduler:

`W0205 18:02:00.523810       1 reflector.go:424] vendor/k8s.io/client-go/informers/factory.go:134: failed to list *v1.Node: Get "https://localhost:6443/api/v1/nodes?limit=500&resourceVersion=0": dial tcp [::1]:6443: connect: connection refused
E0205 18:02:00.523905       1 reflector.go:140] vendor/k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.CSIStorageCapacity: failed to list *v1.CSIStorageCapacity: Get "https://localhost:6443/apis/storage.k8s.io/v1/csistoragecapacities?limit=500&resourceVersion=0": dial tcp [::1]:6443: connect: connection refused
W0205 18:02:00.523830       1 reflector.go:424] vendor/k8s.io/client-go/informers/factory.go:134: failed to list *v1.StorageClass: Get "https://localhost:6443/apis/storage.k8s.io/v1/storageclasses?limit=500&resourceVersion=0": dial tcp [::1]:6443: connect: connection refused
E0205 18:02:00.523948       1 reflector.go:140] vendor/k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Node: failed to list *v1.Node: Get "https://localhost:6443/api/v1/nodes?limit=500&resourceVersion=0": dial tcp [::1]:6443: connect: connection refused
E0205 18:02:00.523977       1 reflector.go:140] vendor/k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.StorageClass: failed to list *v1.StorageClass: Get "https://localhost:6443/apis/storage.k8s.io/v1/storageclasses?limit=500&resourceVersion=0": dial tcp [::1]:6443: connect: connection refused
W0205 18:02:00.523962       1 reflector.go:424] vendor/k8s.io/client-go/informers/factory.go:134: failed to list *v1.CSINode: Get "https://localhost:6443/apis/storage.k8s.io/v1/csinodes?limit=500&resourceVersion=0": dial tcp [::1]:6443: connect: connection refused
E0205 18:02:00.524049       1 reflector.go:140] vendor/k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.CSINode: failed to list *v1.CSINode: Get "https://localhost:6443/apis/storage.k8s.io/v1/csinodes?limit=500&resourceVersion=0": dial tcp [::1]:6443: connect: connection refused
W0205 18:02:00.524014       1 reflector.go:424] vendor/k8s.io/client-go/informers/factory.go:134: failed to list *v1.CSIDriver: Get "https://localhost:6443/apis/storage.k8s.io/v1/csidrivers?limit=500&resourceVersion=0": dial tcp [::1]:6443: connect: connection refused
E0205 18:02:00.524129       1 reflector.go:140] vendor/k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.CSIDriver: failed to list *v1.CSIDriver: Get "https://localhost:6443/apis/storage.k8s.io/v1/csidrivers?limit=500&resourceVersion=0": dial tcp [::1]:6443: connect: connection refused`

**Version**

openshift-install 4.12.0-0.okd-2023-01-21-055900
built from commit e33d9bda73e58d6584f922d68260931c02992a41
release image quay.io/openshift/okd@sha256:8c5e4d3a76aba995c005fa7f732d68658cc67d6f11da853360871012160b2ebf
release architecture amd64  

**How reproducible**
 100%. 

**Log bundle**
 
[log-bundle-20230205171101.tar.gz](https://github.com/okd-project/okd/files/10667794/log-bundle-20230205171101.tar.gz)

If you need any further information, please let me know. 
Using dig utility, I have also verified the DNS rDNS works perfectly.

**Comment by melledouwsma** [comment]
From the bootkube.log:

```
Feb 05 09:54:24 bootstrap.test.voereir.io bootkube.sh[2969]: Check if API and API-Int URLs are resolvable during bootstrap
Feb 05 09:54:24 bootstrap.test.voereir.io bootkube.sh[2969]: Checking validity of api.test.voereir.io of type API_URL
Feb 05 09:54:24 bootstrap.test.voereir.io bootkube.sh[2969]: Starting stage check-api-url
Feb 05 09:54:24 bootstrap.test.voereir.io bootkube.sh[2969]: Unable to resolve API_URL api.test.voereir.io
Feb 05 09:54:24 bootstrap.test.voereir.io bootkube.sh[2969]: Checking validity of api-int.test.voereir.io of type API_INT_URL
Feb 05 09:54:24 bootstrap.test.voereir.io bootkube.sh[2969]: Starting stage check-api-int-url
Feb 05 09:54:24 bootstrap.test.voereir.io bootkube.sh[2969]: Unable to resolve API_INT_URL api-int.test.voereir.io
```

Are you sure all DNS requirements are met? You can find more on DNS entries for a user-provisioned installation on [this page](https://docs.okd.io/latest/installing/installing_platform_agnostic/installing-platform-agnostic.html#installation-dns-user-infra_installing-platform-agnostic) in the OKD docs.

**Comment by Rouf111** [comment]
@melledouwsma Yes, I set it up properly, I looked through these logs and tried the manual nslookup and it was resolved. I don't know why this is happening! 
However, I found another release of 4.12  ([4.12.0-0.okd-2023-02-04-212953]) and tried with this and it worked fine!
Thank you for the follow-up! we can close this bug!
