### ISSUE TITLE
OKD IPI Deployment failure - on vmware

### ISSUE THREAD

**Issue by rajspeed1** [okd-project/okd#1508]
**Describe*
Openshift-install (OKD)  failed to create cluster on vmware with SSL X509 errors.
No Option on OKD vmware parameters to ignore/skip SSL validation for mentioning on install-config.yaml. 
(Although terraform vmware modules are having option to skip ssl verification)

**Version**
4.11.17
IPI Deployment

**How reproducible**
100% reproducible

**Comment by jcpowermac** [comment]
@rajspeed1 we don't allow skipping ssl verification in the installer.

see: https://docs.openshift.com/container-platform/4.12/installing/installing_vsphere/installing-vsphere-installer-provisioned.html#installation-adding-vcenter-root-certificates_installing-vsphere-installer-provisioned
