### ISSUE TITLE
[OKD4.12] Bootstrap install ostree error

### ISSUE THREAD

**Issue by CopyShizu1** [okd-project/okd#1509]
**Describe the bug**
Bootstrap cant finish the installation because of the stage rebase to okd os image

**Version**

4.12

**How reproducible**

100% for me

**Log bundle**

[test.tar.gz](https://github.com/okd-project/okd/files/10761927/test.tar.gz)

Hey guys i am currently trying to install okd 4.12 cluster on bare metal with proxmox.
Haproxy PFsense and DNS are up and running.

when i try to boot up boostrap i get over and over again the same error in the rebase-to-okd-os-image stage
full gather below.

++ rpm-ostree rebase --experimental ostree-unverified-registry:quay.io/openshift/okd-content@sha256:ae04fc72f2532d27d75c628cd242d0ab3bd9ea8001e4333153ffc5db2bfb6a79
error: Invalid refspec ostree-unverified-registry:quay.io/openshift/okd-content@sha256:ae04fc72f2532d27d75c628cd242d0ab3bd9ea8001e4333153ffc5db2bfb6a79
+ record_service_exit 1

I am not sure if its a bug on okd or fedore coreos but i am using the recommended raw.xz

**Comment by vrutkovs** [comment]
>Linux version 5.12.12-300.fc34.x86_64

The initial FCOS is too old, see https://github.com/okd-project/okd/blob/master/FAQ.md#which-fedora-coreos-should-i-use
