### ISSUE TITLE
EgressIP with OVN-Kubernetes causes network connectivity issues

### ISSUE THREAD

**Issue by netwarex** [okd-project/okd#1511]
**Describe the bug**

Same issue happens described in this article for OpenShift which should have been fixed: https://access.redhat.com/solutions/6247851

```
Pods have connectivity issues when using an EgressIP including:

- Dropping of connection from time to time.
- Experiencing network timeouts when connecting to services outside of a cluster.
- After adding an EgressIP resource to selected Namespaces/Pods, the configuration
  may initially function correctly, but after some time the pods may start to display the above issues.
```

**Version**

Version: 4.11.0-0.okd-2023-01-14-152430
Installed as UPI on KVM/Proxmox and Baremetal

**How reproducible**

It's happening after a while.

**Log bundle**

Ticket about the OCP issue: https://bugzilla.redhat.com/show_bug.cgi?id=1976215

After running this script mentioned in the Knowledgebase (with slight modification to display the correct columns), it shows the issue:

Code to verify:
```
EGRESS_NAME=egress-ip-resource
POD=$(oc -n openshift-ovn-kubernetes get pod -o custom-columns=POD:.metadata.name --no-headers  --selector='app==ovnkube-master' | head -n1)
oc -n openshift-ovn-kubernetes exec $POD -c ovnkube-master -it -- ovsdb-client --private-key=/ovn-cert/tls.key --certificate=/ovn-cert/tls.crt --ca-cert=/ovn-ca/ca-bundle.crt -f csv --no-headings dump ssl:localhost:9641 OVN_Northbound NAT | grep "name=$EGRESS_NAME" | tr -d '"' | cut -d ',' -f9,10 | sort -u
```

Output:
```
[...]
10.131.0.36,k8s-infra-3
10.131.0.37,k8s-infra-2
10.131.0.37,k8s-infra-3
10.131.0.39,k8s-infra-2
```

Which shows, the pods are attached to multiple nodes. Restarting one of these nodes are clearing the issue until it's happening again.

**Comment by vrutkovs** [comment]
If its not OKD-specific lets track this in bugzilla, OKD will receive the fix automatically.

Seems the issue is still occurring, so you would need to file a new bug (in Jira this time - https://issues.redhat.com/projects/OCPBUGS) with must-gather
