### ISSUE TITLE
Update to 4.12.0-0.okd-2023-02-18-033438: unable to verify ... against keyrings: verifier-public-key-ci

### ISSUE THREAD

**Issue by mschauf** [okd-project/okd#1514]
Hello! 
When updating a ipi vsphere installation from 4.12.0-0.okd-2023-02-04-212953 to 4.12.0-0.okd-2023-02-18-033438 following error appears:

`Retrieving payload failed version="4.12.0-0.okd-2023-02-18-033438" image="[registry.ci.openshift.org/origin/release@sha256:fd08a1dae13a434729451cdb6edd969714a4329904e8d27eb45d94e96021dff4](http://registry.ci.openshift.org/origin/release@sha256:fd08a1dae13a434729451cdb6edd969714a4329904e8d27eb45d94e96021dff4)" failure=The update cannot be verified: unable to verify sha256:fd08a1dae13a434729451cdb6edd969714a4329904e8d27eb45d94e96021dff4 against keyrings: verifier-public-key-ci`

**Comment by vrutkovs** [comment]
Seems we used an outdated GPG key to sign the release :( https://github.com/openshift/release/pull/36617 would fix it for other nightlies

The workaround is to apply the upgrade with `--force`. Keeping this open to make sure it got resolved in the new stable

**Comment by peterroth** [comment]
Same issue happened from `4.12.0-0.okd-2023-04-16-041331` to `4.12.0-0.okd-2023-11-20-220231` (nightly build) today.
