### ISSUE TITLE
[OKD 4.12][vSphere IPI]  node-valid-hostname-service fails after 5 minutes 17 seconds on firstboot of new nodes 

### ISSUE THREAD

**Issue by fortinj66** [okd-project/okd#1517]
**Describe the bug**

On initial install of a cluster and when new nodes are created the nodes get stuck waiting for node-valid-hostname to complete/fail  for over 5 minutes.  after it fails the node install continues on as expected and node-valid-hostname-service runs properly after first boot.

![image](https://user-images.githubusercontent.com/8594283/220667893-729b768c-1973-4afb-8e6c-409663e5bd3c.png)
![image](https://user-images.githubusercontent.com/8594283/220672182-84d190e7-2494-4ded-a36a-ec8e8c9d3e79.png)

I'm wondering whether this service should only run after firstboot completes, not during.

**Version**
4.12.0-0.okd-2023-02-18-033438

**How reproducible**
seems to be 100 %

**Comment by vrutkovs** [comment]
Right, node-valid-hostname should run after -firstboot. I don't think we can fix it in okd-machine-os, could you make a PR to machine-config-operator?

**Comment by mathianasj** [comment]
Seeing the same with baremetal IPI https://github.com/okd-project/okd/discussions/1528

**Comment by fortinj66** [comment]
> Right, node-valid-hostname should run after -firstboot. I don't think we can fix it in okd-machine-os, could you make a PR to machine-config-operator?

Hmmm, MCO and I don't get along very well...

**Comment by rassie** [comment]
Still happening on 4.13 (IPI/vSphere), fresh installation delayed for at least 10 minutes by first masters and then workers waiting for `node-valid-hostname`.

@vrutkovs I guess that PR on `machine-config-operator` never happened?

**Comment by JaimeMagiera** [comment]
Hi,

We are not working on FCOS builds of OKD any more. Please see these documents...

https://okd.io/blog/2024/06/01/okd-future-statement
https://okd.io/blog/2024/07/30/okd-pre-release-testing

Please test with the OKD SCOS nightlies and file a new issue as needed.

Many thanks,

Jaime
