### ISSUE TITLE
ostree fsck: Corrupted file object

### ISSUE THREAD

**Issue by ExNG** [okd-project/okd#1540]
**Describe the bug**

While upgrading a cluster from `4.11.0-0.okd-2023-01-21-111419` to `4.12.0-0.okd-2023-02-04-212953` the machine-config-daemon refused to update the FCOS because of, i think it was, unregistered packages glusterfs, glusterfs-fuse, qemu-guest-agent and NetworkManager-ovs.
Those packages where probably manually installed in the past while testing something and after `rpm-ostree uninstall ` but this isnt the issue since it might be our fault.
We at the time did not correlate this issue with anything specific about the nodes and after investigating found out that some older nodes of ours have corrupt ostree file objects. This seems to only be on clusters installed with 4.7 and older. 

Expected output:
```
ostree fsck
Validating refs...
Validating refs in collections...
Enumerating commits...
Verifying content integrity of 53 commit objects...
fsck objects (1/27220) 0%
fsck objects (4047/27220) 14%
fsck objects (10355/27220) 38%
fsck objects (13729/27220) 50%
fsck objects (16307/27220) 59%
fsck objects (21346/27220) 78%
fsck objects (24934/27220) 91%
fsck objects (27220/27220) 100%
object fsck of 53 commits completed successfully - no errors found.
```

Older node:
```
ostree fsck
Validating refs...
Validating refs in collections...
Enumerating commits...
Verifying content integrity of 53 commit objects...
fsck objects (1/27220) 0%
fsck objects (6571/27220) 24%
fsck objects (13726/27220) 50%
error: In commits 217863246506e9bb3b425cbc618dad94b20634c6b454ec7edbe6a8957a359d00, 290856631b38e287957569699796a82724bdbc20dbfba37fb5e79c8bb4135160: fsck content object 829344a075c8f0eafea5c4b252bd8feb07d775923ede4e82cce0ee9fd2a5edd0: Corrupted file object; checksum expected='829344a075c8f0eafea5c4b252bd8feb07d775923ede4e82cce0ee9fd2a5edd0' actual='bf13d8fe63612425b89f526a906f06359a1a71ac71902caef8a7160558d91187'
```

**Version**

4.12.0-0.okd-2023-02-04-212953 UPI

**How reproducible**

N.A. 

**Log bundle**

https://clouddrive.avm.de/s/oHEkRBeJgKPQLP2
PW: FPji6NJpGO

**Comment by vrutkovs** [comment]
>machine-config-daemon refused to update the FCOS

Right, that's #1483 

>some older nodes of ours have corrupt ostree file objects

Some, but not all I guess? Check if your disks are healthy

**Comment by ExNG** [comment]
> Right, that's https://github.com/okd-project/okd/issues/1483

Yes this looks familiar thanks.
Is there an alternative to ostree-rebaseing the nodes VMs with a corrupted objects?

**Comment by ExNG** [comment]
Hi @vrutkovs hope you're well.
While researching a seemingly unrelated issue which involved CgroupV1 being enabled, it was noted there being a pivot config at `/etc/pivot/kernel-args` from an older version of OKD with `systemd.unified_cgroup_hierarchy=0` in it, this file was manually deleted.
There might be a problem with [machine-config-operator](https://github.com/openshift/machine-config-operator/blob/4acaaded2422e859d9f500f45a1b39f7e6d60600/pkg/daemon/update.go) which did properly cleanup this config.
Today, after another update, `ostree fsck` did not find any errors.
I know you wont fix these kind of special issues for older installs but hope this helps in debugging future problems.
