### ISSUE TITLE
Assisted installer agent: Unable to pull okd binaries on nodes behind a proxy

### ISSUE THREAD

**Issue by a-elie** [okd-project/okd#1542]
**Describe the bug**

Agent service doesn't start on cluster nodes (booting from agent.iso) because okd-binaries.sh can't pull an okd image 

Root cause : HTTPS_PROXY is not set and /etc/profile.d/proxy.sh doesn't exists

As a temp workaround, one can ssh to each node and add `export HTTP(S)_PROXY=_proxy_url_` before `podman pull` line.
After that, discovery and installation succeeds

```bash
# edit file and restart service
sudo vi /usr/local/bin/okd-binaries.sh ; sudo systemctl restart okd-overlay.service
```

Don't know if it's related, but if I don't add HTTP(S)_PROXY in okd-configmap.yml, cluster nodes joins discovery without any problem (but installation fails because assisted-installer can't  download installation files)

**Version**

Baremetal IPI (libvirt) with assisted installer agent (podman)

OS_IMAGES: 

```json
[{"openshift_version":"4.12","cpu_architecture":"x86_64","url":"https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/37.20230205.3.0/x86_64/fedora-coreos-37.20230205.3.0-live.x86_64.iso","version":"37.20230205.3.0"}]
```

RELEASE_IMAGES: 

```json
[{"openshift_version":"4.12","cpu_architecture":"x86_64","cpu_architectures":["x86_64"],"url":"quay.io/openshift/okd:4.12.0-0.okd-2023-03-05-022504","version":"4.12.0-0.okd-2023-03-05-022504","default":true}]
```

```bash
podman images
REPOSITORY                                          TAG               IMAGE ID      CREATED     SIZE
localhost/podman-pause                              4.2.0-1667932451  0988768b0889  4 days ago  739 kB
quay.io/edge-infrastructure/assisted-image-service  latest            fe99790f4d21  5 days ago  400 MB
quay.io/edge-infrastructure/assisted-service        latest            73d6d4a24ee2  5 days ago  973 MB
quay.io/centos7/postgresql-12-centos7               latest            ed33c67aa405  7 days ago  383 MB
quay.io/edge-infrastructure/assisted-installer-ui   latest            1e6ad6c750ff  8 days ago  472 MB
```

**How reproducible**
100%

**Log bundle**

**Comment by JaimeMagiera** [comment]
Hi,

We are not working on FCOS builds of OKD any more. Please see these documents...

https://okd.io/blog/2024/06/01/okd-future-statement
https://okd.io/blog/2024/07/30/okd-pre-release-testing

Please test with the OKD SCOS nightlies and file a new issue as needed.

Many thanks,

Jaime
