### ISSUE TITLE
[OKD 4.12] Cluster settings link to non-public Red Hat subscription content 

### ISSUE THREAD

**Issue by ssams** [okd-project/okd#1545]
**Describe the bug**

After upgrading the cluster from an earlier version, an alert and corresponding message in the cluster settings warn about requiring explicit acknowledgement before upgrading to future releases (both expected and not a bug on its own):

> This cluster should not be updated to the next minor version.
> 
> Kubernetes 1.26 and therefore OpenShift 4.13 remove several APIs which require admin consideration. Please see the knowledge article https://access.redhat.com/articles/6958394 for details and instructions.

The linked knowledge article however is marked as "Subscriber exclusive content" and not accessible without a Red Hat subscription, hence the shown message effectively provides no further details and instructions on how to resolve the warning. I'd expect the link to be either publicly accessible, or updated to point towards OKD documentation with further information.

**Version**
`4.12.0-0.okd-2023-03-18-084815` - baremetal installation

**How reproducible**
Install (or upgrade) a cluster, check *\<console-URL\>/settings/cluster* for the update warning message

**Comment by JaimeMagiera** [comment]
Thank you for reaching out. The OKD Working Group will discuss this issue. I'll let you know what we land on.

**Comment by ssams** [comment]
any news on this? in the meantime, the current 4.13 version (`4.13.0-0.okd-2023-07-23-051208`) again contains a new link to non accessible content:

> This cluster should not be updated to the next minor version.
>
> Kubernetes 1.27 and therefore OpenShift 4.14 remove several APIs which require admin consideration. Please see the knowledge article https://access.redhat.com/articles/6958395 for details and instructions.

**Comment by nate-duke** [comment]
@ssams 

FWIW the only thing germane there is a link to the kubernetes deprecation page for 1.27

https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-27

**Comment by ssams** [comment]
> @ssams
> 
> FWIW the only thing germane there is a link to the kubernetes deprecation page for 1.27
> 
> https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-27

yes, the information on what needs to be done for the kubernetes update itself isn't hard to find, doesn't matter if one can access the RedHat page or not. Although in general there _could_ be OpenShift and thus also OKD specific additions that need to be taken care of.

Overall I mostly find it quite unexpected to see links to "Subscriber exclusive content" when operating an otherwise free product. Just need to point it towards the OKD docs or Kubernets docs if applicable instead.

**Comment by JaimeMagiera** [comment]
Hi,

We are not working on FCOS builds of OKD any more – in part to address these types of issues. Please see these documents...

https://okd.io/blog/2024/06/01/okd-future-statement
https://okd.io/blog/2024/07/30/okd-pre-release-testing

Please test with the OKD SCOS nightlies and file a new issue as needed.

Many thanks,

Jaime
