### ISSUE TITLE
High CPU usage in control-plane nodes on almost empty cluster 4.12.0-0.okd-2023-04-16-041331

### ISSUE THREAD

**Issue by apmlima** [okd-project/okd#1567]
High CPU usage in control-plane nodes on almost empty cluster. Occurring in the last 3 okd 4.12 versions. Is fine with 4.11.

NAME                                          CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%
ip-10-35-196-146.eu-west-1.compute.internal   304m         8%     4238Mi          13%
ip-10-35-196-56.eu-west-1.compute.internal    2088m        59%    6525Mi          44%
ip-10-35-197-51.eu-west-1.compute.internal    313m         8%     4060Mi          13%
ip-10-35-197-84.eu-west-1.compute.internal    3560m        101%   6029Mi          41%
ip-10-35-202-154.eu-west-1.compute.internal   114m         3%     1592Mi          5%
ip-10-35-202-165.eu-west-1.compute.internal   1810m        51%    5243Mi          35%

4.12.0-0.okd-2023-04-16-041331 (AWS)

AWS

https://drive.google.com/file/d/1Jxja9yTRQ334MqCP9CobaEbJx7j9Fl1y/view?usp=share_link

**Comment by vrutkovs** [comment]
must-gather doesn't have metrics, which pods / services are using most of the CPU?

**Comment by apmlima** [comment]
No, the top ones are community-operators and packageserver. It's sorted by reverse order, but you can see cpu/mem usage.

**Comment by vrutkovs** [comment]
Ah, okay, so its OLM. That's probably https://issues.redhat.com/browse/OCPBUGS-1152, not OKD specific
