### ISSUE TITLE
OKD 4.12 update cannot be verified

### ISSUE THREAD

**Issue by dkoci** [okd-project/okd#1572]
Update  from 4.12.0-0.okd-2023-04-01-051724 to the latest stable version failed with:

`Retrieving payload failed version="4.12.0-0.okd-2023-04-16-041331" image="registry.ci.openshift.org/origin/release@sha256:c51a70b2131b67a6f1140994de46a9ec42a9c07be051ca0883f96f5a2d0f4e4c" failure=The update cannot be verified: unable to verify sha256:c51a70b2131b67a6f1140994de46a9ec42a9c07be051ca0883f96f5a2d0f4e4c against keyrings: verifier-public-key-ci`

**Comment by titou10titou10** [comment]
The signing keys have rotated
You have to "force" the upgrade ie `oc adm upgrade --force`
See 
- https://github.com/okd-project/okd/discussions/1566#discussioncomment-5633599
- https://github.com/okd-project/okd/issues/1569#issuecomment-1512529808

**Comment by dkoci** [comment]
@titou10titou10 Thank you. `spec.desired.force: true` did the trick.
