### ISSUE TITLE
AWS install failing due to new S3 security changes

### ISSUE THREAD

**Issue by mhenson1** [okd-project/okd#1573]
**Describe the bug**
When attempting to install to AWS the installation fails with the following error
level=error msg=Error: error creating S3 bucket ACL for os-test-sblb7-bootstrap: AccessControlListNotSupported: The bucket does not allow ACLs
I believe this behavior is due to this change made by Amazon
https://aws.amazon.com/blogs/aws/heads-up-amazon-s3-security-changes-are-coming-in-april-of-2023/

It appears that any new buckets are created with ACL's disabled by default and I'm guessing the install process is expecting for them to be enabled.

**Version**
4.12.0-0.okd-2023-03-05-022504 on AWS with IPI

**How reproducible**
100%

**Log bundle**
level=info msg=Creating infrastructure resources...
level=error
level=error msg=Error: error creating S3 bucket ACL for os-test-sblb7-bootstrap: AccessControlListNotSupported: The bucket does not allow ACLs
level=error msg=	status code: 400, request id: KBN08SQ3BG33QBZ5, host id: joxoxwso57JUd6g5XLQC/Zd87vyzkIAQHPOuL2GA/YuS2T9gMCxft4iUW1p7UKLGDzxvlbWqscI=
level=error
level=error msg=  with aws_s3_bucket_acl.ignition,
level=error msg=  on main.tf line 62, in resource "aws_s3_bucket_acl" "ignition":
level=error msg=  62: resource "aws_s3_bucket_acl" ignition {
level=error
level=error msg=failed to fetch Cluster: failed to generate asset "Cluster": failure applying terraform for "bootstrap" stage: failed to create cluster: failed to apply Terraform: exit status 1-->

**Comment by mhenson1** [comment]
Never mind this. I just tried with the latest installer from a couple of days ago, 4.12.0-0.okd-2023-04-16-041331, and that installer worked without issues. Sorry for not trying the latest first.

**Comment by vrutkovs** [comment]
OCP bug: https://issues.redhat.com/browse/OCPBUGS-11636
