### ISSUE TITLE
Upgrade to 4.12.0-0.okd-2023-04-16-041331 failed: unable to verify against verifier-public-key-ci

### ISSUE THREAD

**Issue by mschaefers** [okd-project/okd#1578]
**Describe the bug**

Automatic Upgrade from `4.12.0-0.okd-2023-04-01-051724` to `stable-4` version `4.12.0-0.okd-2023-04-16-041331` is stuck with Condition `ReleaseAccepted: False` and Reason `RetrievePayload`, Message `Retrieving payload failed version="4.12.0-0.okd-2023-04-16-041331" image="registry.ci.openshift.org/origin/release@sha256:c51a70b2131b67a6f1140994de46a9ec42a9c07be051ca0883f96f5a2d0f4e4c" failure=The update cannot be verified: unable to verify sha256:c51a70b2131b67a6f1140994de46a9ec42a9c07be051ca0883f96f5a2d0f4e4c against keyrings: verifier-public-key-ci
`

**Version**

4.12.0-0.okd-2023-04-16-041331

**How reproducible**

N/A (cant reproduce - would involve a fresh cluster install)

**Log bundle**

**Comment by sherine-k** [comment]
Hello @mschaefers 
[This discussion](https://github.com/okd-project/okd/discussions/1566#discussioncomment-5633599) will probably help

**Comment by titou10titou10** [comment]
duplicate #1572 
duplicate #1574

**Comment by mschaefers** [comment]
I feel bad for having missed these bugs...
