### ISSUE TITLE
vmware-vsphere-csi-driver-controller" deployment runs with "hostNetwork: true"

### ISSUE THREAD

**Issue by guhilling** [okd-project/okd#1591]
**Describe the bug**
vmware-vsphere-csi-driver-controller" deployment runs with "hostNetwork: true". This is not the case in the upstream vsphere-csi-driver and I don't know why this should be necessary. In fact I'd like all vcenter accesses to originate from _one_ IP address and use EgressIP for this purpose. This approach works fine for the machine-operator but doesn't work for the vsphere csi-driver as it uses hostNetwork.

This might not be a "bug" in the normal sense but in upstream "csi vsphere provider" the setting is different and there might be a slight confusion about where we actually need to use hostNetwork (for the daemonset vmware-vsphere-csi-driver-node it's actually needed). See https://kubernetes.slack.com/archives/C9PGCDKV5/p1683198355000799?thread_ts=1683038313.875139&cid=C9PGCDKV5 and my remark at the bottom.

**Version**
I've to admit I'm using openshift (version 4.12.9). But I don't this this was altered from the upstream okd version, right?

**How reproducible**
Try to assign EgressIP to the openshift-cluster-csi-drivers. The pods of the vmware-vsphere-csi-driver-controller will run with hostNetwork and per (our) firewall settings the access will not be allowed.

**Remark**
As I thought this would be present in the "upstream" project I started a thread in Kubernetes slack in #provider-vsphere .
Link: https://kubernetes.slack.com/archives/C9PGCDKV5/p1683198355000799?thread_ts=1683038313.875139&cid=C9PGCDKV5

**Comment by vrutkovs** [comment]
>I've to admit I'm using openshift (version 4.12.9). But I don't this this was altered from the upstream okd version, right?

If its not OKD-specific bug it probably should be reported to https://issues.redhat.com/browse/OCPBUGS

**Comment by guhilling** [comment]
Thanks for the info. I'll report with redhat!

**Comment by gnufied** [comment]
Yeah we are planning to remove `hostNetork:` from controller pods.. Please see - https://issues.redhat.com/browse/OCPBUGS-13084

**Comment by guhilling** [comment]
Ah, thanks a lot! Unfortunately I cannot see that issue. So I just created a duplicate https://issues.redhat.com/browse/OCPBUGS-13159
Will mark it as such and refer...
