### ISSUE TITLE
OKD4 GCP on shared VPC problem creating ingress LB

### ISSUE THREAD

**Issue by MarcoPereira7** [okd-project/okd#1596]
**Describe the bug**

While trying to install OKD4 on GCP on a shared VPC using IPI i noticed a bug where the installer creates an instance group with the name k8s-ig--<ramdom value> having both master nodes and worker nodes. This leads to an error on creating the ingress load balancer, since there is another instance group that is already using the master nodes. On GCP we cannot have the same instance associated with multiple instance groups and being used by multiple load balancers.

https://cloud.google.com/load-balancing/docs/backend-service#restrictions_and_guidance

With this i cannot succesfully create an OKD4 cluster on GCP. The only way i managed to get around this problem, was manually removing the master node machines from the instance group, and the ingress LB was succesfully created.

I have previously installed a private cluster on a GCP VPC and the expected behavior was the installer creating two instance groups:

One for the master nodes (where api server runs) and other for the worker nodes (where the ingress pods runs)

**Version**

I have reproduced this problem on the following versions:

- 4.12.0-0.okd-2023-04-01-051724
- 4.12.0-0.okd-2023-01-21-055900

**How reproducible**

Create an OKD4 into a shared VPC on GCP using the IPI method.
https://docs.okd.io/4.12/installing/installing_gcp/installing-gcp-shared-vpc.html

**Comment by vrutkovs** [comment]
Pretty sure it is not OKD-specific, please report this to https://issues.redhat.com/browse/OCPBUGS

**Comment by keremceliker** [comment]
Hey Marco,

Agree with Vadim @vrutkovs also here is my comment below,

Versions **4.12.0-0.okd-2023-04-01-051724** and **4.12.0-0.okd-2023-01-21-055900** are both affected by this issue. 
If you encounter this problem, I recommend reporting it to the appropriate channels, such as the [OCPBUGS issue tracker](https://issues.redhat.com/browse/OCPBUGS), as it may not be specific to OKD but rather a broader issue related to instance group management in GCP shared VPCs.

Kerem ÇELİKER
Head of Cloud Architecture
linkedin.com/in/keremceliker/
