### ISSUE TITLE
nodes always not ready when upgrade from 4.11 to 4.12 - no kubelet and ovs-configuration.service

### ISSUE THREAD

**Issue by garyyang85** [okd-project/okd#1615]
**Describe the bug**

I am upgrading okd from 4.11 to 4.12, it is Falling with notice "Cluster operators etcd, kube-apiserver are degraded". I found there are one master node and one work node in not ready status for more than 10 hours. Log in the not ready nodes, and found there is no kubelet and ovs-configuration sevice, some other basice binaries were also lost, like crictl and ovs related files under /usr/bin.
The mcp showed machince is unavailable.
No problem when upgrade from 4.10 to 4.11. 
**Version**

From 4.11.0-0.okd-2022-07-29-154152 to 4.12.0-0.okd-2023-03-18-084815
**How reproducible**

Upgrade from okd 4.11 to 4.12
**Log bundle**

**Comment by vrutkovs** [comment]
Please attach (or upload to the public file sharing service) [must-gather](https://docs.okd.io/latest/support/gathering-cluster-data.html#support_gathering_data_gathering-cluster-data) archive

**Comment by garyyang85** [comment]
[must-gather.tgz](https://github.com/okd-project/okd/files/11575468/must-gather.tgz)

**Comment by vrutkovs** [comment]
Kubelet `master02.taurus.eti.cdl.ibm.com` is not updating its status.

Can you ssh on it? If yes, please attach the output of `journalctl -b` from this node. If its unreachable see [replacing unhealthy node](https://docs.okd.io/4.13/backup_and_restore/control_plane_backup_and_restore/replacing-unhealthy-etcd-member.html)

**Comment by garyyang85** [comment]
[master-unready.log](https://github.com/okd-project/okd/files/11594951/master-unready.log)
[worker-unready.log](https://github.com/okd-project/okd/files/11594952/worker-unready.log)

**Comment by garyyang85** [comment]
Hello @vrutkovs , can you kindly help on this? Or some workarouds I can do is also appreciated.

**Comment by garyyang85** [comment]
Hello, could anyone give some advice on this issue? Thanks

**Comment by ascherbakov686** [comment]
Hello, the same problem, need help, respond

**Comment by vrutkovs** [comment]
Seems it boots into FCOS deployment, not FCOS+OKD binaries (so it can't find `ovs-vsctl`, `kubelet` or `crio` binaries). What's the output of `rpm-ostree status` on this node?

**Comment by imdmahajankanika** [comment]
@garyyang85 @vrutkovs I also faced the same issue. When I did ssh into the nodes, I found two services (kubelet.service and ovs-configuration.service) failed. I tried to restart kubelet service but I got an error "crio not found".

**Comment by garyyang85** [comment]
Hi @vrutkovs 
The rpm-ostree status response in broken master:
```
State: idle
Deployments:
● d34ff10be925c01aad7d088fa2dcc18aaa3e9d7ead12081a18fb6883a94385d7
                  Version: 37.20230218.3.0 (2023-03-06T20:02:24Z)

  pivot://quay.io/openshift/okd-content@sha256:a77c75b002aa480b9dc834a8c0cb38ccce347f528f1d27118c08da2bb2e199b1
             CustomOrigin: Managed by machine-config-operator
                  Version: 411.36.202207291018-0 (2022-07-29T10:22:03Z)
```
The rpm-ostree status response in broken worker:
```
State: idle
Deployments:
● d34ff10be925c01aad7d088fa2dcc18aaa3e9d7ead12081a18fb6883a94385d7
                  Version: 37.20230218.3.0 (2023-03-06T20:02:24Z)

  pivot://quay.io/openshift/okd-content@sha256:a77c75b002aa480b9dc834a8c0cb38ccce347f528f1d27118c08da2bb2e199b1
             CustomOrigin: Managed by machine-config-operator
                  Version: 411.36.202207291018-0 (2022-07-29T10:22:03Z)
```
Thanks very much for the help.

**Comment by vrutkovs** [comment]
Yeah, your current deployment in plain FCOS. You may want to boot into a previous one and let MCD upgrade it to 4.12 again

**Comment by garyyang85** [comment]
@vrutkovs Thanks for the reply. Is there a guide how can I "boot into a previous one"? Thanks.

**Comment by vrutkovs** [comment]
See https://docs.fedoraproject.org/en-US/fedora-coreos/manual-rollbacks/#_temporary_rollback

**Comment by garyyang85** [comment]
Thank you. Will have a try.

**Comment by garyyang85** [comment]
@vrutkovs after rollback, it runs into another issue https://access.redhat.com/solutions/5598401, after operation follow the workaround, it runs into the status in this issue again :(
