### ISSUE TITLE
4.13 upgrade --to-multi-arch doesn't seem to do anything

### ISSUE THREAD

**Issue by japhar81** [okd-project/okd#1631]
**Describe the bug**
Trying to move a pre-existing 4.13 cluster to multiarch, I ran `oc adm upgrade --to-multi-arch` per the docs. Status shows no changes, and the UI just flips to 'Available updates', but doesn't actually do anything. Selecting the available update in the UI just flips to 'Up to date', and nothing happens.

**Version**
4.13.0-0.okd-2023-06-04-080300 deployed to AWS via openshift-installer

**How reproducible**
100%, I've done it multiple times

**Comment by aleskandro** [comment]
Hello, there is no support for multi-arch compute clusters in OKD yet, unfortunately. We're working on that, but we should remove it from the doc until this becomes possible.

cc @kelbrown20

**Comment by vrutkovs** [comment]
Lets track multiarch in #1165
