### ISSUE TITLE
[AWS IPI][OKD 4.13] air-gapped installation fails during bootstrap - rpm-ostree not considering /etc/containers/registries.conf

### ISSUE THREAD

**Issue by dan1el-k** [okd-project/okd#1636]
**Describe the bug**
We tried installing OKD 4.13 in our same enterprise custom VPC setup as we did install from OKD 4.6 onwards.
The installation fails during the bootstrap phase.

Kubelet as well as etc-d failed according journalctl, neither api-server nor machine-config ports are open on the bootstrap node.
After digging through the install logs I cathed a suspicious error in the `release-image-pivot` service:

```yaml
Jun 15 21:34:00 ip-10-223-213-37 bootstrap-pivot.sh[1734]: ++ MACHINE_OS_IMAGE=quay.io/openshift/okd-content@sha256:a70ed62bcd842bd75806638a64afeac3e691922566e7f0c312c60c80845a4953
Jun 15 21:34:00 ip-10-223-213-37 bootstrap-pivot.sh[1734]: ++ chmod 0644 /etc/containers/registries.conf
Jun 15 21:34:00 ip-10-223-213-37 bootstrap-pivot.sh[1734]: ++ rpm-ostree rebase --experimental ostree-unverified-registry:quay.io/openshift/okd-content@sha256:a70ed62bcd842bd75806638a64afeac3e691922566e7f0c312c60c80845a4953
Jun 15 21:34:00 ip-10-223-213-37 bootstrap-pivot.sh[2566]: Pulling manifest: ostree-unverified-image:docker://quay.io/openshift/okd-content@sha256:a70ed62bcd842bd75806638a64afeac3e691922566e7f0c312c60c80845a4953
Jun 15 21:34:02 ip-10-223-213-37 bootstrap-pivot.sh[2566]: error: Preparing import: Fetching manifest: remote error: Get "https://cdn03.quay.io/sha256/5c/5c437aa03227b5db043e05544314b5484de60b9e5d9c4414d7daab20b2c7c5f2?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AAAAAAAAAA%2F20230615%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20230615T213402Z&X-Amz-Expires=600&X-Amz-SignedHeaders=host&X-Amz-Signature=82fd020e2326a5fbd2db160338fae49e170e06f047f1dcb8fc748b71e908fcd4&cf_sign=OD11kYKBm%2FQ5XDQ6tPPZ17b4sfhVtjOhuwtzQWX81n1PtOdYWflltjHOFogNgsGuriD4hwl6TDJXnvknmSzEXc7D8OOFE6E%2FLBoYzIsbRxonh6t4AR3VS7aBRKMPMvxTQ9XNO%2BM3fcUwBFlBUuEudQjmZ2E7Yw%2Bmkrx50VLdWqPIWCYk%2FjTp0QyOBxPOd7WqP5W2AzwhI83GdfICk6ngSBK7kRfOsOGpGdluWnnLPqW0oC6gCADuB4lsalrAE55ccnw4dGBqxln0PtB78cJVAeANVQ1bAu9B%2FQ2TRqKrJvUVt5CrhKjvxZawOhWZjdg6PHHKWck639Ps0ez0EzAlig%3D%3D&cf_expiry=1686865442&region=us-east-1": read tcp 10.1.1.37:53992->104.18.37.198:443: read: connection reset by peer
Jun 15 21:34:02 ip-10-223-213-37 bootstrap-pivot.sh[1734]: + record_service_exit 1
Jun 15 21:34:02 ip-10-223-213-37 bootstrap-pivot.sh[1734]: + '[' 1 -eq 0 ']'
Jun 15 21:34:02 ip-10-223-213-37 bootstrap-pivot.sh[1734]: + local RESULT=failure
Jun 15 21:34:02 ip-10-223-213-37 bootstrap-pivot.sh[1734]: + local ERROR_LINE
Jun 15 21:34:02 ip-10-223-213-37 bootstrap-pivot.sh[1734]: + local ERROR_MESSAGE
Jun 15 21:34:02 ip-10-223-213-37 bootstrap-pivot.sh[1734]: + get_error_info ERROR_LINE ERROR_MESSAGE
Jun 15 21:34:02 ip-10-223-213-37 bootstrap-pivot.sh[1734]: + local -n error_line=ERROR_LINE
Jun 15 21:34:02 ip-10-223-213-37 bootstrap-pivot.sh[1734]: + local -n error_message=ERROR_MESSAGE
Jun 15 21:34:02 ip-10-223-213-37 bootstrap-pivot.sh[2775]: ++ caller 1
Jun 15 21:34:02 ip-10-223-213-37 bootstrap-pivot.sh[1734]: + error_line='1 source ./pre-pivot.sh'
Jun 15 21:34:02 ip-10-223-213-37 bootstrap-pivot.sh[2776]: ++ journalctl --unit=release-image-pivot.service --lines=3 --output=cat
Jun 15 21:34:02 ip-10-223-213-37 bootstrap-pivot.sh[1734]: + error_message='++ caller 1
```

There are 2 question with this CDN endpoint:
1. When calling locally I get an "URL expired at Tue Jan 20 1970 12:34:25 GMT+0000 (Coordinated Universal Time)%  " error"
2. Why does the installer try to reach a public CDN endpoint, if we use the "private" installation method on AWS with IPI ? Was there introduce a change in this error in the latest releases?. We never had such an error, at least between OKD 4.6 and 4.11 releases

**Version**
AWS IPI air-gapped
4.13.0-0.okd-2023-06-04-080300 and 4.13.0-0.okd-2023-05-22-052007

**How reproducible**
100% reproducible

**Log bundle**

[log-bundle-20230615215243.tar.gz](https://github.com/okd-project/okd/files/11763681/log-bundle-20230615215243.tar.gz)

**Comment by dan1el-k** [comment]
I just found this: https://github.com/okd-project/okd/discussions/1539, which seems to be the same error already catched with OKD 4.12

**Comment by dan1el-k** [comment]
After digging deeper I think I can pinpoint the issue to the ´rpm-ostree` not taken into consideration `/etc/containers/registries.conf` (https://github.com/openshift/okd-machine-os/blob/master/bootstrap/pre-pivot.sh#L15).


Manual run on the bootstrap node gives the same picture:
```bash
[core@ip-10-223-214-58 core]$ sudo rpm-ostree rebase --experimental ostree-unverified-registry:quay.io/openshift/okd-content@sha256:a70ed62bcd842bd75806638a64afeac3e691922566e7f0c312c60c80845a4953
Pulling manifest: ostree-unverified-image:docker://quay.io/openshift/okd-content@sha256:a70ed62bcd842bd75806638a64afeac3e691922566e7f0c312c60c80845a4953
error: Preparing import: Fetching manifest: remote error: Get "https://cdn03.quay.io/sha256/5c/5c437aa03227b5db043e05544314b5484de60b9e5d9c4414d7daab20b2c7c5f2?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AAA%2F20230616%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20230616T124339Z&X-Amz-Expires=600&X-Amz-SignedHeaders=host&X-Amz-Signature=55541ef5aed7b7024dcb579f6117a808f8af9e6ce6f93adf5caca29ba521f736&cf_sign=O8oEqlSpeCtk7B2gv40D2jtamFA6wEsaALgHkhRabfjNPes2TFkWs9gRsNafuVU2KYLlUcmLTumjbFkTJJoxPyRWMdyG9rFOaaSsGGpR8c%2BU%2FDJUAAB7pG2JeEX37L7%2BNxmpZfxeOU6xMUzxuBrpDM%2FXJug%2Fd3NNCKyKwoQq1TRvphwBmBWAfTV6wH63iyxO%2BDab3qwEq1ElGFC1T7JCs4T4x6CuH5oCuJBsKOHAbzate989VLO%2FK9%2Bi%2Fm6kZVyY4Sy5RhxHV%2FfzFzfN3uS1YnRCO8cVL%2B9m5zP4K3dG0zr%2B6bKRFaqkKI%2F1JVuk04NieLplDAgg6rezQCjoUO0baA%3D%3D&cf_expiry=1686920019&region=us-east-1": read tcp 10.223.214.58:51486->172.64.150.58:443: read: connection reset by peer
```

We are using registry mirrors, so thats explains in case they are not used, why its blocked.
As a validation, we have opened the firewall for "*.quay.io" endpoints and since then, the full installation went through.
I also check the file `/etc/containers/registries.conf` which is correctly filled and looks ok (except it has no indention, but I am not sure if this is an issue)

**Comment by dan1el-k** [comment]
@vrutkovs any ideas how this can be fixed?

**Comment by MarkusNeuron** [comment]
Also we have the same issue with our cluster. We need to operate air-gapped but now need to open firewall for every cluster installation... 🥲 If you please have a look.

**Comment by dan1el-k** [comment]
> After digging deeper I think I can pinpoint the issue to the `rpm-ostree` not taken into consideration `/etc/containers/registries.conf` (https://github.com/openshift/okd-machine-os/blob/master/bootstrap/pre-pivot.sh#L15).
> 
> Manual run on the bootstrap node gives the same picture:
> 
> ```shell
> [core@ip-10-223-214-58 core]$ sudo rpm-ostree rebase --experimental ostree-unverified-registry:quay.io/openshift/okd-content@sha256:a70ed62bcd842bd75806638a64afeac3e691922566e7f0c312c60c80845a4953
> Pulling manifest: ostree-unverified-image:docker://quay.io/openshift/okd-content@sha256:a70ed62bcd842bd75806638a64afeac3e691922566e7f0c312c60c80845a4953
> error: Preparing import: Fetching manifest: remote error: Get "https://cdn03.quay.io/sha256/5c/5c437aa03227b5db043e05544314b5484de60b9e5d9c4414d7daab20b2c7c5f2?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AAA%2F20230616%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20230616T124339Z&X-Amz-Expires=600&X-Amz-SignedHeaders=host&X-Amz-Signature=55541ef5aed7b7024dcb579f6117a808f8af9e6ce6f93adf5caca29ba521f736&cf_sign=O8oEqlSpeCtk7B2gv40D2jtamFA6wEsaALgHkhRabfjNPes2TFkWs9gRsNafuVU2KYLlUcmLTumjbFkTJJoxPyRWMdyG9rFOaaSsGGpR8c%2BU%2FDJUAAB7pG2JeEX37L7%2BNxmpZfxeOU6xMUzxuBrpDM%2FXJug%2Fd3NNCKyKwoQq1TRvphwBmBWAfTV6wH63iyxO%2BDab3qwEq1ElGFC1T7JCs4T4x6CuH5oCuJBsKOHAbzate989VLO%2FK9%2Bi%2Fm6kZVyY4Sy5RhxHV%2FfzFzfN3uS1YnRCO8cVL%2B9m5zP4K3dG0zr%2B6bKRFaqkKI%2F1JVuk04NieLplDAgg6rezQCjoUO0baA%3D%3D&cf_expiry=1686920019&region=us-east-1": read tcp 10.223.214.58:51486->172.64.150.58:443: read: connection reset by peer
> ```
> 
> We are using registry mirrors, so thats explains in case they are not used, why its blocked. I also checked the file `/etc/containers/registries.conf` which is correctly filled and looks ok (except it has no indention, but I am not sure if this is an issue)
> 


@cgwalters: Could you please take a quick look and confirm if this is the case and `/etc/containers/registries.conf` is not considered by rpm-ostree for mirror/proxy repositories?

**Comment by cgwalters** [comment]
A big reason in fact that we architected things the way we did in rpm-ostree where it forks off `skopeo` as a subprocess is precisely because `skopeo` links in all the common tooling in the github.com/containers/image stack.

Does using `skopeo` work?

**Comment by JaimeMagiera** [comment]
Hi,

We are not working on FCOS builds of OKD any more. Please see these documents...

https://okd.io/blog/2024/06/01/okd-future-statement
https://okd.io/blog/2024/07/30/okd-pre-release-testing

Please test with the OKD SCOS nightlies and file a new issue as needed.

Many thanks,

Jaime
