### ISSUE TITLE
After upgrade to OKD 4.13, the kubelet service monitor shows target down on all hosts

### ISSUE THREAD

**Issue by joyartoun** [okd-project/okd#1640]
**Describe the bug**
After upgrading from 4.11.0-0.okd-2022-12-02-145640 -> 4.12.0-0.okd-2023-03-18-084815 -> 4.13.0-0.okd-2023-05-22-052007 the servicemonitor for kubelet shows target down on all hosts. 

![image](https://github.com/okd-project/okd/assets/29835230/68b41b46-cfd8-47a7-85fa-a3c208bf5c26)

I have commented before on the [discussion ](https://github.com/okd-project/okd/discussions/1626) but no answer there

Kubelet on all nodes print this
`Jun 21 12:14:55 master-1.<redacted> kubenswrapper[1508]: E0621 12:14:55.916154    1508 server.go:299] "Unable to authenticate the request due to an error" err="verifying certificate SN=271132308545303815804978568557672067097, SKID=, AKID=1E:94:4A:97:26:E8:A5:F5:27:FD:EF:60:E0:C4:B8:CC:F0:77:F1:08 failed: x509: certificate signed by unknown authority"
Jun 21 12:15:01 master-1.<redacted> kubenswrapper[1508]: E0621 12:15:01.548207    1508 server.go:299] "Unable to authenticate the request due to an error" err="verifying certificate SN=271132308545303815804978568557672067097, SKID=, AKID=1E:94:4A:97:26:E8:A5:F5:27:FD:EF:60:E0:C4:B8:CC:F0:77:F1:08 failed: x509: certificate signed by unknown authority"
Jun 21 12:15:04 master-1.<redacted> kubenswrapper[1508]: E0621 12:15:04.130941    1508 server.go:299] "Unable to authenticate the request due to an error" err="verifying certificate SN=271132308545303815804978568557672067097, SKID=, AKID=1E:94:4A:97:26:E8:A5:F5:27:FD:EF:60:E0:C4:B8:CC:F0:77:F1:08 failed: x509: certificate signed by unknown authority"
Jun 21 12:15:05 master-1.<redacted> kubenswrapper[1508]: E0621 12:15:05.677251    1508 server.go:299] "Unable to authenticate the request due to an error" err="verifying certificate SN=271132308545303815804978568557672067097, SKID=, AKID=1E:94:4A:97:26:E8:A5:F5:27:FD:EF:60:E0:C4:B8:CC:F0:77:F1:08 failed: x509: certificate signed by unknown authority"
Jun 21 12:15:05 master-1.<redacted> kubenswrapper[1508]: E0621 12:15:05.766893    1508 server.go:299] "Unable to authenticate the request due to an error" err="verifying certificate SN=271132308545303815804978568557672067097, SKID=, AKID=1E:94:4A:97:26:E8:A5:F5:27:FD:EF:60:E0:C4:B8:CC:F0:77:F1:08 failed: x509: certificate signed by unknown authority"`
**Version**
4.13.0-0.okd-2023-05-22-052007 

**How reproducible**
Not really sure. Maybe do the same upgrade path as described.

**Log bundle**
cannot send one as there is sensitive information in secrets

**What have i tried?**
* rebooting nodes one by one
* removing configmaps, specifically kubelet-serving-ca-bundle in the openshift-monitoring namespace so the operator recreates it
* removed secret kube-state-metrics-tls and let the operator recreate it.

**Comment by vrutkovs** [comment]
Please refrain from creating more issues. I've already spent time closing that one instead of looking into the must-gather
