### ISSUE TITLE
Release streams failing for 4.10, 4.11 and 4.12

### ISSUE THREAD

**Issue by lvlts** [okd-project/okd#1659]
**Describe the bug**

Several pull specs are no longer functioning (continously failing) over the past 7 weeks.

I'm referring to [https://amd64.origin.releases.ci.openshift.org/](https://amd64.origin.releases.ci.openshift.org/)

In particular, the following release streams are no longer up-to-date and always failing:

- [4.12.0-0.okd-scos](https://amd64.origin.releases.ci.openshift.org/#4.12.0-0.okd-scos)
- [4.12.0-0.okd](https://amd64.origin.releases.ci.openshift.org/#4.12.0-0.okd)
- [4.11.0-0.okd](https://amd64.origin.releases.ci.openshift.org/#4.11.0-0.okd)
- [4.10.0-0.okd](https://amd64.origin.releases.ci.openshift.org/#4.10.0-0.okd)

Other release streams (even older ones such as 4.9) are working.

**Version**
- [4.12.0-0.okd-scos](https://amd64.origin.releases.ci.openshift.org/#4.12.0-0.okd-scos)
- [4.12.0-0.okd](https://amd64.origin.releases.ci.openshift.org/#4.12.0-0.okd)
- [4.11.0-0.okd](https://amd64.origin.releases.ci.openshift.org/#4.11.0-0.okd)
- [4.10.0-0.okd](https://amd64.origin.releases.ci.openshift.org/#4.10.0-0.okd)

**How reproducible**
Navigate to the release status page: [https://amd64.origin.releases.ci.openshift.org/](https://amd64.origin.releases.ci.openshift.org/)

**Log bundle**
None

**Comment by vrutkovs** [comment]
Seems all of these are failing on post-install, before tests begin:
```
 [Fri Jul 14 00:18:42 UTC 2023] waiting for non-samples imagesteams to import...
[Fri Jul 14 00:18:42 UTC 2023] The following image streams are yet to be imported (attempt #1):
openshift/dotnet:3.1
openshift/dotnet:3.1-el7
openshift/dotnet-runtime:3.1
openshift/dotnet-runtime:3.1-el7 
```
For 4.14 and 4.13 it was removed in https://github.com/openshift/cluster-samples-operator/pull/485, so you may want to file a new bug at issues.redhat.com/ for OCP (component: samples operator) mentioning that OKD 4.12, 4.11 and 4.10 is still affected. The engineer will resync library for 4.12 and cherry-pick it as 4.11 and 4.10

**Comment by JaimeMagiera** [comment]
Hi,

We are not working on FCOS builds of OKD any more. Please see these documents...

https://okd.io/blog/2024/06/01/okd-future-statement
https://okd.io/blog/2024/07/30/okd-pre-release-testing

Please test with the OKD SCOS nightlies and file a new issue as needed.

Many thanks,

Jaime
