### ISSUE TITLE
OKD 4.13.0 IPI build errors

### ISSUE THREAD

**Issue by pzi123** [okd-project/okd#1684]
### Discussed in https://github.com/okd-project/okd/discussions/1673

<div type='discussions-op-text'>

<sup>Originally posted by **pzi123** July 30, 2023</sup>
Tried to install OKD 4.13.0 on vsphere. IPI failed unfortunately.  All build details are collected here https://github.com/pzi123/tmp/tree/main/4.13.0-error . The commands ran (RUNME) below. I would appreciate any feedback. As a  background on the vsphere I used I successfully built OKD cluster 4.8.57 in this environment with details on that installation here https://github.com/pzi123/tmp/tree/main/4.8.57-ok .

```
dig +noall +answer @10.31.0.1 api.okd2.p31.home.pzi.net
dig +noall +answer @10.31.0.1 api-int.okd2.p31.home.pzi.net
dig +noall +answer @10.31.0.1 console-openshift-console.apps.okd2.p31.home.pzi.net

here=`pwd`

cd ~/.ssh
ssh-add -D
ssh-add id_rsa
ssh-add -l

cd $here
rm -rf inst
mkdir inst
cp tmp/install-config.yaml inst

wget https://github.com/okd-project/okd/releases/download/4.13.0-0.okd-2023-07-23-051208/openshift-install-linux-4.13.0-0.okd-2023-07-23-051208.tar.gz
wget https://github.com/okd-project/okd/releases/download/4.13.0-0.okd-2023-07-23-051208/openshift-client-linux-4.13.0-0.okd-2023-07-23-051208.tar.gz

tar xvf openshift-install-linux-4.13.0-0.okd-2023-07-23-051208.tar.gz
#./openshift-install create cluster install-config --dir=inst
./openshift-install create cluster --log-level=debug --dir=inst 2>&1 | tee log.txt

grep -i error log.txt > errors.txt
```
</div>

**Comment by JaimeMagiera** [comment]
Hi,

We are not working on FCOS builds of OKD any more. Please see these documents...

https://okd.io/blog/2024/06/01/okd-future-statement
https://okd.io/blog/2024/07/30/okd-pre-release-testing

Please test with the OKD SCOS nightlies and file a new issue as needed.

Many thanks,

Jaime
