### ISSUE TITLE
CI config for latest 4-stable OKD release picked wrong base release

### ISSUE THREAD

**Issue by ars-admin** [okd-project/okd#1696]
**Describe the bug**
In the release status page for [4.13.0-0.okd-2023-08-04-164726](https://amd64.origin.releases.ci.openshift.org/releasestream/4-stable/release/4.13.0-0.okd-2023-08-04-164726) it shows a "failed" entry for a wrong base release (e.g. scos-based instead of fcos).

**Version**
4.13.0-0.okd-2023-08-04-164726

**How reproducible**
N/A

**Log bundle**
N/A

**Comment by ars-admin** [comment]
![grafik](https://github.com/okd-project/okd/assets/75731037/783f7755-b092-4428-984a-1f5d485d322d)

**Comment by kai-uwe-rommel** [comment]
Oops, accidentially used wrong Github account. Should have come from this one.
The above one is our org admin account.

**Comment by kai-uwe-rommel** [comment]
The same happened again for 4.13.0-0.okd-2023-08-18-135805.

**Comment by LorbusChris** [comment]
Should be fixed by https://github.com/openshift/release/pull/42843
