### ISSUE TITLE
Release Artifacts for 4.13.0-0.okd-2023-09-03-082426 are named 4.13.0-0.okd-2023-08-18-135805

### ISSUE THREAD

**Issue by CpuID** [okd-project/okd#1720]
**Describe the bug**

https://github.com/okd-project/okd/releases/tag/4.13.0-0.okd-2023-09-03-082426

The release artifacts on there used to be named after the tag respectively, but have now been changed (accidentally or intentionally?) to be `4.13.0-0.okd-2023-08-18-135805` - which is the previous release.

This is causing an issue trying to the use the "single node cluster" scripts - filed at https://github.com/crc-org/snc/issues/798

**Version**

4.13.0-0.okd-2023-09-03-082426

**How reproducible**

Visit https://github.com/okd-project/okd/releases/tag/4.13.0-0.okd-2023-09-03-082426 and look at the list of Assets.

**Log bundle**

N/A

**Comment by vrutkovs** [comment]
Sorry, I uploaded binaries for the previous release. Should be fixed now

**Comment by CpuID** [comment]
Thanks! much better :)
