### ISSUE TITLE
What's the deal with 4.13.0-0.okd-2023-09-03-112738

### ISSUE THREAD

**Issue by ibotty** [okd-project/okd#1723]
It's not listed in the releases.

**Comment by ibotty** [comment]
That's the question.  Two of my clusters listed this release as soon as the other one from 2023-09-03 had been installed.

**Comment by madpearl** [comment]
Now is Okay
oc adm upgrade
Cluster version is 4.13.0-0.okd-2023-09-03-082426

Upstream: https://amd64.origin.releases.ci.openshift.org/graph
Channel: stable-4
No updates available. You may force an upgrade to a specific release image, but doing so may not be supported and may result in downtime or data loss.`
`

**Comment by ibotty** [comment]
That's unfortunate for my test cluster that I already updated to 4.13.0-0.okd-2023-09-03-112738.  One node cannot pull some images now.

```
Sep 05 08:42:47 ... bash[6471]: Trying to pull registry.ci.openshift.org/origin/4.13-2023-09-03-112738@sha256:25919ca30f4a1d410b2301d191b8f268f131372da04c4646a45c1127c9492e22...
Sep 05 08:42:48 ... bash[6471]: Error: initializing source docker://registry.ci.openshift.org/origin/4.13-2023-09-03-112738@sha256:25919ca30f4a1d410b2301d191b8f268f131372da04c4646a45c1127c9492e22: reading manifest sha256:25919ca30f4a1d410b2301d191b8f268f131372da04c4646a45c1127c9492e22 in registry.ci.openshift.org/origin/4.13-2023-09-03-112738: received unexpected HTTP status: 500
```

**Comment by vrutkovs** [comment]
There are no breaking changes between these, so you can recover by "downgrading" back to stable

**Comment by ibotty** [comment]
That's harder if the kubelet on the node does not start.  I think I'll just reprovision the node.

**Comment by ssams** [comment]
> That's harder if the kubelet on the node does not start. 

Last time this problem occurred (#1433), I managed to get around some similar problems and recover such a broken cluster - the related discussion https://github.com/okd-project/okd/discussions/1435 would contain some hints that may be useful when you need to recover kubelet in this situation (i.e. in case reprovisioning is not an option).

**Comment by ibotty** [comment]
I'll close this.  There is nothing to do here afaict.
