### ISSUE TITLE
ClusterOperator network hung with 4.13.0-0.okd-2023-09-03-082426 update

### ISSUE THREAD

**Issue by shdwchn10** [okd-project/okd#1724]
**Describe the bug**
While upgrading OKD from 4.13.0-0.okd-2023-08-18-135805 to 4.13.0-0.okd-2023-09-03-082426, rollout of ClusterOperator `network` hung. I got these messages:
```
DaemonSet "/openshift-ovn-kubernetes/ovnkube-node" rollout is not making progress - last change 2023-09-05T04:56:48Z
DaemonSet "/openshift-ovn-kubernetes/ovnkube-node" update is rolling out (1 out of 3 updated)
```

Container `ovnkube-node` from `ovnkube-node-bw5ps` pod has following message in logs: `ovnkube.go:137] failed to start node network manager: failed to start default node network controller: error waiting for node readiness: unknown pid for ovn-controller process: open /var/run/ovn/ovn-controller.pid: no such file or directory`

**Version**
4.13.0-0.okd-2023-08-18-135805
Installed with Assisted Installer (Cluster-Managed Networking). 3 masters (no dedicated workers) in 3 VMs on single libvirt host.

**Log bundle**
https://drive.proton.me/urls/S6VM4XCAYC#TWDU4WjKXZnb

**Comment by vrutkovs** [comment]
Unhealthy ovnkube-node-bw5ps pod has
```
    policies.kyverno.io/last-applied-patches: |
      dockerhub-cache-pod-containers.dockerhub-cache.kyverno.io: added /spec/containers/4/volumeMounts/12
```
others don't have it.

Seems kyverno is interfering? Could you disable it for `openshift-*` namespaces to make sure faulty rules don't interfere with updates?
