### ISSUE TITLE
Possible Missing Release Image in quay.io Image Registry

### ISSUE THREAD

**Issue by nhenderson** [okd-project/okd#1740]
**Describe the bug**

The install of `4.13.0-0.okd-2023-09-03-082426` is failing for me. The error reports that the bootstrap machine cannot download a container image from quay.io. The image appears to be missing. I can confirm that I am able to login to the bootstrap machine via `ssh` and manually pull an existing image from the quay.io image registry. So, I've ruled out a networking or proxy problem. Please correct me if I'm wrong, but this image appears to be missing in the quay.io image registry:

```
...
reading manifest sha256:59b1e486ed132fa084f654ca930d84a751c7956870f659ef522a9928bc200ec7
in quay.io/openshift/okd: manifest unknown: manifest unknown
...
```

**Version**

I'm installing OKD release: [4.13.0-0.okd-2023-09-03-082426](https://github.com/okd-project/okd/releases/tag/4.13.0-0.okd-2023-09-03-082426) via the following command `openshift-install create cluster --dir="/builds/devops/provision-openshift/roles/clusters/test"`. 

**NOTE:** I'm allowing the `openshift-install` command to install my infrastructure for me in AWS. (I believe this is called the `IPI` installer)

**How reproducible**

I've run the install command above many times and am receiving the same error 100% of the time.

**Log bundle**

```
level=info msg=Credentials loaded from default AWS environment variables
level=info msg=Consuming Install Config from target directory
level=info msg=Creating infrastructure resources...
level=info msg=Waiting up to 20m0s (until 2:36PM) for the Kubernetes API at https://api.test.redacted.net:6443/...
level=info msg=Pulling VM console logs
level=info msg=Pulling debug logs from the bootstrap machine
level=error msg=Attempted to gather ClusterOperator status after installation failure: listing ClusterOperator objects: Get \"https://api.test.redacted.net:6443/apis/config.openshift.io/v1/clusteroperators\": dial tcp 44.219.203.123:6443: connect: connection refused
level=error msg=Bootstrap failed to complete: Get \"https://api.test.redacted.net:6443/version\": dial tcp 44.219.203.123:6443: connect: connection refused
level=error msg=Failed waiting for Kubernetes API. This error usually happens when there is a problem on the bootstrap host that prevents creating a temporary control plane.
level=error msg=The bootstrap machine failed to download the release image
level=info msg=Error: initializing source docker://quay.io/openshift/okd@sha256:59b1e486ed132fa084f654ca930d84a751c7956870f659ef522a9928bc200ec7: reading manifest sha256:59b1e486ed132fa084f654ca930d84a751c7956870f659ef522a9928bc200ec7 in quay.io/openshift/okd: manifest unknown: manifest unknown
level=info msg=Pull failed. Retrying quay.io/openshift/okd@sha256:59b1e486ed132fa084f654ca930d84a751c7956870f659ef522a9928bc200ec7...
level=info msg=Error: initializing source docker://quay.io/openshift/okd@sha256:59b1e486ed132fa084f654ca930d84a751c7956870f659ef522a9928bc200ec7: reading manifest sha256:59b1e486ed132fa084f654ca930d84a751c7956870f659ef522a9928bc200ec7 in quay.io/openshift/okd: manifest unknown: manifest unknown
level=info msg=Bootstrap gather logs captured here \"/builds/devops/provision-openshift/clusters/test/log-bundle-20230914143606.tar.gz
```

I suppose I can rollback to an earlier stable release, but I thought I would let you know about this issue. I appreciate your help and thank you for your time and efforts on this.

**Comment by vrutkovs** [comment]
Right, there is no `sha256:59b1e486ed...` image listed in the payload - so perhaps uploaded installer is invalid?

Could you check if installer extracted from the payload works? `oc adm release extract --command=openshift-install --from=quay.io/openshift/okd:4.13.0-0.okd-2023-09-03-082426`

**Comment by vrutkovs** [comment]
Hmm, I'll need to reupload the files attached to the release then

**Comment by vrutkovs** [comment]
Files reuploaded, installer now points to existing release
