### ISSUE TITLE
4.13.0-0.okd-2023-09-03-082426 "Shutdown Guest OS" stuck on workers

### ISSUE THREAD

**Issue by engineater** [okd-project/okd#1748]
**Describe the bug**
Shutdown worker virtual machines  is stuck with messages:
<img width="959" alt="image" src="https://github.com/okd-project/okd/assets/49279754/e0465503-6159-4b44-8f3c-2b7e65296a2d">

Strange things: workers with Prometheus or/and Ingress Controllers Shutdown Guest OS fine.

**Version**
4.13.0-0.okd-2023-09-03-082426

**How reproducible**
Do not remove or drain worker node from k8s cluster.
Try to shutdown worker node gently in Cloud system. 
For example in vSphere: Mouse Right Click -> Power -> Shutdown Guest OS.

**Comment by vrutkovs** [comment]
That sounds more like a FCOS issue, would you mind refiling this at https://github.com/coreos/fedora-coreos-tracker/?
