### ISSUE TITLE
The Worker Node becomes NotReady intermittently due to CPU reaching 100%

### ISSUE THREAD

**Issue by wayne-cec** [okd-project/okd#1757]
**Platform**
VMware vSphere 7.0.3

**Describe the bug**

This issue occurs multiple times across various platforms. The occurrence of the fault is unpredictable and typically happens once every few months. Even in newly installed clusters without any additional user Pods running, such faults can occur.

The Pods running on the node are in a terminating state, and they cannot complete the termination process and be deleted automatically.

Following the occurrence of the fault, upon checking in the vCenter interface, it is observed that the CPU utilization of the affected VM is close to 100%. Subsequently, network connectivity is lost, and the VM's IP address is is lost. After restarting the VM, it sometimes immediately transitions to a "ready" status, while at other times, it may take a significant amount of time to become "ready" (e.g., several hours).
![NodeNotReady](https://github.com/okd-project/okd/assets/64525646/2f7019db-1686-4b6d-b5fe-063624674408)
![CPU 100%](https://github.com/okd-project/okd/assets/64525646/42a020d9-8132-4061-bd5f-e56eaca66243)
![CPU 100%-2](https://github.com/okd-project/okd/assets/64525646/14a18588-934f-4168-8b1f-b6f11ceca1ab)
![NodeNotReady-2](https://github.com/okd-project/okd/assets/64525646/df435bb8-f74d-42eb-acf2-d092328c2a26)

**Version**

UPI installed: 4.9.0-0.okd-2022-01-29-035536
IPI installed： 4.9.0-0.okd-2021-11-28-035710
UPI installed： 4.10.0-0.okd-2022-03-07-131213

**How reproducible**

The fault appears intermittently and is difficult to reproduce manually.

**Log bundle**

https://drive.google.com/file/d/1rkYW_rtUdLmul7ese10n_kbPmOxbex3E/view?usp=drive_link

**Comment by vrutkovs** [comment]
Is it reproducible on 4.13 or 4.12?

**Comment by wayne-cec** [comment]
@vrutkovs I'm not sure because we haven't upgraded to 4.13 or 4.12 yet. Do you know if earlier versions had this bug?

**Comment by wayne-cec** [comment]
It should be different because there are no additional cron jobs running in my cluster.

**Comment by wayne-cec** [comment]
The 100% CPU load is caused by the kubelet process, and this is quite similar.

**Comment by vrutkovs** [comment]
Right, that's a dupe most likely
