### ISSUE TITLE
ovn-kube-node crash-loops in update to 4.13.0-0.okd-2023-05-22-052007

### ISSUE THREAD

**Issue by ibotty** [okd-project/okd#1760]
**Describe the bug**

The `ovnkube-node` ds does not rollout.
```
ovnkube-node-5xcpc     3/5     CrashLoopBackOff    8 (13s ago)    16m18s
```

The describe says that container `ovn-kube-node` has

```
    State:       Waiting
      Reason:    CrashLoopBackOff
    Last State:  Terminated
      Reason:    Error
      Message:   sbin/iptables -t mangle -C OVN-KUBE-ITP -p TCP -d <nil> --dport 110 -j MARK --set-xmark 0x1745ec --wait]: e
xit status 2: iptables v1.8.7 (nf_tables): host/network `<nil>' not found
```

and the `ovn-controller` has
```
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Completed
      Exit Code:    0
```

**Version**
`4.12.0-0.okd-2023-04-01-051724` to `4.13.0-0.okd-2023-05-22-052007` on bare metal UPI.

**How reproducible**
always.  After deleting the pod the newly created pod has the same symptoms.

**Log bundle**
https://send.vis.ee/download/a215b5bf7b6eaab7/#lLphvJFSmv0NZXyptZJwZQ

**Comment by ibotty** [comment]
Anything I can do to debug?

**Comment by ibotty** [comment]
Investigating further, this was due to a service of type `ClusterIP`, that had `internalTrafficPolicy: Local`, which arguably does not make sense.

**Comment by vrutkovs** [comment]
Good catch! That still looks like a bug worth filing to https://issues.redhat.com - OVN should not crash when a bad service is created

**Comment by ibotty** [comment]
I filed <https://issues.redhat.com/browse/OCPBUGS-21925>.  I do think that the best fix would be to do both: not crash **and** don't allow these nonsensical services.
