### ISSUE TITLE
okd 4.13 Memory and CPU utilization not visible in web interface.

### ISSUE THREAD

**Issue by balait4** [okd-project/okd#1771]
Hi,

In okd 4.13 ( 4.13.0-0.okd-2023-05-22-052007 ), 
Not able to see the Memory/CPU utilization of any pods in web interface and also it stopped working all of sudden from Oct 17th. Please find the must-gather logs. Please help on this. 
https://drive.google.com/file/d/1R6sewjkr1tXVGKOFixX_ZL8dJwU7KZkW/view?usp=drive_link

```
$ kubectl top pods
error: Metrics not available for pod cp3o/cp3o-dc-284-2rnxb, age: 775h49m13.719255s
```
Thanks

**Comment by vrutkovs** [comment]
thanos-querier is not responding
>2023-10-27T14:11:58.539607981Z level=info ts=2023-10-27T14:11:58.539553446Z caller=endpointset.go:415 component=endpointset msg="removing endpoint because 
     it's unhealthy or does not exist" address=10.131.1.49:10901 extLset="{prometheus=\"openshift-monitoring/k8s\", prometheus_replica=\"prometheus-k8s-0\"}"

Its last line is:
>2023-10-27T15:02:06.072147239Z I1027 15:02:06.072087       1 log.go:198] http: proxy error: context canceled

That means apiserver is not responding in time. Its seems it takes a while to write anything:
>2023-10-27T14:54:48.840748440Z I1027 14:54:48.840514      15 trace.go:219] Trace[1483202627]: "Update" accept:application/json, */*,audit-id:7511c29c-25f5-4a50-9570-d51f1496fdf3,client:116.203.158.128,protocol:HTTP/2.0,resource:roles,scope:resource,url:/apis/rbac.authorization.k8s.io/v1/namespaces/openshift-monitoring/roles/prometheus-k8s-config,user-agent:operator/v0.0.0 (linux/amd64) kubernetes/$Format,verb:PUT (27-Oct-2023 14:54:48.248) (total time: 591ms):

and that comes from etcd being too busy:
>{"level":"warn","ts":"2023-10-27T14:48:21.265Z","caller":"etcdserver/util.go:166","msg":"apply request took too long","took":"229.972998ms","expected-duration":"200ms","prefix":"read-only range ","request":"key:\"/kubernetes.io/services/specs/\" range_end:\"/kubernetes.io/services/specs0\" ","response":"range_response_count:520 size:592128"}

and

>{"level":"warn","ts":"2023-10-27T15:15:57.561Z","caller":"fileutil/purge.go:72","msg":"failed to lock file","path":"/var/lib/etcd/member/wal/000000000001ba27-000000004925bfa4.wal","error":"fileutil: file already locked"}

Check that etcd disks are fast enough?
