### ISSUE TITLE
OCPBUGS-22293: upgrade from 4.13 2023-09-30 to 2023-10-28 stuck on network CO because of ovnkube-master DS preStop

### ISSUE THREAD

**Issue by kai-uwe-rommel** [okd-project/okd#1775]
**Describe the bug**
The upgrade is stuck at the network cluster operator. It looks like it cannot update ovnkube-master. The error message is:
`Error while updating operator configuration: could not apply (apps/v1, Kind=DaemonSet) openshift-ovn-kubernetes/ovnkube-master: failed to apply / update (apps/v1, Kind=DaemonSet) openshift-ovn-kubernetes/ovnkube-master: DaemonSet.apps "ovnkube-master" is invalid: [spec.template.spec.containers[0].lifecycle.preStop: Required value: must specify a handler type, spec.template.spec.containers[1].lifecycle.preStop: Required value: must specify a handler type, spec.template.spec.containers[3].lifecycle.preStop: Required value: must specify a handler type]`

**Version**
OKD 4.13 2023-09-30 to 2023-10-28

**How reproducible**
happened right now on upgrade of first cluster

**Log bundle**
Will create one.

**Comment by kai-uwe-rommel** [comment]
Apparently, the problem is already known:
https://issues.redhat.com/browse/OCPBUGS-22293

**Comment by llomgui** [comment]
Hello,

Same error here during an upgrade from 4.13.0-0.okd-2023-09-30-084937 to 4.13.0-0.okd-2023-10-28-065448

**Comment by madpearl** [comment]
I get the same error

**Comment by kai-uwe-rommel** [comment]
I have heard from someone else that he upgraded the same step without problem.
But that cluster was much younger (installed in spring 2023). 
While the one I reported from here was initially installed in February 2021 with OKD 4.6 ...

**Comment by kai-uwe-rommel** [comment]
I compared the configs of the ovnkube-master DS of both clusters and found that this newer and unaffected cluster did not have any lifecycle.prestop branches in this. I removed these (three of these) from the ovnkube-master DS on my affected cluster and then the CNO progressed and completed the upgrade.

**Comment by llomgui** [comment]
@kai-uwe-rommel Can you provide the yaml of the unaffected cluster?

**Comment by kai-uwe-rommel** [comment]
My cluster upgraded now successfully.
All you need to do is:
`oc edit ds ovnkube-master -n openshift-ovn-kubernetes`
and remove three occurrences of lifecycle.prestop branches in the YAML.

**Comment by kai-uwe-rommel** [comment]
Here is a diff of this object. Remove only the three "preStop:" branches and ignore (do not touch) the other changes.
`--- ovnkube-master.devqs	Mon Oct 30 17:24:18 2023
+++ ovnkube-master.txt	Mon Oct 30 17:24:05 2023
@@ -75,15 +75,8 @@
         env:
         - name: OVN_LOG_LEVEL
           value: info
-        image: quay.io/openshift/okd-content@sha256:e01396608ecddfdf34b5639900115c7510c173744b4ad7d031bc7177472a1ae4
+        image: quay.io/openshift/okd-content@sha256:26786007ba238a6ecd2d16318a56628e370407fffc58d104a4162d5704ce0888
         imagePullPolicy: IfNotPresent
-        lifecycle:
-          preStop:
-            exec:
-              command:
-              - /bin/bash
-              - -c
-              - OVN_MANAGE_OVSDB=no /usr/share/ovn/scripts/ovn-ctl stop_northd
         name: northd
         resources:
           requests:
@@ -283,23 +276,13 @@
                 if [ "${ipsec}" == "true" ]; then
                     # IBMCloud does not forward ESP (IP proto 50)
                     # Instead, force IBMCloud IPsec to always use NAT-T
-                    if [ "VSphere" == "IBMCloud" ]; then
+                    if [ "None" == "IBMCloud" ]; then
                         ipsec_encapsulation=true
                     fi
                 fi
                 if ! retry 20 "ipsec" "${OVN_NB_CTL} set nb_global . ipsec=${ipsec} options:ipsec_encapsulation=${ipsec_encapsulation}"; then
                   exit 1
                 fi
-          preStop:
-            exec:
-              command:
-              - /bin/bash
-              - -c
-              - |
-                echo "$(date -Iseconds) - stopping nbdb"
-                /usr/share/ovn/scripts/ovn-ctl stop_nb_ovsdb
-                echo "$(date -Iseconds) - nbdb stopped"
-                rm -f /var/run/ovn/ovnnb_db.pid
         name: nbdb
         ports:
         - containerPort: 9641
@@ -553,20 +536,10 @@
                 fi
 
                 # Kill some time while the cluster converges by checking IPsec status
-                OVN_SB_CTL="ovn-sbctl -p /ovn-cert/tls.key -c /ovn-cert/tls.crt -C /ovn-ca/ca-bundle.crt --db "ssl:193.149.37.20:9642,ssl:193.149.37.21:9642,ssl:193.149.37.71:9642""
+                OVN_SB_CTL="ovn-sbctl -p /ovn-cert/tls.key -c /ovn-cert/tls.crt -C /ovn-ca/ca-bundle.crt --db "ssl:10.101.0.113:9642,ssl:10.101.0.111:9642,ssl:10.101.0.112:9642""
                 if ! retry 20 "ipsec" "${OVN_SB_CTL} get sb_global . ipsec"; then
                   exit 1
                 fi
-          preStop:
-            exec:
-              command:
-              - /bin/bash
-              - -c
-              - |
-                echo "$(date -Iseconds) - stopping sbdb"
-                /usr/share/ovn/scripts/ovn-ctl stop_sb_ovsdb
-                echo "$(date -Iseconds) - sbdb stopped"
-                rm -f /var/run/ovn/ovnsb_db.pid
         name: sbdb
         ports:
         - containerPort: 9642
`

**Comment by llomgui** [comment]
Thank you!

I had to manually force delete "terminating" ovnkube-master pods after the DS modification to continue the update.

Still ongoing...

**Comment by alishchytovych** [comment]
@llomgui you just need to wait a bit until pods get synchronized. After that update will continue...

**Comment by kai-uwe-rommel** [comment]
It does, BTW, not help to remove the lifecycle.preStop entries in advance of the upgrade. The old CNO puts them back in. One must run into the problem and fix it then.

**Comment by kai-uwe-rommel** [comment]
It is quite mysterious. I just upgraded a cluster that was on the exact same version like the cluster for which I opened this issue with the problem. I checked in advance and it had the preStop entries. Nevertheless, the upgrade went through without any problem.

**Comment by alishchytovych** [comment]
> It is quite mysterious. I just upgraded a cluster that was on the exact same version like the cluster for which I opened this issue with the problem. I checked in advance and it had the preStop entries. Nevertheless, the upgrade went through without any problem.

The same here. But the new cluster was installed later from the different AMIs (AWS).

**Comment by kai-uwe-rommel** [comment]
Seems to be solved in later versions.
