### ISSUE TITLE
Error updating node status

### ISSUE THREAD

**Issue by balait4** [okd-project/okd#1779]
Hi, 
This is related to the same issue https://github.com/okd-project/okd/issues/1758.

Again Today I got the same issue. Here is the must gather log
https://drive.google.com/file/d/1CBWgyc2CYCIbJ_O2sRQ7yx2UuQn3-Ce_/view?usp=sharing

I don't see any network outages, similar setup in dev and test cluster don't have this issue.. Only happening on my Prod env, So confused what could be the issue. Also its happening randomly on any day. But only on the set of worker nodes. So what can I collect or what troubleshooting steps can be tried during issue time. Or any can be monitored? Appreciate your input on this please.

**Comment by vrutkovs** [comment]
Closing as duplicate

**Comment by balait4** [comment]
ok thanks @vrutkovs . I thought that issue was closed and you will not get to know if I update the closed issue.
