### ISSUE TITLE
4.14 VMWare/IPI install: FATAL failed to fetch Terraform Variables: failed to generate asset "Terraform Variables": network '/TS-vRA/VLAN2506' not found

### ISSUE THREAD

**Issue by dkoci** [okd-project/okd#1780]
I tried to install 4.14 OKD (VMWare/IPI) but got `FATAL failed to fetch Terraform Variables: failed to generate asset "Terraform Variables": network '/TS-vRA/VLAN2506' not found`. **4.13 install works fine**.

I used `openshift-install create install-config`. The installer connected to my VMWare and as you can see I chose the correct network
<img width="629" alt="Screenshot 2023-11-03 at 14 28 45" src="https://github.com/okd-project/okd/assets/5565897/55e78186-ee99-49e6-9ae1-d06f48199ae1">

Snippet from my install-config.yaml
<img width="629" alt="Screenshot 2023-11-03 at 14 37 29" src="https://github.com/okd-project/okd/assets/5565897/e271fb6f-b003-4809-ad8f-3f3c297676b1">

**Comment by jcpowermac** [comment]
can you provide the `.openshift-install.log` please

**Comment by dkoci** [comment]
> can you provide the `.openshift-install.log` please

[openshift_install.log](https://github.com/okd-project/okd/files/13252078/openshift_install.log)

**Comment by dkoci** [comment]
It is a bug: https://issues.redhat.com/browse/OCPBUGS-23376

Redhat engineering has fixed this issue and the code will be included in the 4.15 release.  They found an issue caused by the double slashes in the resource pool field.

**Comment by vrutkovs** [comment]
Lets close this as not OKD-specific? It would be picked up automatically in next stable OKD once https://github.com/openshift/installer/pull/7759 merges

**Comment by jcpowermac** [comment]
@dkoci were you able to confirm? I know QE reached out to the support engineer for you to test.

**Comment by jcpowermac** [comment]
@vrutkovs yeah I think we can close
