### ISSUE TITLE
release=4.14.0-0.okd-2023-10-28-073550 ---  * illegal base64 data at input byte 0 on bootstrap

### ISSUE THREAD

**Issue by vrutkovs** [okd-project/okd#1786]
### Discussed in https://github.com/okd-project/okd/discussions/1784

<div type='discussions-op-text'>

<sup>Originally posted by **rlaflamme** November  5, 2023</sup>
Hi,
I successfully upgraded to the latest 4.13.0-0.okd-2023-10-28-065448 but when I try to upgrade to 
release 4.14.0-0.okd-2023-10-28-073550,  the bootstrap is stuck when starting the bootkube.sh. with this error

 bootkube.sh[3227]:         * illegal base64 data at input byte 0

Nov 05 22:48:09 okd4-bootstrap podman[3215]: 2023-11-05 22:48:09.730105194 +0000 UTC m=+0.043402740 container remove 5789703e4851350c17d383e231c30261f7037105956bcd2f85921c86c1ae7616 (image=quay.io/openshift/okd@sha256:7a6200e347a1b857e47f2ab0735eb1303af7d796a847d79ef9706f217cd12f5c, name=amazing_mayer, io.openshift.release=4.14.0-0.okd-2023-10-28-073550, io.openshift.release.base-image-digest=sha256:068639a8d5ffd7b2e15ee974851875c87b008366fb62a88a32d250ad981c8b47)
Nov 05 22:48:09 okd4-bootstrap bootkube.sh[3227]: error: 1 error occurred:
Nov 05 22:48:09 okd4-bootstrap bootkube.sh[3227]:         * illegal base64 data at input byte 0
Nov 05 22:48:09 okd4-bootstrap systemd[1]: bootkube.service: Main process exited, code=exited, status=1/FAILURE
Nov 05 22:48:09 okd4-bootstrap systemd[1]: bootkube.service: Failed with result 'exit-code'.
Nov 05 22:48:09 okd4-bootstrap audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=bootkube comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
Nov 05 22:48:09 okd4-bootstrap systemd[1]: bootkube.service: Consumed 1.495s CPU time.
Nov 05 22:48:09 okd4-bootstrap systemd[1]: var-lib-containers-storage-overlay.mount: Deactivated successfully.

</div>

**Comment by vrutkovs** [comment]
```
Nov 07 13:15:22 okd4-bootstrap bootkube.sh[156414]: ++ oc adm release info -o 'jsonpath={.metadata.version}' '' quay.io/openshift/okd@sha256:7a6200e347a1b857e47f2ab0735eb1303af7d796a847d79ef9706f217cd12f5c
Nov 07 13:15:22 okd4-bootstrap bootkube.sh[156414]: error: 1 error occurred:
Nov 07 13:15:22 okd4-bootstrap bootkube.sh[156414]:         * illegal base64 data at input byte 0
```
that seems to be an oc bug

**Comment by KIgnas** [comment]
We had the same issue and it turned out to be a malformed docker config file (specifically we used to pass an invalid pullSecret configuration when installing Openshift). Previous versions of oc did not use to validate it, but the one shipped with 4.14 does.

Since we don't need a custom pullSecret, we have changed the line in install config to this and it started working again:
`pullSecret: '{"auths":{"foo":{"auth": ""}}}'`

**Comment by vrutkovs** [comment]
Right, it was incorrectly fortmatted pullsecret it seems. Empty or `aWQ6cGFzcwo=` auth is recommended (some previous guides used `bar` which will cause this error)

**Comment by zubanst** [comment]
The latest version doesn't work with this workaround. I even pulled the secret key from RH as advised in the official OKD4 guide and the bootstrap won't start. I am really looking for a working install-config.yaml file.

**Comment by vrutkovs** [comment]
Please file a new bug with [log bundle](https://docs.okd.io/latest/installing/installing-troubleshooting.html#installation-bootstrap-gather_installing-troubleshooting) linked
