### ISSUE TITLE
HTTPS Redirect Using Non-Standard HTTP Code

### ISSUE THREAD

**Issue by jabbate19** [okd-project/okd#1849]
**Describe the bug**
HTTPS redirects done by an OKD Route use a 302 HTTP Code, where the standard appears to be 301. This small change doesn't matter for most browsers, but results in an error if you have an HTTPS-only mode enabled on your browser.

Example error:
![image](https://github.com/okd-project/okd/assets/40615740/ed70794e-2aa8-45fb-a67f-c09a4d8eb4d8)

OKD Redirect:
![Screenshot 2024-01-08 at 6 23 17 PM](https://github.com/okd-project/okd/assets/40615740/821b9df8-daca-4ed3-971d-c02851fdb913)

Proper Redirect:
![Screenshot 2024-01-08 at 6 23 58 PM](https://github.com/okd-project/okd/assets/40615740/4b1fa559-b072-48ee-b5e7-8f11a05ced8b)

**Version**
4.13.0-0.okd-2023-10-28-065448

**How reproducible**
Create a secure route with edge/redirect options and this will occur.

**Log bundle**
N/A

**Comment by vrutkovs** [comment]
Please attach (or upload to the public file sharing service) [must-gather](https://docs.okd.io/latest/support/gathering-cluster-data.html#support_gathering_data_gathering-cluster-data) archive

**Comment by jabbate19** [comment]
https://drive.google.com/file/d/1Ps2PC4Vl5s2pTGyXzB_XJcLlxdjrJlgm/view?usp=sharing

**Comment by vrutkovs** [comment]
That seems to affect OCP as well, please file this in https://issues.redhat.com/projects/OCPBUGS
