### ISSUE TITLE
bootstraper fails to start container for installation

### ISSUE THREAD

**Issue by oe3gwu** [okd-project/okd#1857]
**Describe the bug**
I am using the RedHat OCP4 Helper node and also try to bootstrap via the Ansible scripts to a vsphere cluster. This works well. But when the bootstraper boots up, the installation hangs at this window:

![image](https://github.com/okd-project/okd/assets/17622063/36431d78-a33d-4c23-b06d-bb943dca1210)

The bootstrap vm seems booted without error:

![image](https://github.com/okd-project/okd/assets/17622063/bb81477d-f927-4e33-abc3-d911f6f0d5ec)

But the control-plane vm's cannot install.

![image](https://github.com/okd-project/okd/assets/17622063/745fc258-e3c6-4a90-ba0c-4421d0051ce0)

DNS entries are correct.

![image](https://github.com/okd-project/okd/assets/17622063/106aa61a-2e14-4f4c-b283-a2dcdbf22b38)

![image](https://github.com/okd-project/okd/assets/17622063/994ec1b6-880d-4cd3-91b3-552d35b27c12)

I found out that the podman services (bootkube) tries to start the init containers, and then simply dies. I can pull the container using root manually though and start it. Therefore also the DNS entries of the bootstrapper are correct.

![image](https://github.com/okd-project/okd/assets/17622063/db088aae-1452-4349-b564-a4b370bfb4cd)

Pulling logs out of the VM is a little a challenge, so I havent added text files.

**Version**
I tried with 4.10 and 4.13

**How reproducible**
100% reproducable by starting the installation via ansible scripts on my system.

**Log bundle**
Cant create oc logs because system isnt up yet.

**Comment by vrutkovs** [comment]
Please attach [log bundle](https://docs.okd.io/latest/installing/installing-troubleshooting.html#installation-bootstrap-gather_installing-troubleshooting)

**Comment by oe3gwu** [comment]
Attached. Thanks!
[log-bundle-20240113165011.tar.gz](https://github.com/okd-project/okd/files/13928673/log-bundle-20240113165011.tar.gz)

**Comment by melledouwsma** [comment]
From release-image.log:

```
Jan 13 15:41:26 bootstrap.okd.okd.local systemd[1]: Starting release-image.service - Download the OpenShift Release Image...
Jan 13 15:41:32 bootstrap.okd.okd.local podman[1956]: 2024-01-13 15:41:32.784600221 +0000 UTC m=+4.847285019 system refresh
Jan 13 15:41:32 bootstrap.okd.okd.local release-image-download.sh[1863]: Pulling quay.io/openshift-release-dev/ocp-release@sha256:05ba8e63f8a76e568afe87f182334504a01d47342b6ad5b4c3ff83a2463018bd...
Jan 13 15:42:29 bootstrap.okd.okd.local release-image-download.sh[2160]: d3e740b44b787a88c9ab2755c60ce03d7412e591ac71864a7ce31a90ee206df9
Jan 13 15:42:29 bootstrap.okd.okd.local podman[2160]: 2024-01-13 15:42:29.265415652 +0000 UTC m=+56.178203945 image pull d3e740b44b787a88c9ab2755c60ce03d7412e591ac71864a7ce31a90ee206df9 quay.io/openshift-release-dev/ocp-release@sha256:05ba8e63f8a76e568afe87f182334504a01d47342b6ad5b4c3ff83a2463018bd
Jan 13 15:42:29 bootstrap.okd.okd.local systemd[1]: Finished release-image.service - Download the OpenShift Release Image.
```

Are you sure you're using the client tools (oc and installer) from https://github.com/okd-project/okd/releases? This looks like an OCP installation.

**Comment by oe3gwu** [comment]
I have to check it. I use the OCP4 Helper node, yes, but otherwise I am using an ansible script from a friend. Maybe there is a bug. I check on Tuesday. Not at home currently.

**Comment by horvaro** [comment]
Having the same issue here with OKD 4.14.0

- Bootstrap starts
- `journalctl -b -f -u release-image.service -u bootkube.service`
  - [...] container create [...] image=quay.io/openshift/okd
  - [...] container init [...] image=quay.io/openshift/okd
  - [...] container start [...] image=quay.io/openshift/okd
  - [...] container attach [...] image=quay.io/openshift/okd
  - modest_lovelace[48516]: quay.io/openshift/okd-content@sha256:7df1a8d75db145a9f761e1de429d209dc73b21291d791082fa9fbb37231f0dcf
  - [...] container died [...] image=quay.io/openshift/okd

This comes over and over again. DNS entries are there and correct. Networking is wired up correctly.

- fedora-coreos-38.20231027.3.2-metal.x86_64
- openshift-client-linux-4.14.0-0.okd-2024-01-06-084517
- openshift-install-linux-4.14.0-0.okd-2024-01-06-084517

**Comment by oe3gwu** [comment]
For me, I use OCP4 Helper node and a modified OCP Vsphere Ansible Script. It seems that there still are some OCP Elements in there. But still, as far as I saw it still should work, because the Bootstrapper dies when starting a Pod that I manually can start.
