### ISSUE TITLE
Upgrade from 4.13.0-0.okd-2023-10-28-065448 to 4.14.0-0.okd-2024-01-06-084517 stuck on network CO because of ovnkube-node DS image required value and hostPort duplicate value

### ISSUE THREAD

**Issue by MarkusLandau** [okd-project/okd#1866]
**Describe the bug**
The upgrade is stuck at the network cluster operator. It looks like it cannot update ovnkube-node. The error message is:

`Error while updating operator configuration: could not apply (apps/v1, Kind=DaemonSet) openshift-ovn-kubernetes/ovnkube-node: failed to apply / update (apps/v1, Kind=DaemonSet) openshift-ovn-kubernetes/ovnkube-node: DaemonSet.apps "ovnkube-node" is invalid: [spec.template.spec.containers[2].image: Required value, spec.template.spec.containers[5].image: Required value, spec.template.spec.containers[3].ports[0].hostPort: Duplicate value: "TCP//9103", spec.template.spec.containers[9].ports[0].hostPort: Duplicate value: "TCP//29103"]
`

**Version**
4.13.0-0.okd-2023-10-28-065448 to 4.14.0-0.okd-2024-01-06-084517

**How reproducible**
The error has already occurred once when attempting to upgrade to 4.14.0-0.okd-2023-11-14-101924. The upgrade process was therefore canceled and a new release was waited for. And now again when attempting to upgrade to 4.14.0-0.okd-2024-01-06-084517. 
Note: The cluster is a long-running one, that means numerous upgrades have already been carried out.

**Log bundle**
[Download page for log bundle](https://my.hidrive.com/lnk/tRClnBOe)

**Comment by vrutkovs** [comment]
Right, its definitely a dupe then, lets continue there if the upgrade fails
