### ISSUE TITLE
Upgrading to 4.15.0-0.okd-2024-01-27-070424 leaves all pods resolving DNS queries relative to cluster domain

### ISSUE THREAD

**Issue by bstinsonmhk** [okd-project/okd#1871]
**Describe the bug**
I recently upgraded a cluster from 4.14.0-0.okd-2024-01-06-084517 to 4.15.0-0.okd-2024-01-27-070424, ever since then I have quite a few workloads failing to reach external resources. I see the following from a terminal within one of my pods: 

```
/app $ getent hosts redhat.com
172.28.20.1       redhat.com.apps.home.bstinson.com  redhat.com.apps.home.bstinson.com redhat.com
/app $ 
```

I would expect this to return the actual DNS records for redhat.com

Note: 172.28.20.1 is the floating load balancer IP of the cluster itself, and the DNS request is performed relative to my cluster domain. 

**Version**
IPI, Bare metal. I started with 4.14.0-0.okd-2023-12-01-225814 a number of weeks ago and have upgraded periodically  to 4.15.0-0.okd-2024-01-27-070424

**How reproducible**
100%

**Comment by vrutkovs** [comment]
Please attach (or upload to the public file sharing service) [must-gather](https://docs.okd.io/latest/support/gathering-cluster-data.html#support_gathering_data_gathering-cluster-data) archive
