### ISSUE TITLE
Image mirroring issue on builds

### ISSUE THREAD

**Issue by maps1995** [okd-project/okd#1872]
**Describe the bug**
Hi,

We have asked about image mirroring in builds in several discussions such as the below discussion and we haven't received a response for it, could you help us with this question, please?

https://github.com/okd-project/okd/discussions/1632

Kind regards

**Version**

**How reproducible**

**Log bundle**

**Comment by vrutkovs** [comment]
This isn't the reason to open a new issue with no additional information
