### ISSUE TITLE
[OKD 4.14] Bootstrap installation failed

### ISSUE THREAD

**Issue by ObieBent** [okd-project/okd#1873]
**Describe the bug**

I'm trying to install OKD 4.14 but the installation process stucks after the release-image service has downloaded the image. 
Thanks in advance for your support. 

**Version**

4.14.0-0.okd-2024-01-06-084517

**How reproducible**

**Log bundle**

[log-bundle-20240129141008.tar.gz](https://github.com/okd-project/okd/files/14084748/log-bundle-20240129141008.tar.gz)

**Comment by jcpowermac** [comment]
Looks like there is issues pulling images. 

```
    "errorLine": "24 main /usr/local/bin/bootstrap-pivot.sh",
    "errorMessage": "time=\"2024-01-29T13:08:44Z\" level=warning msg=\"Failed, retrying in 1s ... (2/3). Error: initializing source docker://quay.io/openshift/okd-content@sha256:b3a9a33f56137677f4505e2964c48b1ce9801addddbb6c0ebf612ce8223bcbf9: (Mirrors also failed: [registry.bomar.bme.lab:5000/ocp4/okd@sha256:b3a9a33f56137677f4505e2964c48b1ce9801addddbb6c0ebf612ce8223bcbf9: reading manifest sha256:b3a9a33f56137677f4505e2964c48b1ce9801addddbb6c0ebf612ce8223bcbf9 in registry.bomar.bme.lab:5000/ocp4/okd: manifest unknown]): quay.io/openshift/okd-content@sha256:b3a9a33f56137677f4505e2964c48b1ce9801addddbb6c0ebf612ce8223bcbf9: pinging container registry quay.io: Get \\\"https://quay.io/v2/\\\": net/http: TLS handshake timeout\"\ntime=\"2024-01-29T13:09:05Z\" level=warning msg=\"Failed, retrying in 1s ... (3/3). Error: initializing source docker://quay.io/openshift/okd-content@sha256:b3a9a33f56137677f4505e2964c48b1ce9801addddbb6c0ebf612ce8223bcbf9: (Mirrors also failed: [registry.bomar.bme.lab:5000/ocp4/okd@sha256:b3a9a33f56137677f4505e2964c48b1ce9801addddbb6c0ebf612ce8223bcbf9: reading manifest sha256:b3a9a33f56137677f4505e2964c48b1ce9801addddbb6c0ebf612ce8223bcbf9 in registry.bomar.bme.lab:5000/ocp4/okd: manifest unknown]): quay.io/openshift/okd-content@sha256:b3a9a33f56137677f4505e2964c48b1ce9801addddbb6c0ebf612ce8223bcbf9: pinging container registry quay.io: Get \\\"https://quay.io/v2/\\\": net/http: TLS handshake timeout\"\nError: initializing source docker://quay.io/openshift/okd-content@sha256:b3a9a33f56137677f4505e2964c48b1ce9801addddbb6c0ebf612ce8223bcbf9: (Mirrors also failed: [registry.bomar.bme.lab:5000/ocp4/okd@sha256:b3a9a33f56137677f4505e2964c48b1ce9801addddbb6c0ebf612ce8223bcbf9: reading manifest sha256:b3a9a33f56137677f4505e2964c48b1ce9801addddbb6c0ebf612ce8223bcbf9 in registry.bomar.bme.lab:5000/ocp4/okd: manifest unknown]): quay.io/openshift/okd-content@sha256:b3a9a33f56137677f4505e2964c48b1ce9801addddbb6c0ebf612ce8223bcbf9: pinging container registry quay.io: Get \"https://quay.io/v2/\": net/http: TLS handshake timeout"
 ```

**Comment by ObieBent** [comment]
Thanks for your reply, I think it is related to the mirroring process on my private registry. 

`Jan 29 14:31:34 bootstrap.bomar.bme.lab bootkube.sh[15003]: Error: initializing source docker://quay.io/openshift/okd-content@sha256:16beb5268ddaf74ba2e2466991a84c6134a4115c3ace2dbdaa91ddf01a184b1f: (Mirrors also failed: [registry.bomar.bme.lab:5000/ocp4/okd@sha256:16beb5268ddaf74ba2e2466991a84c6134a4115c3ace2dbdaa91ddf01a184b1f: reading manifest sha256:16beb5268ddaf74ba2e2466991a84c6134a4115c3ace2dbdaa91ddf01a184b1f in registry.bomar.bme.lab:5000/ocp4/okd: manifest unknown]): quay.io/openshift/okd-content@sha256:16beb5268ddaf74ba2e2466991a84c6134a4115c3ace2dbdaa91ddf01a184b1f: pinging container registry quay.io: Get "https://quay.io/v2/": net/http: TLS handshake timeout`

I'll try to relaunch it and see what's happen next.

**Comment by vrutkovs** [comment]
Check if its https://github.com/okd-project/okd/discussions/1815#discussioncomment-7705239?
