### ISSUE TITLE
Unable to upgrade, etcd backup pod fails

### ISSUE THREAD

**Issue by bianchi2** [okd-project/okd#1879]
When trying to upgrade, etc-packup pod  errors out with:
```
+ '[' -n /etc/kubernetes/cluster-backup ']'
+ echo 'removing all backups in /etc/kubernetes/cluster-backup'
+ rm -rf /etc/kubernetes/cluster-backup
removing all backups in /etc/kubernetes/cluster-backup
rm: cannot remove '/etc/kubernetes/cluster-backup': Device or resource busy
```
OKD is installed on AWS.

**Version**
4.14.0-0.okd-2024-01-06-084517

**Comment by marlonfrank30** [comment]
man having the same issue... have you got any feedback?

**Comment by JaimeMagiera** [comment]
Hi,

We are not working on FCOS builds of OKD any more. Please see these documents...

https://okd.io/blog/2024/06/01/okd-future-statement
https://okd.io/blog/2024/07/30/okd-pre-release-testing

We will be providing documentation on upgrading clusters from 4.15 FCOS to 4.16 SCOS. In terms of clusters that are older, you may be able to get help from community members. I'll convert this to a discussion to facilitate that.

Many thanks,

Jaime
