### ISSUE TITLE
Helm Chart cannot be installed

### ISSUE THREAD

**Issue by homesicker** [okd-project/okd#1900]
**Describe the bug**
It is impossible to install something from the custom helm chart from the developer console. Installation from cli is successful.

**Version**
4.15.0-0.okd-2024-02-10-035534

**How reproducible**
Add custom helm repository, try to install helm chart from developer console. My OKD on air-gapped env, and I use JFrog to proxy the helm repository, on this example I try install airflow from bitnami.

**Log bundle**
Unfortunately I cannot attach full logs due to confidentiality.
This error showing in developer console, after click Install on helm chart

Helm Chart cannot be installed
The Helm Chart is currently unavailable. r: Failed to retrieve chart: error locating chart: looks like "https://*changed*" is not a valid chart repository or cannot be reached: open /.cache/helm/repository/HICBXQckXENriy8g4WdGOsXAnWM=-index.yaml: no such file or directory

I found that the Helm installation is called from the openshift-console pod, so this folder is not there.

**Comment by codespearhead** [comment]
As [this comment](https://github.com/bitnami/charts/issues/8433#issuecomment-1720806963) states:

> We changed the bitnami/charts helm repository to use OCI. Check the new instructions here https://github.com/bitnami/charts/
