### ISSUE TITLE
Outdated openshift client embedded in the okd-content image for cli-artifacts

### ISSUE THREAD

**Issue by Bengrunt** [okd-project/okd#1909]
**Describe the bug**

On our OKD 4 clusters the image used by the `downloads` deployment in the `openshift-console` namespace is using an `okd-content` image that ships with outdated CLI binaries. Hence, our users download outdated CLI binaries from the console and cannot take advantage of the latest development in the CLI and risk bugs or unforeseeable behaviour when using such CLIs against recent clusters.

```
$ docker run --rm -it quay.io/openshift/okd-content:4.15.0-0.okd-2024-03-10-010116-cli-artifacts sh
Unable to find image 'quay.io/openshift/okd-content:4.15.0-0.okd-2024-03-10-010116-cli-artifacts' locally
4.15.0-0.okd-2024-03-10-010116-cli-artifacts: Pulling from openshift/okd-content
cae1910675af: Download complete
be8225157a48: Download complete
dd6a89444ec3: Download complete
9ebf1a2cd7c3: Download complete
7965a2a32d04: Download complete
Digest: sha256:801b3b97a33acb7830dd24c529d4d77d5680a2ced7953a843da020167c9b66a5
Status: Downloaded newer image for quay.io/openshift/okd-content:4.15.0-0.okd-2024-03-10-010116-cli-artifacts
sh-4.4# find / -name oc
/usr/share/openshift/linux_ppc64le/oc
/usr/share/openshift/mac_arm64/oc
/usr/share/openshift/mac/oc
/usr/share/openshift/linux_amd64/oc
/usr/share/openshift/linux_arm64/oc
/usr/share/openshift/linux_s390x/oc
/usr/bin/oc
sh-4.4# /usr/bin/oc version
Client Version: v4.2.0-alpha.0-2106-gd6175eb
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
sh-4.4# /usr/share/openshift/linux_amd64/oc version
Client Version: v4.2.0-alpha.0-2106-gd6175eb
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
```

It's the same with the `quay.io/openshift/okd-content:4.13.0-0.okd-2023-10-28-065448` image used by our clusters.
Seems like this issue is there since a very long time (several years).

**Version**
Server Version: 4.13.0-0.okd-2023-10-28-065448
UPI bare metal installation.

**How reproducible**
It's always there.

Thanks !

**Comment by codespearhead** [comment]
I can corroborate the existence of this issue. Needs investigation.

**Comment by codespearhead** [comment]
@vrutkovs What codebase should we look into to troubleshoot this issue?

**Comment by jacksgt** [comment]
Hi,
unfortunately this is a well-known and long-standing issue: https://github.com/okd-project/okd/issues/447

**Comment by codespearhead** [comment]
Can you close this in favor of #447 ?

If this is any consolation, see (this comment)[https://github.com/okd-project/okd/issues/731#issuecomment-872295494] in #731 .

**Comment by Bengrunt** [comment]
Closing this in favor of #447 as suggested.
