### ISSUE TITLE
Bootstrap process could not start in Disconnected installation

### ISSUE THREAD

**Issue by parseltongued** [okd-project/okd#1932]
Hi, 

**Describe the bug**
My initial intent was to setup a 3 nodes disconnected OKD 4.15 cluster via _mirror registry for Red Hat OpenShift_ on Red Hat Quay. 

The mirroring of OKD images was successful:
![image](https://github.com/okd-project/okd/assets/120156491/02afb14f-3b04-4dbd-8614-7e0c8c176fcc)
after mirroring, executed openshift-install.

In the disconnected environment, after the images were successfully downloaded from the internal mirror repository, the bootstrap process could not start (ie. bootstrap node did not auto restart, control-plane nodes hung in pinging port 22623). However when using an internet-facing forward proxy in ignition config, the bootstrap process ran successfully and the cluster was installed.

The bootstrap process could not start without internet access, is there any remediation? 

**How reproducible**
Always reproducible

**Deployment information**
OKD Cluster Version: 4.15.0-0.okd-2024-03-10-010116
Kernel version: v1.28.2-3598+6e2789bbd58938-dirty

Thank you

**Comment by JaimeMagiera** [comment]
Hi,

We are not working on FCOS builds of OKD any more. Please see these documents...

https://okd.io/blog/2024/06/01/okd-future-statement
https://okd.io/blog/2024/07/30/okd-pre-release-testing

Please test with the OKD SCOS nightlies and file a new issue as needed.

Many thanks,

Jaime
