### ISSUE TITLE
No CNI configuration file in /etc/kubernetes/cni/net.d/. Has your network provider started?

### ISSUE THREAD

**Issue by fcolomas** [okd-project/okd#1966]
**Describe the bug**

I'm trying to install a Compact OpenShift Cluster :

Bootstrap Node
3 Master Nodes
2 Worker Nodes

Now on the Bastion Host when I'm trying to run the following command to get the ready nodes

oc get nodes

NAME STATUS ROLES AGE VERSION
master01.ocp4.example.net NotReady control-plane,master 16h v1.27.6+b49f9d1
master02.ocp4.example.net Ready control-plane,master 17h v1.27.6+b49f9d1
master03.ocp4.example.net Ready control-plane,master 17h v1.27.6+b49f9d1

Trying to troubleshoot master01 node

[root@master01 ~]# journalctl -f _SYSTEMD_UNIT=kubelet.service 

I get the following error

Dec 26 13:55:09 master01.ocp4.example.net kubenswrapper[6041]: E1226 13:55:09.237534    6041 pod_workers.go:1300] "Error syncing pod, skipping" err="network is not ready: container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: No CNI configuration file in /etc/kubernetes/cni/net.d/. Has your network provider started?" pod="openshift-network-diagnostics/network-check-target-dfvs9" podUID=4cfd7421-4506-4b88-b199-efa7210eef95

**Version**

4.15.0-0.okd-2024-03-10-010116

**How reproducible**

100% using the Agent installer for OCI

**Log bundle**

Referenced the discussion where multiple users have the same problem: https://access.redhat.com/discussions/7050416

I also have it for SCN topology, after applying the solution proposed on the comments it works

**Comment by fcolomas** [comment]
Workaround from Konstantin Rebrov :

I had similar issue with OCP 4.14. fixed it by creating manually config for CNI

cat << EOF | tee /etc/kubernetes/cni/net.d/10-containerd-net.conflist
{
 "cniVersion": "1.0.0",
 "name": "containerd-net",
 "plugins": [
   {
     "type": "bridge",
     "bridge": "cni0",
     "isGateway": true,
     "ipMasq": true,
     "promiscMode": true,
     "ipam": {
       "type": "host-local",
       "ranges": [
         [{
           "subnet": "10.128.0.0/14"
         }]
       ],
       "routes": [
         { "dst": "0.0.0.0/0" },
         { "dst": "::/0" }
       ]
     }
   },
   {
     "type": "portmap",
     "capabilities": {"portMappings": true},
     "externalSetMarkChain": "KUBE-MARK-MASQ"
   }
 ]
}
EOF

Here you need to modify your network accordingly Then restart services at the master nodes:

# systemctl restart crio; systemctl restart kubelet; systemctl status crio

**Comment by Antvirf** [comment]
For me this was an issue with network overlaps, and adding any CNI config manually had no effect.

Fixing this was just a matter of sizing everything properly, segregating the networks so they don't overlap, and also explicitly specifying the `networking.machineNetwork` parameter in `install-config.yaml`

In my case;

- Physical network was serving out `10.0.0.0/8` at the time, which was way too big so I changed that to a smaller block
- The cluster network cidr was set to `10.128.0.0/14` - which overlaps with the physical network set above


Working config snippet for me was:

```
...
networking:
  machineNetwork:
    - cidr: 10.10.0.0/16 # Must match whatever your router gives out
  clusterNetwork:
    - cidr: 10.128.0.0/14 # Must NOT overlap with physical network of the machines above
      hostPrefix: 23
  networkType: OVNKubernetes
  serviceNetwork:
    - 172.30.0.0/16 # left this as default
...
```
