### ISSUE TITLE
IBM Cloud create cluster failed

### ISSUE THREAD

**Issue by oborges** [okd-project/okd#1990]
**Describe the bug**
openshift-install create cluster fails on IBM Cloud option

**Version**

OKD version release: 4.15.0-0.okd-2024-03-10-010116
tool version: openshift-install-mac-arm64-4.15.0-0.okd-2024-03-10-010116
Cloud platform: IBM Cloud

**How reproducible**
100%

**Log bundle**

(venv) *supressed* openshift-install-mac-arm64-4.15.0-0.okd-2024-03-10-010116 % ./openshift-install create cluster 
? SSH Public Key /id_rsa.pub
? Platform ibmcloud
? Region br-sao
FATAL failed to fetch Metadata: failed to fetch dependency of "Metadata": failed to fetch dependency of "Cluster ID": failed to fetch dependency of "Install Config": failed to generate asset "Base Domain": failed to load IBM SDK services: Exactly one of ApiKey or RefreshToken must be specified.

**Comment by JaimeMagiera** [comment]
Hi, 

We're not actually working on 4.15, or FCOS builds of OKD in general, any more. Please see these documents...

https://okd.io/blog/2024/06/01/okd-future-statement
https://okd.io/blog/2024/07/30/okd-pre-release-testing
https://github.com/okd-project/okd/blob/master/COMMUNITY-TESTING.md#getting-started

Please try with a recent SCOS-based nightly and let us know how it goes with a new discussion in the community-testing discussion threads.

Many thanks,

Jaime
