### ISSUE TITLE
Marketplace uses Images from registry.redhat.io and enables too many catalogs

### ISSUE THREAD

**Issue by gudroot** [okd-project/okd#1996]
**Describe the bug**
I tried my first okd-scos installation today (4.16.0-0.okd-scos-2024-08-02-172403). 

The installation went well, but when it was done I noticed that the marketplace-operator now contains only images from http://registry.redhat.io/ for all the catalogs. Since I only provided the fake pull-secret, my cluster can't pull images from that registry and I now have 8 pods in state "Init:ImagePullBackOff", 2 for each of the catalogs (community, certified, redhat-operators and redhat-marketplace). Not only is having 8 broken pods by default kind of ugly, it also rises the question of why those catalogs were not disabled by default.

I compared with an old OKD 4.15 cluster that had all but the community operators disabled and additionally was using quay.io for the catalog pods. This is what would be expected: the installation of OKD should be possible using a fake pull-secret and only those operator catalogs, that can be used without a subscription, should be present, i.e. only community operators.

**Version**
4.16.0-0.okd-scos-2024-08-02-172403)
UPI installation on "none" platform.

**Comment by Reamer** [comment]
Compare your configuration with the following. This should actually only activate the Community-Operator.
https://github.com/operator-framework/operator-marketplace/blob/master/hack/okd/0000_03_marketplace-operator_02_operatorhub.cr.yaml

**Comment by gudroot** [comment]
The version in my cluster is different from the "hack":

```apiVersion: config.openshift.io/v1
kind: OperatorHub
metadata:
  name: cluster
spec: {}
status:
  sources:
  - disabled: false
    name: redhat-operators
    status: Success
  - disabled: false
    name: certified-operators
    status: Success
  - disabled: false
    name: community-operators
    status: Success
  - disabled: false
    name: redhat-marketplace
    status: Success
```

So the version of that config that should have come from the source you named was never actually applied. This is one of the issues, the other being that it tries to pull the images from the wrong registry.

**Comment by JaimeMagiera** [comment]
Thanks for your issue. A bug is being filed to correct this in the OKD build process. The Red Hat catalogs will be removed and a single operator hub catalog (with the public image URL) will be added.
