### ISSUE TITLE
New updates/upgrades are not availabe

### ISSUE THREAD

**Issue by cronchiq** [okd-project/okd#2012]
**Describe the bug**
Cannot upgrade the cluster to a newer version than 4.15.0-0.okd-2024-03-10-010116. Updates are not available.

**Version**
4.15.0-0.okd-2024-03-10-010116

**How reproducible**
Upgrade cluster from 4.15.0-0.okd-2024-02-10-035534 to 4.15.0-0.okd-2024-03-10-010116

**Comment by JaimeMagiera** [comment]
Hi,

There are no newer version of OKD at this time. We are not working on FCOS builds of OKD any more. Please see these documents...

https://okd.io/blog/2024/06/01/okd-future-statement
https://okd.io/blog/2024/07/30/okd-pre-release-testing

We will be providing documentation on upgrading clusters from 4.15 FCOS to 4.16 SCOS when a stable release is available. 

Many thanks,

Jaime
