### ISSUE TITLE
F5 Load Balancer Only Recognizes 2 of 5 Worker Nodes as Active in OKD Cluster

### ISSUE THREAD

**Issue by ahmedalazazy** [okd-project/okd#2043]
@vrutkovs kindly your support 
After installing the OKD cluster with the following configuration:

OKD version is: 4.15 stable 
fedora core os version : fedora-coreos-40.20240728.3.0-metal.x86_64.raw.xz
installation type is: any platform platform  in VM's in VMware

3 master nodes
5 worker nodes
2 load balancers (LB) in F5, handling:
Ports 6443 and 22623
Ports 443 and 80
All worker nodes are ready and functioning properly within the cluster. However, the F5 load balancer only recognizes 2 worker nodes as active, while the remaining 3 are marked as inactive.

When I attempt to telnet to port 443:

It works on the active nodes as seen by the F5.
It does not work on the inactive nodes, neither from the VMs' IPs nor from within the VMs themselves (the 443 port is not responding).
How can I resolve this issue to ensure that all worker nodes are active in F5 and capable of handling incoming application requests?

_Originally posted by @ahmedalazazy in https://github.com/okd-project/okd/discussions/1903#discussioncomment-10969501_

**Comment by JaimeMagiera** [comment]
Hi,

The OKD Working Group is transitioning OKD to an SCOS base and can only provide minimal guidance on versions <= 4.15. Please see these documents...

https://okd.io/blog/2024/06/01/okd-future-statement
https://okd.io/blog/2024/07/30/okd-pre-release-testing

We will be providing documentation on upgrading clusters from 4.15 FCOS to 4.16 SCOS when a stable release is available.

Many thanks,

Jaime
