### ISSUE TITLE
Invalid version reported by `oc`

### ISSUE THREAD

**Issue by aneagoe** [okd-project/okd#447]
**Describe the bug**
Following an upgrade to version `4.6.0-0.okd-2020-12-12-135354` from `4.6.0-0.okd-2020-11-27-200126`, I've noticed that downloading the cli from the downloads section of the cluster provides a much older cli, version `v4.2.0-alpha.0-823-g299b6af`

**Version**
4.6.0-0.okd-2020-12-12-135354

**How reproducible**
Always, just curl/wget the cli from https://downloads-openshift-console.DOMAIN/amd64/linux/oc.tar

**Log bundle**
N/A

**Comment by bdlink** [comment]
This is a longstanding issue.  Perhaps change links to something that is updated, so the link does not change each update.
Similarly to https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/ which seems to be at 4.6.8 at the moment.

**Comment by codespearhead** [comment]
[This seems](https://github.com/openshift/oc/issues/1688) to be the cause, so once it's fixed there, this problem will be solved.

**Comment by codespearhead** [comment]
By the way, @vrutkovs , it seems that you're the one pushing new releases.

I'm not familiar with releases, so if you have the bandwidth to point us the the right direction with regards to that issue, we'd appreciated it.

**Comment by vrutkovs** [comment]
I no longer work on OKD, please tag @LorbusChris instead

**Comment by JaimeMagiera** [comment]
Closing this as the issue will be resolved in the new OKD SCOS releases.
