### ISSUE TITLE
CoreDNS is returning SERVFAIL for % of requests

### ISSUE THREAD

**Issue by devops-42** [okd-project/okd#618]
**Describe the bug**
We have an OKD cluster installed in version 4.6.0-0.okd-2021-02-14-205305. Everything seems to work fine, but the monitoring encounters a problem with the CoreDNS:

```
CoreDNS is returning SERVFAIL for x% of requests
```

The amount of failed request varies from 2% up to 18%. We already tried troubleshooting as described on https://access.redhat.com/solutions/3804501. As a result of these tests we saw, that sometimes UDP connect to our forwarding DNS runs into timeouts. I checked with `socat` on the `dns-default-*` pods, but UDP connection is working fine, resolving hostnames from the forwarder works as expected.
Also testing resolving kubernetes service hostname to and from every DNS pod and testing resolving external DNS entries like redhat.com works without problems.
 
Moreover we checked workload on our DNS instances, which is constantly below 2% load.

Unfortunately it's not possible to configure logging in the according configmap, the operator restores the state of the configmap immediately.
 
Any help would be appreciated!

**Version**
4.6.0-0.okd-2021-02-14-205305 (Baremetal)

**How reproducible**
The error occurs constantly

**Log bundle**
N/A

**Comment by sgreene570** [comment]
Could you share the available CoreDNS logs when youre hitting this issue? 

Your upstream resolver isn't returning very large UDP DNS responses, is it? 
If so, you could potentially be hitting https://github.com/openshift/cluster-dns-operator/pull/266 (That patch has not been back-ported to 4.6 yet).

What platform is this on, and what does your upstream resolver look like?

**Comment by kai-uwe-rommel** [comment]
We had the same problem, on an OCP cluster. Since I was unable to find out where this came from, I even opened a RH support case. Finally, during that we saw that the failures came only from a set of three of the worker nodes. So I looked for a deployment which had three instances on exactly these nodes. I found that in our case it was a Vault deployment. Apparently its pods frequently did DNS lookups for some invalid names. I scaled it down to zero for a test (it was a test deployment anyway) and the problems went away.
You could search for the cause on your cluster in a similar way. Unfortunately, CoreDNS does not per default log failed lookups (and where these come from) and I have not yet found docs on how to change that.

**Comment by devops-42** [comment]
Hi @kai-uwe-rommel, thanks for commenting. We use the cluster for developing pods only, no Vault or other infrastructural components are deployed within the cluster.

@sgreene570 
Our upstream resolver is a FreeIPA instance. It's possible that we run into the bug mentioned by you. Here's a (redacted) log output from one of the `dns-default-*` pods:

```
.:5353
[INFO] plugin/reload: Running configuration MD5 = 16d10c9396a4095338f9a5f9437a4813
CoreDNS-1.6.6
linux/amd64, go1.15.5,
[ERROR] plugin/errors: 2 oauth-openshift.apps.example.com. AAAA: read udp *.*.*.*:45846->DNS.IP.ADD.RESS:53: i/o timeout
[ERROR] plugin/errors: 2 oauth-openshift.apps.example.com. A: read udp *.*.*.*:47080->DNS.IP.ADD.RESS:53: i/o timeout
[ERROR] plugin/errors: 2 oauth-openshift.apps.example.com. AAAA: read udp *.*.*.*:33245->DNS.IP.ADD.RESS:53: i/o timeout
[ERROR] plugin/errors: 2 oauth-openshift.apps.example.com. A: read udp *.*.*.*:36114->DNS.IP.ADD.RESS:53: i/o timeout
[ERROR] plugin/errors: 2 oauth-openshift.apps.example.com. A: read udp *.*.*.*:33305->DNS.IP.ADD.RESS:53: i/o timeout
[ERROR] plugin/errors: 2 *.*.*.*.in-addr.arpa. PTR: read udp *.*.*.*:50190->DNS.IP.ADD.RESS:53: i/o timeout
[ERROR] plugin/errors: 2 oauth-openshift.apps.example.com. AAAA: read udp *.*.*.*:34309->DNS.IP.ADD.RESS:53: i/o timeout
[ERROR] plugin/errors: 2 oauth-openshift.apps.example.com. A: read udp *.*.*.*:53962->DNS.IP.ADD.RESS:53: i/o timeout
[ERROR] plugin/errors: 2 oauth-openshift.apps.example.com. A: read udp *.*.*.*:40405->DNS.IP.ADD.RESS:53: i/o timeout
[ERROR] plugin/errors: 2 oauth-openshift.apps.example.com. A: read udp *.*.*.*:50294->DNS.IP.ADD.RESS:53: i/o timeout
[ERROR] plugin/errors: 2 *.*.*.*.in-addr.arpa. PTR: read udp *.*.*.*:53415->DNS.IP.ADD.RESS:53: i/o timeout
[ERROR] plugin/errors: 2 *.*.*.*.in-addr.arpa. PTR: read udp *.*.*.*:42591->DNS.IP.ADD.RESS:53: read: connection refused
[ERROR] plugin/errors: 2 oauth-openshift.apps.example.com. AAAA: read udp *.*.*.*:56996->DNS.IP.ADD.RESS:53: read: connection refused
[ERROR] plugin/errors: 2 infogw.api.openshift.com. A: read udp *.*.*.*:49239->DNS.IP.ADD.RESS:53: read: connection refused
[ERROR] plugin/errors: 2 oauth-openshift.apps.example.com. AAAA: read udp *.*.*.*:34336->DNS.IP.ADD.RESS:53: i/o timeout
[ERROR] plugin/errors: 2 oauth-openshift.apps.example.com. A: read udp *.*.*.*:46495->DNS.IP.ADD.RESS:53: i/o timeout
[ERROR] plugin/errors: 2 oauth-openshift.apps.example.com. AAAA: read udp *.*.*.*:59693->DNS.IP.ADD.RESS:53: i/o timeout
[ERROR] plugin/errors: 2 *.*.*.*.in-addr.arpa. PTR: read udp *.*.*.*:60716->DNS.IP.ADD.RESS:53: i/o timeout
[ERROR] plugin/errors: 2 *.*.*.*.in-addr.arpa. PTR: read udp *.*.*.*:36320->DNS.IP.ADD.RESS:53: read: connection refused
[ERROR] plugin/errors: 2 infogw.api.openshift.com. AAAA: read udp *.*.*.*:46950->DNS.IP.ADD.RESS:53: i/o timeout
[ERROR] plugin/errors: 2 *.*.*.*.in-addr.arpa. PTR: read udp *.*.*.*:56272->DNS.IP.ADD.RESS:53: i/o timeout
[ERROR] plugin/errors: 2 *.*.*.*.in-addr.arpa. PTR: read udp *.*.*.*:38057->DNS.IP.ADD.RESS:53: read: connection refused
[ERROR] plugin/errors: 2 *.*.*.*.in-addr.arpa. PTR: read udp *.*.*.*:37620->DNS.IP.ADD.RESS:53: i/o timeout
[ERROR] plugin/errors: 2 *.*.*.*.in-addr.arpa. PTR: read udp *.*.*.*:60984->DNS.IP.ADD.RESS:53: read: connection refused
[ERROR] plugin/errors: 2 *.*.*.*.in-addr.arpa. PTR: read udp *.*.*.*:44038->DNS.IP.ADD.RESS:53: i/o timeout
[ERROR] plugin/errors: 2 oauth-openshift.apps.example.com. AAAA: read udp *.*.*.*:45624->DNS.IP.ADD.RESS:53: read: connection refused
[ERROR] plugin/errors: 2 oauth-openshift.apps.example.com. AAAA: read udp *.*.*.*:60720->DNS.IP.ADD.RESS:53: i/o timeout
[ERROR] plugin/errors: 2 oauth-openshift.apps.example.com. A: read udp *.*.*.*:50658->DNS.IP.ADD.RESS:53: read: connection refused
[ERROR] plugin/errors: 2 *.*.*.*.in-addr.arpa. PTR: read udp *.*.*.*:41286->DNS.IP.ADD.RESS:53: i/o timeout
[ERROR] plugin/errors: 2 *.*.*.*.in-addr.arpa. PTR: read udp *.*.*.*:39732->DNS.IP.ADD.RESS:53: i/o timeout
[ERROR] plugin/errors: 2 *.*.*.*.in-addr.arpa. PTR: read udp *.*.*.*:46826->DNS.IP.ADD.RESS:53: i/o timeout
I*.*.*.*:43.941902       1 trace.go:205] Trace[997930479]: "Reflector ListAndWatch" name:github.com/coredns/coredns/plugin/kubernetes/controller.go:333 (28-Apr-*.*.*.*:33.664) (total time: 10277ms):
Trace[997930479]: ---"Objects listed" 10277ms (08:52:00.941)
Trace[997930479]: [10.277520836s] [10.277520836s] END
I*.*.*.*:03.290624       1 trace.go:205] Trace[1612670413]: "Reflector ListAndWatch" name:github.com/coredns/coredns/plugin/kubernetes/controller.go:326 (28-Apr-*.*.*.*:34.933) (total time: 28356ms):
Trace[1612670413]: ---"Objects listed" 28356ms (08:53:00.290)
Trace[1612670413]: [28.356875786s] [28.356875786s] END
I*.*.*.*:46.529687       1 trace.go:205] Trace[764401649]: "Reflector ListAndWatch" name:github.com/coredns/coredns/plugin/kubernetes/controller.go:328 (01-May-*.*.*.*:33.646) (total time: 12882ms):
Trace[764401649]: ---"Objects listed" 12882ms (18:21:00.529)
Trace[764401649]: [12.882751816s] [12.882751816s] END
I*.*.*.*:07.618927       1 trace.go:205] Trace[1603465549]: "Reflector ListAndWatch" name:github.com/coredns/coredns/plugin/kubernetes/controller.go:328 (03-May-*.*.*.*:52.319) (total time: 15299ms):
Trace[1603465549]: ---"Objects listed" 15299ms (11:57:00.618)
Trace[1603465549]: [15.299487588s] [15.299487588s] END
```

The first block of errors could've been created when starting the pod. Unfortunately there's almost no timestamp within the log output. We'll try to update the cluster to 4.7 within the next days, I'll keep you informed whether the error has gone.

**Comment by sgreene570** [comment]
> Unfortunately, CoreDNS does not per default log failed lookups (and where these come from) and I have not yet found docs on how to change that.

@kai-uwe-rommel we have a ticket to add a DNS log level API in our backlog. Currently, you cannot adjust the CoreDNS logging level via the dns operator.

**Comment by devops-42** [comment]
Hi @sgreene570, meanwhile we updated our cluster to 4.7 (4.7.0-0.okd-2021-04-24-103438), but the problem still remains. Are there further methods to debug/investigate the issue?

**Comment by sgreene570** [comment]
@devops-42 bit of an in-depth idea, but you could use wireshark to gather packet captures of the failing DNS queries and take a closer look at them. 
Or you could put the DNS operator in an unmanaged state by temporarily scaling down the CVO and the operator, which would let you modify the CoreDNS corefile to enable debug logging. Note that putting the operator into an unmanaged state is entirely unsupported and in general not recommended.

**Comment by fortinj66** [comment]
I am seeing this issue on my OKD 4.10 production and QA cluster...

**Comment by cberg-aot** [comment]
I also am encountering this issue, specifically with registry.redhat.io.   The large amount of bad DNS lookups is a clue I think

**Comment by vrutkovs** [comment]
/lifecycle stale

Is this is still reproducible in 4.12?

**Comment by seb2020** [comment]
We are in OpenShift 4.10 and it seems that we have the same issue.

**Comment by kai-uwe-rommel** [comment]
I agree that it is not really an issue. However, I think an improvement would make sense. The problem is, that any misbehaving deployment can (by doing lots of failing DNS lookups) cause an alert for a system component (CoreDNS). This is misleading.
